/******************************************************************************
**
** File:	ims_opCat.h
**
** Function:	This is the header file for the ims_opCat.c functions which
**		perform catalog queries and updates for the operator interface.
**
** Author:	Hoshyar Sayah, Jennifer Ting
**
** Date:	 12/14/94
**
** Revision History: 
**  04/26/96         J. Ting   Added events OP_UPDATEITEMSTEPINFO,
**             								 OP_GETORDERITEMINFO, OP_GETITEMSTEPINFO
**
**  05/09/96         J. Ting   Added event OP_GETSTEPNAMEPPSSTATUS
**  07/12/96         J. Ting   Added event OP_RESTARTITEM
**  07/23/97			   D. Ting   Added OP_ACC_DELETEACCOUNTEXTENSION
**
******************************************************************************/

#ifndef _IMS_OPCAT_H
#define _IMS_OPCAT_H

static char *sccsOpCat = "@(#)ims_opCat.h	5.8  09/15/97";

#define OP_SERVER ""
#define OP_DBNAME ""
#define OP_PROGRAM "ims_op"


/*
** Internal CDB file descriptor.  Contains information on files, most
** of which comes from the catalog.
*/

typedef struct opCatUserSpec 
{
	char *dbUserName;
	char *dbPassword;
	char *program;
	char *server;
	char *dbName;
} OP_CAT_USERSPEC;   

/*
** Following is the request structure for database processing and interface.
*/

typedef struct opCatStruct
{
	IMS_MSG_STRUCT *msgDesc;  /* msg facility descriptor */
	IMS_QI_DESC_OBJ *qDesc;   /* query descriptor, ims_qi */
	OP_CAT_USERSPEC userSpec;	/* database login information. */
	void *item[10];           /* Array of pointers for input & output */
} OP_CAT_STRUCT;

/*
** op_cat events are listed below:
**
**      1. Open a connection to the catalog
**      2. Begin a transaction.
**      3. Rollback the transaction openned by BEGINTRANSACTION.
**      4. Commit the transaction openned by BEGINTRANSACTION.
**      5. Close the catalog connection openned by OPENCONNECTION.
**
** The following enum definitions define the above events.
*/

/*
** CAT events for the following screens:   
** Order Display, Order Search, Photo Order, Photo Job
** Film Generation, Media Device Status, Shipping & Billing
*/
typedef enum opCatEvent {OP_USEDATABASE, OP_OPENCONNECTION,  
OP_BEGINTRANSACTION, OP_ROLLBACKTRANSACTION, OP_COMMITTRANSACTION, 
OP_CLOSECONNECTION, OP_GETORDERLIST, OP_GETORDERITEMLIST, 
OP_GETORDERITEMSTATS, OP_GETCATALOGITEMS, OP_UPDATEORDERPRIORITY,
OP_UPDATEITEMPRIORITY, OP_GETNEWORDERPRIORITY, OP_GETORDERLOCK, 
OP_GETITEMLOCK, OP_UPDATEORDERCOMMENT, OP_UPDATEITEMCOMMENT,
OP_UPDATEORDERSTATUS, OP_UPDATEITEMSTATUS,
OP_VALIDATEORDER, OP_VALIDATEITEM, OP_GETNEWORDERSTATUS,
OP_GETUSERDATA, OP_GETACCOUNTIDLIST, OP_GETUSERIDLIST,
OP_GETPHOTOQUEUELIST, OP_CREATEPHOTOJOB, OP_UPDATEPHOTOQUEUE,
OP_UPDATEPHOTOJOB, OP_GETDATASETGRANULE, OP_GETGRANULESTABLE,
OP_GETPRODUCTNAME, OP_GETPHOTOJOBIDLIST, OP_GETPHOTOJOBLIST,
OP_UPDATEPHOTOCOMMENT, OP_UPDATEPHOTOQUALITY, OP_COMPLETEPHOTOJOB,
OP_UPDATEPHOTOJOBCOST, OP_GETTAPEITEMS, OP_GETMEDIACAPACITY,
OP_GETITEMSTATUS, OP_ROLLBACKITEMSTATUS, OP_GETITEMSTEPSEQUENCE,
OP_GETORDERSTATUS, OP_GETITEMACCOUNTCOST,
OP_GETFIREQUEUELIST, OP_GETLASERQUEUELIST, 
OP_UPDATEFIREITEMSTATUS, OP_UPDATELASERITEMSTATUS,
OP_GETFIREITEMSTATUS, OP_GETLASERITEMSTATUS,
OP_UPDATEFIREITEMCOMMENT, OP_UPDATELASERITEMCOMMENT,
OP_REMOVEFIREQUEUEITEM, OP_REMOVELASERQUEUEITEM,
OP_GETGENERALLOCK, OP_GETSHIPITEMS, OP_VERIFYITEMSHIPPINGSTATUS,
OP_GETSHIPPINGID, OP_GETSHIPPINGDATA, OP_UPDATEITEMSHIPPINGSTATUS,
OP_UPDATESHIPPINGCOMMENT, OP_CANCELSHIPMENT, OP_GETORDERSHIPIDLIST,
OP_GETBILLITEMS, OP_VERIFYITEMBILLINGSTATUS, OP_GETBILLINGDATA,
OP_UPDATEITEMBILLINGSTATUS, OP_GETBILLINGID, OP_CANCELBILLING,
OP_GETORDERBILLIDLIST, OP_GETOPCOMMENT, OP_UPDATEBILLINGCOMMENT,
OP_GETPPSGRANULESIZESTEPTIME, OP_GETDARDATA, OP_GETPHOTOITEMSTATUS,
OP_UPDATEITEMMEDIAID, OP_GETUSERTYPE, OP_UPDATECOSTDEBITFLAG,
OP_UPDATEITEMSTEPINFO, OP_GETORDERITEMINFO, OP_GETITEMSTEPINFO,
OP_GETSTEPNAMEPPSSTATUS, OP_RESTARTITEM, OP_GETKEYWORDVALUES,
OP_GETDOWNLINKLIST, OP_GETDOWNLINKDTKLIST, OP_GETAUXILIARYLOCK,
OP_UPDATEDTKPROCESSAUTHFLAG, OP_ISSUEDOWNLINKSCANREQUEST, OP_GETPHOTOJOBID
} OP_CAT_EVENT;


/*** Accounts and Users ***/

typedef enum opAccCatEvent {
OP_ACC_USEDATABASE, OP_ACC_OPENCONNECTION,  
OP_ACC_BEGINTRANSACTION, OP_ACC_ROLLBACKTRANSACTION, OP_ACC_COMMITTRANSACTION, 
OP_ACC_CLOSECONNECTION,
OP_ACC_GETUSERLIST, OP_ACC_GETACCOUNTLIST, 
OP_ACC_SAVEUSERDATA, OP_ACC_SAVEACCDATA,
OP_ACC_DELETEUSER, OP_ACC_DELETEACCOUNT, OP_ACC_DELETEACCOUNTMGR,
OP_ACC_GETACCOUNTLOCK,
OP_ACC_UPDATE_BEGIN_CURRENT_BALANCE, OP_ACC_GETDATASETS, OP_ACC_GETACCDATASETS,
OP_ACC_GETCATALOGITEMS, 
OP_ACC_GET_ALL_USERS, OP_ACC_GET_ASSIGN_USERS, 
OP_ACC_ADD_ASSIGN_USERS, OP_ACC_DELETE_ASSIGN_USERS,
OP_ACC_GET_ALL_DATASETS, OP_ACC_GET_ASSIGN_DATASETS, 
OP_ACC_ADD_ASSIGN_DATASETS, OP_ACC_DELETE_ASSIGN_DATASETS, OP_ACC_UPDATE_ASSIGN_DATASETS,
OP_ACC_DELETEACCOUNTUSER, OP_ACC_DELETEACCOUNTDATASET, OP_ACC_DELETEACCOUNTEXTENSION, OP_ACC_GETMANAGER 
} OP_ACC_CAT_EVENT ;


/*
** declaration of glbal routines
*/
int ims_opCat (OP_CAT_STRUCT *, OP_CAT_EVENT);
/*** Accounts and Users ***/
int ims_op_accCat (OP_CAT_STRUCT *, OP_ACC_CAT_EVENT);

#endif	/* !_IMS_OPCAT_H */
