Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/asf_meta/",
    "#src/libasf_proj/",
    "#src/libasf_import/",
    "#src/libasf_convert/",
    "#src/libasf_vector/",
    "/usr/include/libshp",
])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_convert",
])

bins = localenv.Program("asf_kml_overlay", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
