import os.path

Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/asf_meta/",
    "#src/libasf_proj/",
    "#src/libasf_import/",
    "#src/libasf_convert/",
    "#src/libasf_vector/",
])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs gsl")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_import",
    "asf_convert",
    "asf_proj",
    "asf_geocode",
    "asf_raster",
    "asf_vector",
    "asf_meta",
    "asf_ardop",
    "asf_export",
    "asf_sar",
    "asf_fft",
    "asf_terrcorr",
])

head_build_dir, tail_build_dir = os.path.split(Dir(".").path)

localenv.AppendUnique(LIBPATH = [
    "#" + os.path.join(head_build_dir, "asf"),
    "#" + os.path.join(head_build_dir, "libasf_convert"),
    "#" + os.path.join(head_build_dir, "libasf_proj"),
    "#" + os.path.join(head_build_dir, "libasf_geocode"),
    "#" + os.path.join(head_build_dir, "libasf_vector"),
    "#" + os.path.join(head_build_dir, "asf_meta"),
    "#" + os.path.join(head_build_dir, "libasf_export"),
    "#" + os.path.join(head_build_dir, "libasf_sar"),
    "#" + os.path.join(head_build_dir, "asf_fft"),
    "#" + os.path.join(head_build_dir, "libasf_import"),
    "#" + os.path.join(head_build_dir, "libasf_raster"),
    "#" + os.path.join(head_build_dir, "libasf_ardop"),
    "#" + os.path.join(head_build_dir, "libasf_terrcorr"),
])


bins = localenv.Program("asf_kml_overlay", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["bins"], bins)
