Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include",
        ])
    
localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")

libs = localenv.SharedLibrary("asf", [
        "asf_tiff.c",
        "check.c",
        "cla.c",
        "endian.c",
        "error.c",
        "fileUtil.c",
        "log.c",
        "stopwatch.c",
        "share.c",
        "strUtil.c",
        "system.c",
        "tmpdir.c",
        "license.c",
        "splash_screen.c",
        "print_alerts.c",
        "diagnostics.c",
        "matrix.c",
        "vector.c",
        "complex.c",
        "solve1d.c",
        "socket.c",
        "httpUtil.c",
        "caplib.c",
        ])

globalenv.Install(globalenv["inst_dirs"]["libs"], libs)

# run the unit test, and set its dependencies
test_result = localenv.UnitTest("test.semaphore", None)
localenv.Depends(test_result, [libs])
