#===============================================================================
# Filename:	Makefile
# Description:	Makefile for FTP and mail scripts
# Creator:	Norbert Piega
# Notes:	
#  1.  March '96 - R. Hoffman
#      Fixed typo in filename generic_cron.csh
#
# SCCS Info:
#  Makefile
#  1
#  22 Jan 1996
#  @(#)Makefile	1.2
#===============================================================================

all:
	cp ADEOS_ftpget.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/ADEOS_ftpget.csh
	cp ADEOSdirmon.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/ADEOSdirmon.csh
	cp CSA_ftpget.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/CSA_ftpget.csh
	cp CSAgetfile_all.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/CSAgetfile_all.csh
	cp ESAdirmon.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/ESAdirmon.csh
	cp ESA_ftpget.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/ESA_ftpget.csh
	cp ESA_ftpget_all.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/ESA_ftpget_all.csh
	cp FAIF_UNIX_ftpsend.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/FAIF_UNIX_ftpsend.csh
	cp FAIF_ESA_ftpsend.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/FAIF_ESA_ftpsend.csh
	cp FAIF_VAX_ftpsend.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/FAIF_VAX_ftpsend.csh
	cp FAIF_WALPS_ftpsend.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/FAIF_WALPS_ftpsend.csh
	cp J1_ftpget.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/J1_ftpget.csh
	cp J1_ftpget_all.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/J1_ftpget_all.csh
	cp NASDAdirmon.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/NASDAdirmon.csh
	cp WALPSdirmon.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/WALPSdirmon.csh
	cp mails.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/mails.csh
	cp kill_hung_proc.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/kill_hung_proc.csh
	cp mdel_ufdrf_orb.csh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/mdel_ufdrf_orb.csh
	cp line_at_a_time.sh ../../bin/sparc/.
	chmod 755 ../../bin/sparc/line_at_a_time.sh

clean:
	rm -f ../../bin/sparc/ADEOS_ftpget.csh
	rm -f ../../bin/sparc/ADEOSdirmon.csh
	rm -f ../../bin/sparc/CSA_ftpget.csh
	rm -f ../../bin/sparc/CSAgetfile_all.csh
	rm -f ../../bin/sparc/ESAdirmon.csh
	rm -f ../../bin/sparc/ESA_ftpget.csh
	rm -f ../../bin/sparc/ESA_ftpget_all.csh
	rm -f ../../bin/sparc/FAIF_UNIX_ftpsend.csh
	rm -f ../../bin/sparc/FAIF_ESA_ftpsend.csh
	rm -f ../../bin/sparc/FAIF_VAX_ftpsend.csh
	rm -f ../../bin/sparc/FAIF_WALPS_ftpsend.csh
	rm -f ../../bin/sparc/J1_ftpget.csh
	rm -f ../../bin/sparc/J1_ftpget_all.csh
	rm -f ../../bin/sparc/NASDAdirmon.csh
	rm -f ../../bin/sparc/WALPSdirmon.csh
	rm -f ../../bin/sparc/mails.csh
	rm -f ../../bin/sparc/kill_hung_proc.csh
	rm -f ../../bin/sparc/mdel_ufdrf_orb.csh
	rm -f ../../bin/sparc/line_at_a_time.sh
