# Makefile for: pregister_lzceos
# Module Author: Tom Logan 
# Module Description: C schell scripts for sub-pixel registration
# Makefile date: 3/00 

include ../../make_support/system_rules

all: pregister_lzceos
	cp pregister_lzceos $(BINDIR)
	cp *.1 ../../man/cat1
	
