# Makefile for: register_lzraw
# Module Author: Tom Logan 
# Module Description: C schell scripts for sub-pixel registration
# Makefile date: 3/00 

include ../../make_support/system_rules

all: register_lzraw
	cp register_lzraw_script $(BINDIR)
	cp *.1 ../../man/cat1
