#!/usr/local/bin/perl

open(IF,$ARGV[0]) || die "error opening $ARGV[0]\n";

while (<IF>)
{
   @words = split;

   $nsla = $words[2] if (/NEAR_START_LAT =/);
   $nslo = $words[2] if (/NEAR_START_LON =/);
   $fsla = $words[2] if (/FAR_START_LAT =/);
   $fslo = $words[2] if (/FAR_START_LON =/);

   $nela = $words[2] if (/NEAR_END_LAT =/);
   $nelo = $words[2] if (/NEAR_END_LON =/);
   $fela = $words[2] if (/FAR_END_LAT =/);
   $felo = $words[2] if (/FAR_END_LON =/);
}
printf ("%.2f %.2f %.2f %.2f %.2f %.2f %.2f %.2f\n",
          $nsla, $nslo, $nela, $nelo,$fsla, $fslo, $fela, $felo);
