.TH las2ppm 1 "December 2003"

.SH NAME:
las2ppm \- Convert LAS byte files to PPM format.

.SH SYNOPSIS:
.B "las2ppm"
[ options ]
.BI "infile outfile"

.SH DESCRIPTION:
.B "Las2ppm"
converts byte data into a PPM file using either built-in palette files or a
user specified palette file. The PPM file format is more common than the LAS
file format used by our tools.  You can view PPM files with the program xv(1),
or convert them to yet more common formats (gif, jpeg) using the NetPBM
package.

.SH COMMAND LINE OPTIONS:
.TP 8
.B "-mask"
Input file is an unwrapping mask file. Escher generates this file after it
finishes unwrapping the phase file. Las2ppm converts the unwrapping bits to
certain colors: white for non-integrated, black for grounding, purple for
branch cut, red and green for singularities, and yellow for integrated. 
.TP 8
.B "-pal palfile"
Generate a PPM file using a user-defined palette. This option is useful for
colorizing elevation files or even amplitude images. A palette file is an ASCII
file that has one entry per line. An entry consists of 4 number separated by
white space (tabs or spaces). The first value is the palette index (range:
0-255) with the indices always increasing. The next three values are the RGB
(red, green, and blue) colors with values ranging from 0 to 255. Pixel values
that are not specified will be generated so that one color will run into the
next.
.TP 8
.B "infile"
Input file, a 1 or 3 banded LAS byte image. 
.TP 8
.B "outfile"
Output PPM image.

.SH EXAMPLES:
.ce 1
example% las2ppm -mask uwp12.phase.mask uwp12mask.ppm 
.PP
Create a PPM file from a mask file.
.PP
.ce 1
example% las2ppm ml12amp.img ml12amp.ppm
.PP
Converts the byte LAS image ml12amp.img into the
PPM image 
.ce 1
example% las2ppm -pal revgrey.pal ml12amp.img ml12amp.ppm
.PP
Colorize a byte version of a multilooked amplitude file using the palette in
revgrey.pal. In this case, revgrey.pal will apply an inverse greyscale to the
image. The palette file in this case would look like the following:
.PP
0    255    255     255
.br
255    0      0       0
.PP
Las2ppm will automatically calculate the inbetween values.

.SH SEE ALSO:
.BR escher (1), 
.BR ml (1)

.SH HARDWARE/SOFTWARE LIMITATIONS:
None known.

.SH BUGS:
None known.

.SH AUTHOR:
\tMike Shindle

.SH CONTACT:
\tapd@asf.alaska.edu
.br
\thttp://www.asf.alaska.edu/apd
