# Makefile for java point target fetcher
include ../mk.common

SOURCE= MainTargetSelection.java SelectArea.java SelectTargets.java

all:
	$(JAVAC) $(SOURCE)
	cp *.class $(JAVA)
	
clean:
	rm -f *.class $(JAVA)/*.class


