Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_raster",
    "asf_meta",
])

bins = localenv.Program("resample", Glob("*.c"))
docs = localenv.File(["resample.1"])

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
localenv.Install(globalenv["inst_dirs"]["docs"], docs)
