Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/asf_meta/",
    "#src/libasf_proj/",
    "#src/libasf_terrcorr",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_terrcorr",
])

bins = localenv.Program("refine_geolocation", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
