C Alaska SAR Processor (ASP) %W% %E% %U%
      SUBROUTINE CNVRT15 (P,JP,NM1,SCLNG)
C/*   SUBROUTINE CNVRT15 (P,JP,NM1,SCLNG) -----------------
C
C     WE ARE GIVEN A REAL ARRAY (P) OF NON-NEGATIVE NUMBERS.
C     THE SUBROUTINE PLACES A FIXED-POINT SCALED VERSION OF 
C     THIS ARRAY IN INTEGER*2 ARRAY JP.
C     THE NUMBER REPRESENTATION IN ARRAY JP IS 2'S-COMPLEMENT
C     WITH THE MOST SIGNIFICANT BIT REPRESENTING -(2**0).
C     THE SCALING IS SUCH THAT THE MAXIMAL VALUE OF P (PMAX)
C     SCALES TO (1-2**(-15))=32767./32768. IN ARRAY JP.
C     OUTPUT VARIABLE SCLNG IS A SCALING PARAMETER SATISFYING
C          PMAX = SCLNG*(32767./32768.)
C          SCLNG IS ALSO AN INPUT TO COMPUTE PMAX.
C     BOTH ARRAYS ARE DIMENSIONED (0:NM1)
C     THIS SUBROUTINE YIELDS LOWER PRECISION THAN CNVRT13
C*/
      INTEGER*2 JP(0:NM1)
      REAL P(0:NM1)
      DATA TWO15/32768./ ! =2**15
      DATA FLIM/32767./  ! =(2**15)-1.
      CALL MAX5 (P,0,NM1,PMAX)
C Ming, 11/18/92
      IF (PMAX .LT. SCLNG) THEN
	PMAX = SCLNG*(32767./32768.)
      ELSE
	WRITE(6,*) 'WARMING, PMAX = ', PMAX, ' TOO MUCH'
      END IF		
      FMLT=FLIM/PMAX
      DO 1 I=0,NM1
    1 JP(I)=NINT(FMLT*P(I))
      SCLNG=TWO15/FMLT
      RETURN
      END
