C Alaska SAR Processor (ASP) %W% %E% %U%
      SUBROUTINE DELPSD1 (AX,R,RHON)
C/* SUBROUTINE DELPSD1 (AX,R,RHON)  ------------------
C
C             ****** DOUBLE-PRECISION SUBROUTINE ******
C     WE ARE GIVEN AN ELLIPSOID SPECIFIED BY ITS THREE SEMI-AXES
C     (AX(I),I=1,3) AND A POINT ON IT SPECIFIED BY THE VECTOR R
C     WITH COMPONENTS GIVEN IN THE AXES FRAME. THE SUBROUTINE
C     COMPUTES RHON, THE UNIT NORMAL VECTOR AT THE POINT R.
C     CONSISTENCY OF R WITH AX NOT CHECKED.
C*/
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION AX(3),R(3),RHON(3)      
      DO 1 I=1,3
    1 RHON(I)=R(I)/AX(I)**2
      CALL DVNR1 (RHON,3,RHON,D)
      RETURN
      END
