C Alaska SAR Processor (ASP) %W% %E% %U%
      SUBROUTINE DEULER2 (DEULANG,F1,F2,F3,G1,G2,G3)
C/*   SUBROUTINE DEULER2 (DEULANG,F1,F2,F3,G1,G2,G3) --------
C
C             ****** DOUBLE PRECISION SUBROUTINE ******
C     WE ARE GIVEN THE 3 EULER ANGLES:
C                     ROLL:  DEULANG(1)
C                     YAW:   DEULANG(2)
C                     PITCH: DEULANG(3)
C     AND THE FRAME FI AS THE INITIAL CONFIGURATION 
C     OF BODY FRAME GI.
C     THE SUBROUTINE COMPUTES THE FINAL CONFIGURATION OF 
C     BODY-FRAME GI IN THE FOLLOWING SEQUENCE:
C            ROTATE INITIAL GI FRAME DEULANG(1) DEG. ABOUT G1
C            ROTATE NEW GI FRAME DEULANG(2) DEG. ABOUT NEW G3
C            ROTATE NEW GI FRAME -DEULANG(3) DEG. ABOUT NEW G2
C*/
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION G1(3),X(3),F1(3)
      DIMENSION G2(3),Y(3),F2(3)
      DIMENSION G3(3),Z(3),F3(3)
      DIMENSION DUM(3,3),DEULANG(3)
      CALL DROTM (1,DEULANG(1),C,S,DUM,F1)
      CALL DMTRV (Y,DUM,F2,3,3)
      CALL DMTRV (Z,DUM,F3,3,3)
      CALL DROTM (1,DEULANG(2),C,S,DUM,Z)
      CALL DMTRV (X,DUM,F1,3,3)
      CALL DMTRV (G2,DUM,Y,3,3)
      CALL DROTM (1,-DEULANG(3),C,S,DUM,G2)
      CALL DMTRV (G1,DUM,X,3,3)
      CALL DMTRV (G3,DUM,Z,3,3)
      RETURN
      END

