C Alaska SAR Processor (ASP) %W% %E% %U%
      SUBROUTINE DFRAME11 (SRADV,SVLV,F1,F2,F3)
C/*   SUBROUTINE DFRAME11 (SRADV,SVLV,F1,F2,F3) -------------
C
C                ****** DOUBLE PRECISION SUBROUTINE ******
C     WE ARE GIVEN THE COMPONENTS OF THE RADIUS VECTOR OF THE 
C     SPACECRAFT (SRADV) AND ITS VELOCITY VECTOR (SVLV). THE 
C     SUBROUTINE COMPUTES THE FRAME FI DEFINED AS FOLLOWS:
C         F3 = NORMALIZED SRADV
C         F2 = NORMALIZED (F3 CROSS SVLV)
C         F1 = F2 CROSS F3 
C     THE SUBROUTINE ALSO DELIVERS OUTPUTS VIA THE LABELLED
C     COMMON/CDFRAME11/ AS FOLLOWS:
C         SRADMAG = MAGNITUDE OF RADIUS VECTOR  
C         SVMAG = MAGNITUDE OF VELOCITY VECTOR
C         SINPSI = SINE OF ANGLE BETWEEN SRADV AND SVLV  
C*/
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SRADV(3),SVLV(3),F1(3),F2(3),F3(3),RHOV(3)
      COMMON/CDFRAME11/SRADMAG,SVMAG,SINPSI
      CALL DVNR1 (SRADV,3,F3,SRADMAG)
      CALL DVNR1 (SVLV,3,RHOV,SVMAG)
      CALL DVECTP (F3,RHOV,F2)
      CALL DVNR1 (F2,3,F2,SINPSI)
      CALL DVECTP (F2,F3,F1)
      RETURN
      END
     
