Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/libasf_remap",
        ])

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_remap",
])

bins = localenv.Program("remap", Glob("*.c"))
docs = localenv.File(["remap.1"])

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
localenv.Install(globalenv["inst_dirs"]["docs"], docs)
