Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_import/",
        "#src/libasf_vector/",
        "#src/libasf_raster/",
        "/usr/include/libshp",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "asf_import",
    "asf_vector",
    "asf_raster",
    "shp",
    "asf_proj",
])

bins = localenv.Program("rgps2vector", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
