Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_import/",
        "#src/libasf_vector/",
        "#src/libasf_raster/",
        "/usr/include/libshp",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs glib-2.0")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "libasf_import",
    "libasf_vector",
    "libasf_raster",
    "shp"
])

bins = localenv.Program("rgps2vector", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
