.TH las2geotiff 1 "17 August 2001"
.SH NAME:  
las2geotiff  - To convert a LAS image to a geoTIFF file.
.SH SYNOPSIS:
.B "las2geotiff "
<inLAS> <outGeoTIFF>
.SH DESCRIPTION:
.B "las2geotiff "
converts a LAS image to a geoTIFF file.  This program works with images that are of data type byte, short, integer, or float for single band images and byte data for 3 band images.
.B "Las2geotiff"
will add all extensions.
.SH OPTIONS: 
none
.SH ERROR MESSAGES:
.B MESSAGE_GIVEN:  REASON:
-----------------------------------------------------------------------
ERROR: 3-banded images must be	 Program checks input 
byte data only.  Exiting...      image data type.     

Input image is too large for	 For multiple band images, 
this program. Image must be      program checks to see if
less than 2gig.  Exiting...      there will be enough 
                                 memory for I/O buffers.

.SH EXAMPLE:   	

.SH SEE ALSO:

.SH HARDWARE/SOFTWARE LIMITATIONS:

.SH BUGS:

.SH AUTHOR:  
Sherman Watts 
.SH CONTACT:  
\tapd@asf.alaska.edu/apd   
