Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include",
        "#src/asf",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_raster",
        ])


localenv.AppendUnique(LIBS = [
        "asf",
        "asf_meta",
        ])

bins = localenv.Program("add_aux_band", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

