Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include/",
        "#src/asf/",
        "#src/libasf_raster/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_vector/",
        "/usr/include/libshp",
        "#src/libasf_import/",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libpng")
localenv.ParseConfig("pkg-config --cflags --libs gsl")
localenv.ParseConfig("pkg-config --cflags --libs libxml-2.0")

localenv.AppendUnique(LIBS = [
    "m",
    "hdf5",
    "hdf5_hl",
    "jpeg",
    "asf",
    "asf_meta",
    "asf_raster",
    "asf_proj",
    "asf_geocode",
    "tiff",
])

bins = localenv.Program("measures_hdf2csv", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

