Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include",
        "#src/asf/",
        "#src/libasf_sar",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_raster",
        "#src/libasf_vector",
        "/usr/include/libshp",
        "#src/libasf_import",
        "#src/libasf_geocode",
        ])

localenv.ParseConfig("pkg-config --cflags --libs gsl")

localenv.AppendUnique(LIBS = [
    "m",
    "asf",
    "asf_meta",
    "asf_proj",
    "asf_raster",
    "asf_sar",
    "asf_geocode",
    "asf_vector",
])

libs = localenv.SharedLibrary("libasf_terrcorr", [
        "seedsquares.c",
        "asf_terrcorr.c",
        "build_dem.c",
        "rtc.c",
        "make_gr_dem.c",
        "uavsar_rtc.c",
        ])

localenv.Install(globalenv["inst_dirs"]["libs"], libs)

