Import("env")
env = env.Clone()

env.AppendUnique(CPPPATH = [
        "#include",
        "#src/asf/",
        "#src/libasf_sar",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_raster",
        "#src/libasf_vector",
        "/usr/include/libshp",
        "#src/libasf_import",
        "#src/libasf_geocode",
        ])

env.ParseConfig("pkg-config --cflags --libs libgeotiff")
env.ParseConfig("pkg-config --cflags --libs glib-2.0")

libs = env.SharedLibrary("libasf_terrcorr", [
        "seedsquares.c",
        "asf_terrcorr.c",
        "build_dem.c",
        "rtc.c",
        "make_gr_dem.c",
        "uavsar_rtc.c",
        ])

products = {"libs": libs}

# run the unit test, and set its dependencies
test_program = None
test_result = env.UnitTest("test.semaphore", test_program)
for product in products.values():
    Depends(test_result, product)

Return("products")
