#!/bin/sh
# make_demargfile: a script to generate an argument file for use with 
#  tandem_ifm_snaphu.
#
# Program History:
#  04/01:  D. Koster  Initial development.


if [ $# != "4" ]
then
	echo "Usage : make_demargfile <multilooked interferogram>.amp"
	echo "		              <meta file>.meta"
	echo "			      <base line>.00"
	echo "			      <Input DEM>.img"
	echo ""
	echo "  This program generates an argument file, expected in "
	echo "   tandem_ifm_snaphu.  This program should be executed "
	echo "   before tandem_ifm_snaphu has been run."
	echo ""
	exit 1
fi

echo "$1 $2 $3 $4" > demargfile

exit 1
