# Makefile for: las_stack
# Makefile author: Orion Lawlor

include ../../make_support/system_rules

all: 
	cp las_stack.sh $(BINDIR)/las_stack
	-chmod 775 $(BINDIR)/las_stack
	cp las_stack.1 ../../man/cat1

