/* Generated by IDL compiler version OSF DCE T1.1.0-03 */
#ifndef downlink_ingest_v1_0_included
#define downlink_ingest_v1_0_included

#ifndef __STDC__
#define volatile
#endif

#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef hst_types_v1_0_included
#include <hst_types.h>
#endif
extern void downlink_ingest_put_wos(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ process_id_t source,
    /* [in] */ idl_long_int send_time,
    /* [in] */ idl_long_int count,
    /* [in] */ process_addr_t data_file_path[],
    /* [out] */ error_status_t *status
#endif
);
extern void downlink_ingest_put_ephemeris(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ process_id_t source,
    /* [in] */ idl_long_int send_time,
    /* [in] */ idl_long_int count,
    /* [in] */ process_addr_t data_file_path[],
    /* [out] */ error_status_t *status
#endif
);
typedef struct downlink_ingest_v1_0_epv_t {
void (*downlink_ingest_put_wos)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ process_id_t source,
    /* [in] */ idl_long_int send_time,
    /* [in] */ idl_long_int count,
    /* [in] */ process_addr_t data_file_path[],
    /* [out] */ error_status_t *status
#endif
);
void (*downlink_ingest_put_ephemeris)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ process_id_t source,
    /* [in] */ idl_long_int send_time,
    /* [in] */ idl_long_int count,
    /* [in] */ process_addr_t data_file_path[],
    /* [out] */ error_status_t *status
#endif
);
} downlink_ingest_v1_0_epv_t;
extern rpc_if_handle_t downlink_ingest_v1_0_c_ifspec;
extern rpc_if_handle_t downlink_ingest_v1_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
