.TH sarin 1 "3 October 1995"
.SH NAME:
sarin \- converts CEOS SAR images to LAS 6.0 format
.SH SYNOPSIS:
.B sarin 
.BI " inSARfile outLASfile"
.SH DESCRIPTION:
Sarin is a image conversion tool used to convert ASF CEOS images into LAS 6.0
images. This is usually the first step in any sort of processing using the
ASF SAR tools.
.PP
The outputs are the LAS image file, 
outLASfile "\|.img,"
a data descriptor record file, 
outLASfile "\|.ddr,"
and a metadata file,
outLASfile "\|.meta,"
for the input SAR image file 
.IR inSARfile.
If the input image is geocoded, the LAS ddr file will contain the geocoding
information found in the SAR metadata files, but
otherwise the DDR will only contain the line, sample, and pixel size of the
image.
.PP
Note that sarin does a straight conversion from CEOS format to
LAS format-- the output pixels are linear SAR amplitude values.
By contrast, calibrate(1) converts images from CEOS format to 
LAS format and changes the pixels to calibrated dB power.

.SH COMMAND LINE OPTIONS:
.TP
.B inSARfile
Any type of CEOS SAR image and the corresponding metadata (.D and .L, 
or .dat and .ldr).
.TP
.B outLASfile
A LAS 6.0 format image with corresponding DDR.
.SH ERROR MESSAGES:
.B MESSAGE_GIVEN:  REASON:
-------------------------------------------------------
.SH EXAMPLES:
.ce 1
example% sarin E1203 e1
.PP
Sarin converts the SAR file E1203.D to the LAS 6.0 file e1.img.
Sarin will also create the DDR file e1.ddr.
.PP
.ne 13
.SH SEE ALSO:
.SH HARDWARE/SOFTWARE LIMITATIONS:
.SH BUGS:
.SH AUTHOR:
\tMike Shindle, Alaska SAR Facility, Fairbanks, AK
\tTom Logan, Alaska SAR Facility, Fairbanks, AK
\tOrion Lawlor, Alaska SAR Facility, Fairbanks, AK
.SH CONTACT:
.br
\tapd@asf.alaska.edu
\thttp://www.asf.alaska.edu/apd

