Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include",
        "#src/asf",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_raster",
        "#src/libasf_sar",
        "#src/libasf_terrcorr",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_terrcorr",
])

bins = localenv.Program("asf_terrcorr", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

