Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/asf_meta/",
    "#src/libasf_proj/",
    "#src/libasf_geocode/",
    "#src/libasf_raster/",
])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_proj",
    "asf_meta",
    "gtk-x11-2.0",
    "gobject-2.0",
    "glade-2.0",
    "glib-2.0",
])

bins = localenv.Program("proj2proj", [
    "proj2proj.c",
    "utility.c",
    "font.c",
    "projfile.c",
    "geocode.c",
    "execute.c",
    "new.c",
])

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

shares = localenv.File([
    "proj2proj.glade",
    "proj2proj_icon.ico",
])

localenv.Install(globalenv["inst_dirs"]["shares"], shares)
