/*==============================================================================
Filename:	sendtoFA.idl
Description:	Interface Definition Language specification (IDL) file
		for the FAxmitserver
Creator:	Norbert Piega (norbert@orca.jpl.nasa.gov)
Notes:		

SCCS Info:
   @(#)sendtoFA.idl	1.4
==============================================================================*/
[

/*Don't compile till you get a new uuid*/

uuid(38af0be0-5b8f-11d1-a593-894f81a9aa77),

version(1.0),
pointer_default(ptr)
] interface sendtoFA
{
const long NAME_LENGTH = 200;

/* a custom handle storing file info 
*/
typedef struct {          
   char host[NAME_LENGTH+1] ;
   char sourcefile[NAME_LENGTH+1] ;
   char file_type[NAME_LENGTH+1] ;
   char dest_id[NAME_LENGTH+1] ;
} Custom_File_Handle ; 

/* a pipe data type
*/
typedef pipe char Pipe_Char_Type;

/* send pipe of chars to a file on the server 
*/
short int send_file_data(
   [in] handle_t bind_handle,              /* binding handle */
   [in] Custom_File_Handle  custom_handle, /* customized binding for server */
   [in] Pipe_Char_Type ASF_pipe_data,      /* input pipe of float data  */
   [in, out] error_status_t *dce_error     /* DCE comm and fault status */
) ;

} /* end of interface definition */

/* End of File */
