Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_geocode/",
        "#src/libasf_raster/",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "asf_raster",
    "asf_geocode",
])

bins = [
    localenv.Program("combine", [
        "combine.c",
    ]),
    localenv.Program("mosaic", [
        "mosaic.c",
    ])
]

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
