Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        "#src/libasf_sar/",
	"#src/libasf_export/",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "libasf_raster",
    "asf_export",
    "m",
])

bins = localenv.Program("color_diff", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
