      SUBROUTINE CNVRT15 (P,JP,NM1,SCLNG)
C/*   SUBROUTINE CNVRT15 (P,JP,NM1,SCLNG) -----------------
C
C     WE ARE GIVEN A REAL ARRAY (P) OF NON-NEGATIVE NUMBERS.
C     THE SUBROUTINE PLACES A FIXED-POINT SCALED VERSION OF 
C     THIS ARRAY IN INTEGER*2 ARRAY JP.
C     THE NUMBER REPRESENTATION IN ARRAY JP IS 2'S-COMPLEMENT
C     WITH THE MOST SIGNIFICANT BIT REPRESENTING -(2**0).
C     THE SCALING IS SUCH THAT THE MAXIMAL VALUE OF P (PMAX)
C     SCALES TO (1-2**(-15))=32767./32768. IN ARRAY JP.
C     OUTPUT VARIABLE SCLNG IS A SCALING PARAMETER SATISFYING
C          PMAX = SCLNG*(32767./32768.)
C     BOTH ARRAYS ARE DIMENSIONED (0:NM1)
C     THIS SUBROUTINE YIELDS LOWER PRECISION THAN CNVRT13
C*/
      INTEGER*2 JP(0:NM1)
      REAL P(0:NM1)
      DATA TWO15/32768./ ! =2**15
      DATA FLIM/32767./  ! =(2**15)-1.
      character*80 sccsid
      data sccsid /'@(#)cnvrt15.f	1.3 96/04/09 22:51:40\0'/
      CALL MAX5 (P,0,NM1,PMAX)
      FMLT=FLIM/PMAX
      DO 1 I=0,NM1
    1 JP(I)=NINT(FMLT*P(I))
      SCLNG=TWO15/FMLT
      RETURN
      END
