Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include/",
        "#src/asf/",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_raster",
        "#src/libasf_vector",
        "/usr/include/libshp",
        "#src/libasf_import",
        "#src/libasf_geocode",
        "#src/plan/",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libpng")

localenv.AppendUnique(LIBS = [
    "m",
    "jpeg",
    "hdf5",
    "asf",
    "asf_meta",
    "asf_raster",
    "asf_proj",
    "asf_import",
    "asf_geocode",
    "asf_vector",
    "asf_plan",
    "tiff",
    "shp",
    "geotiff",
    "xml2",
    "gdk-x11-2.0",
    "gdk_pixbuf-2.0",
    "gobject-2.0",
    "gtk-x11-2.0",
    "glade-2.0",
    "glib-2.0",
])

bins = localenv.Program("asf_view", [
        "asf_view.c",
        "utility.c",
        "font.c",
        "small_image.c",
        "read.c",
        "read_asf.c",
        "read_ceos.c",
        "read_jpeg.c",
        "read_tiff.c",
        "read_png.c",
        "read_pgm.c",
        "read_airsar.c",
        "read_terrasar.c",
        "read_roipac.c",
        "read_ras.c",
        "read_envi.c",
        "read_generic.c",
        "read_uavsar.c",
        "big_image.c",
        "meta.c",
        "stats.c",
        "google.c",
        "new.c",
        "cache.c",
        "subset.c",
        "bands.c",
        "info.c",
        "lut.c",
        "planner.c",
        "pan.c",
        "goto.c",
        "shape.c",
        "csv.c",
        "excel.c",
        "read_seasat_h5.c",
        ])

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

shares = localenv.File([
        "startup.jpg",
        "asf_view.glade",
        "asf_view_icon.ico",
        "#src/asf/pixmaps/google_earth_button.gif",
        "#src/asf/pixmaps/save_as.png",
        "#src/asf/pixmaps/folder_s.png",
        "#src/asf/pixmaps/save_as.png",
        ])

localenv.Install(globalenv["inst_dirs"]["shares"], shares)

