import os.path

Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        "#src/libasf_sar",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs gsl")
localenv.ParseConfig("pkg-config --cflags --libs glib-2.0")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_proj",
    "asf_meta",
])

head_build_dir, tail_build_dir = os.path.split(Dir(".").path)

localenv.AppendUnique(LIBPATH = [
    "#" + os.path.join(head_build_dir, "asf"),
    "#" + os.path.join(head_build_dir, "libasf_proj"),
    "#" + os.path.join(head_build_dir, "asf_meta"),
])


bins = localenv.Program("analyze_yaw", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["bins"], bins)
