#!/bin/sh


if [ $# != "4" ] && [ $# != "6" ]
then

   echo "Usage: tilesnaphu_catDEMSeeds <file to add> <value to add to coumn 2>"
   echo ""
   echo " This program simply takes a demSeeds file, and concatinates it to "
   echo " one called out_dem_seeds.  It adds some offset, passed as parameter 2"
   echo " to coulmn 2. This program should only be called inside of "
   echo " tilesnaphu"

   exit 1
fi

curSeeds=$1
addit=$2

awk '{ print $1, $2+'$addit', $3}' $curSeeds > tmpSeeds

cat tmpSeeds >> out_dem_seeds

