/* File: $RCSfile$
 * 
 * Synopsis: contains Global system variables and etc
 * 
 * Notes: */

/*--------------------------------------------------
 | $Log$
 | Revision 1.1  2004/02/03 03:32:54  pdenny
 | Initial revision
 |
 * Revision 5.0  1995/11/06  13:04:17  ims
 * PROMOTION FROM GUI_4_5_8_951030 FOR GUI_PROMO_5_0_951106
 *
 * Revision 4.5.1.1  1995/07/27  19:09:08  ims
 * COPIED FROM 4.4.1.1 FOR GUI_PROMO_4_5_950726
 *
 * Revision 4.4.1.1  1995/05/24  21:03:34  ims
 * The source code uses FILENAME_MAX to define size for strings that will hold
 * pathnames. Since HP/UX still supports file systems with short filenames
 * (15 characters), FILENAME_MAX is set to 15 for HP/UX.
 *
 * Revision 4.4  1995/02/13  22:21:24  ims
 * PROMOTION FROM GUI_4_4_950106 FOR GUI_PROMO_4_4_950213
 *
 * Revision 4.3.1.4  1994/11/15  14:21:33  ryan
 * SMR 1724
 * Added new system variable CommentsAddress which gets its value
 * from the environment variable IMS_COMMENTS_MAIL_DEST
 *
 * Revision 4.3.1.3  1994/11/03  15:41:44  ryan
 * SMR 1696
 * Fixed code which returned ChuiGuide.  Removed trailing slash.
 *
 * Revision 4.3.1.2  1994/08/26  12:19:09  ims
 * COPIED FROM REVISION 4.0.1.2.
 *
 * Revision 4.0.1.2  1994/07/26  21:51:36  heather
 * added Guide_Home_Addr to IK_SysConfig routine
 *
 * Revision 4.0.1.1  1994/06/14  22:26:23  heather
 * added ChuiGuide environment variable
 *
 * Revision 4.0  1994/06/08  15:23:49  ims
 * PROMOTION FROM REV4
 *
 * Revision 3.1.1.8  1994/06/02  14:24:23  ryan
 * changed logic for getting version information so that it uses REVNAME
 * instead of Client_Version.
 *
 * Revision 3.1.1.7  1994/06/01  23:19:35  heather
 * added CLIENT_VERSION to IK_SysConfig
 *
 * Revision 3.1.1.6  1994/05/23  13:10:22  heather
 * changed the default value returned for Syslog_Level to be LOG_ERR
 *
 * Revision 3.1.1.5  1994/05/20  19:33:43  heather
 * added SYSLOG_LEVEL to IK_SysConfig
 *
 * Revision 3.1.1.4  1994/05/12  15:14:43  kerbel
 * Changed IK_SysConfig() hanling of GaeaTmp.  If the IK_SysConfig()
 * is called with a parameter of "GaeaTmp", it will still attempt
 * to find the GAEATMP_DIR environment variable.  If this variable
 * does not exist it will default to $HOME/GAEATMP_DIR where GAEATMP
 * DIR is a preprocessor #define in IK_Ims.h which is set to gaea_tmp.
 * So the default for "GaeaTmp" is to return $HOME/gaea_tmp.  If this
 * directory does not exist it will be created.  All transient files
 * will now be stored in the GaeaTmp directory during a session.  This
 * directory should be wiped clean at the end of a session.
 *
 * This is part of the overhaul to move all transient files to GaeaTmp
 *
 * Revision 3.1.1.3  1994/05/02  14:43:19  ryan
 * removed unused function IK_SetConfig().  put in reference to
 * default GAEADATA_DIR value.  note that this depends on the use
 * of Autoconf.
 *
 * Revision 3.1.1.2  1994/04/11  20:37:07  kerbel
 * Added code to resolve DISK_ALLOC and GRANULE_LIMIT_CAP enivronment
 * variables to IK_SysConfig().
 *
 * Revision 3.1.1.1  1994/04/08  15:12:04  kerbel
 * This is the place holder revision that starts the branch
 *
 * Revision 3.1  1994/04/05  09:49:52  ims
 * Promotion from MAR28_RELEASE
 *
 * Revision 3.0.1.6  1994/03/23  14:53:29  ryan
 * removed check for ~ims/ims_data.  $GAEADATA_DIR must be set
 * or an error will occur.
 *
 * Revision 3.0.1.5  1994/03/23  13:17:57  ryan
 * added default values and cleaned up code.
 *
 * Revision 3.0.1.4  1994/02/16  14:02:35  ryan
 * added commented-out code to check value of $TMPDIR
 *
 * Revision 3.0.1.3  1994/02/08  19:12:59  ryan
 * cleaned up error-handling code.
 *
 * Revision 3.0.1.2  1994/01/26  20:40:35  ryan
 * cleaned up code to which determines "UserData" parameter.
 *
 * Revision 3.0.1.1  1994/01/26  18:56:43  ryan
 * This is the place holder revision that starts the branch.
 *
 * Revision 3.0  1993/12/29  15:18:49  winter
 * ALPHA-1
 *
 | Revision 1.4  1993/08/02  14:22:16  kerbel
 | This file now #include's <stdio.h> which eliminates the compiler warnings
 | 	generated by pwd.h function prototypes.
 |
 | Revision 1.3  1993/01/15  02:44:18  honce
 | Changed buffer from IK_MAXBUFLEN to FILENAME_MAX, more
 | bits this way.
 |
 | Revision 1.2  1992/12/15  20:29:29  sylvain
 | added GaeaTmp variable name.
 |
 | Revision 1.1  1992/10/01  17:01:10  honce
 | Initial revision
 |
 +------------------------------------------------*/

static const char *rcsid =
"$Id$";

#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <pwd.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>

#include "IK_Ims.h"		/* IMS configuration file */
#include "IK_Errno.h"		/* IMS Error codes */
#include "IK_Syslog.h"		/* IMS message logger */

/* Check if running under HP/UX, it supports a filesystems with short 
 * filenames(15 characters).
 */

#ifdef HPUX 
#undef FILENAME_MAX
#define FILENAME_MAX 255
#endif

extern int getuid(void);

#ifndef FILENAME_MAX
#  define FILENAME_MAX 256
#endif /* FILENAME_MAX */


/*
 * Name:
 *   IK_SysConfig
 * 
 * Description:
 *   retrieve a global IMS system variable
 *   Think of these as intelligent env-variables.  Path variables have a
 *   trailing '/' added.
 *
 * Parameters:
 *   char *variable		 variable name to retrieve 
 *
 * Return Values:
 *   type: char*
 *     Return: upon success, pointer to static value. On failure, NULL.
 * 
 * Warnings:
 *
 * Global Variables Used:
 *
 * Pre- and Post-Conditions
 * 
 * Notes:
 * 
 * 1) GaeaData - where Gaea is keeping it's data files.  Either derived or
 * can be set by the environment variable GAEADATA_DIR.  This directory
 * and the enclosed files must be readable by all Gaea users.
 * 
 * 2) UserData - where to create and store user's data files. Either derived
 * or can be set by the environment variable USRDATA_DIR.  This directory
 * must be readable and writeable by the user.
 * 
 * 3) GaeaTmp - get the place where you want your temp files to go.
 * This is either derived from the environment variable GAEATMP_DIR, or 
 * else it will default to the current directory.  This directory will 
 * hold hold the tmp debugging files that the network manager creates.
 *
 * 4) ?MESSAGE_ID - next Message ID?
 * 
 * 5) DiskAlloc - get the disk quota allocated for the user.
 * This is derived from the environment variable DISK_ALLOC, or
 * else will default to "-1" if DISK_ALLOC doesn't exist.
 *
 * 6) GranLimitCap - get maximum granules allowed for the user.
 * This is derived from the environment variable GRANULE_LIMIT_CAP, or
 * else it will default to "-1" if GRANULE_LIMIT_CAP doesn't exist.
 *
 * Revision History:
 * 
 * 
 */

/* function should return "const char*" */
char *IK_SysConfig(
    /* this parameter should also be "const char*" */
    char *variable		/* variable name to retrieve */
    )
{
    static char
	buffer[FILENAME_MAX];	/* stuff goodies here */
    struct passwd
	*pw_entry;	/* used to get the passwd entries */
    struct stat
	info;		/* stat() information from file system */
    char
	*env_variable;
    char
	*result = buffer;

    if (strcmp("GaeaData", variable) == 0) {
	/* environment variable */
	if (env_variable = getenv("GAEADATA_DIR")) {
	    (void) sprintf(buffer, "%s/", env_variable);
							    
	} else { /* else default value */
	    (void) sprintf(buffer, "%s/", GAEADATA_DIR);
	    
	}
	  
    } else if (strcmp("UserData", variable) == 0) {
	/* Now here's an accident waiting to happen.  Does "USER"
	 * have a "E" or not?
	 * -pmr
	 */
	if ((env_variable = getenv("USRDATA_DIR"))!=(char *)NULL) {
	    strcpy(buffer, env_variable);
	} else {
	    /*
	     * Assuming the presence of a $HOME variable is dangerous
	     * and unnecessary.  A call to getpwuid() is much better.
	     * -pmr
	     */
/* 	    sprintf(buffer, "%s/%s", getenv("HOME"), USRDATA_DIR); */
	    
	    if ((pw_entry = getpwuid(getuid())) != NULL) {
		sprintf(buffer, "%s/%s", pw_entry->pw_dir, USRDATA_DIR); 
	    } else {
		/* We should never get here.  If getuid() or getpwuid()
		 * fails, we have big problems.
		 * -pmr
		 */
		IK_Syslog(LOG_ERR,
		  "unable to determine login directory for user's account");
		result = NULL;
	    }
	}
	
	if (stat(buffer, &info) == -1 && errno == ENOENT) {
	    if (mkdir(buffer, 0700) != 0) {
		IK_vSyslog(LOG_ERR,
			   "Unable to create user data directory %s",
			   buffer);
		result = NULL;
	    }
	}
	(void) strcat(buffer, "/");
	
    } else if (strcmp ("GaeaTmp", variable) == 0) {
	/*
	 * This is stupid.  This should be TmpData, not GaeaTmp.
	 * That would be more consistent.  It would also make more
	 * sense to honor $TMPDIR like many other applications do.
	 * -pmr
	 */
	if ((env_variable = getenv("GAEATMP_DIR")) != (char*)NULL) 
	 {
	    (void) sprintf(buffer, "%s/", env_variable);
	 }
	/*
	  else if ((env_variable = getenv("TMPDIR")) != (char*)NULL)
	  { (void) sprintf(buffer, "%s/", env_variable); } */
	else 
	 {	
	    if ((pw_entry = getpwuid(getuid())) != NULL) 
	     {
		sprintf(buffer, "%s/%s", pw_entry->pw_dir, GAEATMP_DIR); 
	     }
	    else
	     {
		/* We should never get here.  If getuid() or getpwuid()
		 * fails, we have big problems.
		 * -pmr
		 */
		IK_Syslog(LOG_ERR,
		  "unable to determine login directory for user's account");
		result = NULL;
	     }
	 }
	
	if (stat(buffer, &info) == -1 && errno == ENOENT) 
	 {
	    if (mkdir(buffer, 0700) != 0) 
	     {
		IK_vSyslog(LOG_ERR,
			   "Unable to create gaeatmp directory %s",
			   buffer);
		result = NULL;
	     }
	 }
	(void) strcat(buffer, "/");

    } else if (strcmp ("DiskAlloc", variable) == 0) {

	if ((env_variable = getenv("DISK_ALLOC")) != (char *)NULL) {
	    (void) sprintf(buffer, "%s", env_variable);
	} else {
	    (void) strcpy (buffer, "-1");
	}

    } else if (strcmp ("ChuiGuide", variable) == 0) {
	env_variable = getenv("CHUI_GUIDE");
	if (env_variable != (char *)NULL) {
	    strncpy(buffer, env_variable, FILENAME_MAX);
	} else {
	    strcpy (buffer, " ");
	}
	
    } else if (strcmp ("Guide_Home_Addr", variable) == 0) {

	if ((env_variable = getenv("GUIDE_HOME_ADDR")) != (char *)NULL) {
	    (void) sprintf(buffer, "%s", env_variable);
	} else {
	    (void) strcpy (buffer, " ");
	}

    } else if (strcmp ("GranLimitCap", variable) == 0) {

	if ((env_variable = getenv("GRANULE_LIMIT_CAP")) != (char *)NULL) {
	    (void)sprintf(buffer, "%s", env_variable);
	} else {
	    (void) strcpy (buffer, "-1");
	}

    } else if (strcmp ("SyslogLevel", variable) == 0) {

	if ((env_variable = getenv("SYSLOG_LEVEL")) != (char *)NULL) {
	    (void)sprintf(buffer, "%s", env_variable);
	} else {
	    (void) sprintf (buffer, "%d",LOG_ERR);
	}

    } else if (strcmp ("REVNAME", variable) == 0) {
#ifndef REVNAME
#  define REVNAME ""
#endif /* !REVNAME */
	strcpy(buffer,REVNAME);

    } else if (strcmp("CommentsAddress", variable)==0) {
	env_variable = getenv("IMS_COMMENTS_MAIL_DEST");
	if (env_variable != (char *)NULL) {
	    strcpy(buffer, env_variable);
	} else {
	    /* default address temporarily hard-coded.  yuck.
	     * -pmr
	     */
	    strcpy(buffer,"imsv0@eos.nasa.gov");
	}
	
    } else {                    /* who knows... */
	IK_vSyslog(LOG_ERR,
		   "Reference to unrecognized system variable \"%s\"",
		   variable);
	result = NULL;
    }
    
    return result;
}
