#ifndef DTKM_SEGLOAD_H
#define DTKM_SEGLOAD_H

#ifdef COPYRIGHT
Copyright (c)1996, California Institute of Technology.
U.S. Government Sponsorship acknowledged.
#endif
/*==============================================================================
Filename:   dtkm_segload.h
Description:    
Creator:    unknown
Notes:      
==============================================================================*/
#pragma ident   "@(#)dtkm_segload.h	5.1 98/01/08 APS/ASF"
#pragma ident   "@(#) /home/aps/r2.1.2/src/dtkm_segload/SCCS/s.dtkm_segload.h"

#include "dtkm_utilities.h"

/* FOR SYBASE INTERFACES   */
#include "db_sybint.h"      /* for APS sybase interface routines    */
#include "aps_db_table.h"   /* for APS DB tables sybase interface   */
#include "db_dtk.h"
#include "db_seg.h"
#include "db_maskinout.h"
#include "db_station.h"
 
#include "timeconv.h"
  
/* length of segment file records generated by the mapper.  */
#define SEG_FILE_REC_LEN       160

#include "dapps_list.h"     /* for APS linked list macros           */
#include "dapps_defs.h"     /* for NULL, TRUE, FALSE, MIN_REV and others  */
 
int dtkmseg_add_segment(
    DBPROCESS   *APS_dbproc,         /* Sybase db process                     */
    DB_RECORD   **proposed_dtk_seg,  /* data-take segment to be added.        */
    DB_RECORD   **proposed_dtk,    /* completed data-take added, if seg added */
    int         minimum_seconds,   /*   minimum time-duration of data-take.   */
    FILE        *report_fp   ) ;   /* log file report    */

int dtkmseg_update_seg_dtkid(
    DBPROCESS   *APS_dbproc,
    DB_RECORD   **dtk_rec,      /* dtk rec that now supports the segment */
    FILE        *report_fp ) ;

#define DTKM_SEGLOAD_SEG_DOES_NOT_EXIST  0
#define DTKM_SEGLOAD_SEG_EXISTS          1


/*
-- normal return codes ( >= 0 ) from dtkmseg_add_segment()
*/
#define DTKM_SEGLOAD_NOT_ADDED_NO_RECORDER            1
#define DTKM_SEGLOAD_NOT_ADDED_TOO_SHORT              2
#define DTKM_SEGLOAD_SEG_NOT_ADDED_EXISTS_ALREADY     3
#define DTKM_SEGLOAD_ADD_SEGMENT_OK                   4


/*
-- error return codes from src/dtkm_segload
*/
/*
-- MACRO to decode the messages into a string:
*/
extern char *dtkm_segload_error_message[] ;
#define DTKM_SEGLOAD_ERROR_MESSAGE( code ) \
    dtkm_segload_error_message[ -(code) ]

#define DTKM_SEGLOAD_ERROR_BAD_STOPTIME_VALUE                               -1
#define DTKM_SEGLOAD_ERROR_BAD_STRTTIME_VALUE                               -2
#define DTKM_SEGLOAD_ERROR_DARID_ZERO                                       -3
#define DTKM_SEGLOAD_ERROR_DB_QUERY_FAILED                                  -4
#define DTKM_SEGLOAD_ERROR_DTK_UPDATES_LIST_NOT_EMPTY                       -5
#define DTKM_SEGLOAD_ERROR_DTK_UPDATES_LIST_NOT_INITIALIZED                 -6
#define DTKM_SEGLOAD_ERROR_GT_1_SEG_REC_DELETED                             -7
#define DTKM_SEGLOAD_ERROR_INPUT_DTK_LIST_NOT_EMPTY                         -8
#define DTKM_SEGLOAD_ERROR_INPUT_DTK_LIST_NOT_INITIALIZED                   -9
#define DTKM_SEGLOAD_ERROR_IN_CODE_dtkmseg_add_segment                      -10
#define DTKM_SEGLOAD_ERROR_IN_CODE_dtkmseg_seg_exists                       -11
#define DTKM_SEGLOAD_ERROR_MASKINOUT_PROBLEM_PLEASE_RUN_CNOMCOV_FOR_DTK    -12
#define DTKM_SEGLOAD_ERROR_NO_MASKINOUT_RECS_FOUND_IN_REV                  -13
#define DTKM_SEGLOAD_ERROR_NO_STATION_REC_FOR_DTK                          -14
#define DTKM_SEGLOAD_ERROR_NULL_DTK_PROPOSAL                               -15
#define DTKM_SEGLOAD_ERROR_NULL_PROPOSED_DTK_SEG                           -16
#define DTKM_SEGLOAD_ERROR_NULL_RECORD                                     -17
#define DTKM_SEGLOAD_ERROR_OUTPUT_ACCEPTED_DTK_LIST_IS_NOT_EMPTY           -18
#define DTKM_SEGLOAD_ERROR_OUTPUT_ACCEPTED_DTK_LIST_NOT_INITIALIZED        -19
#define DTKM_SEGLOAD_ERROR_OUTPUT_CON_DTK_LIST_IS_NOT_EMPTY                -20
#define DTKM_SEGLOAD_ERROR_OUTPUT_CON_DTK_LIST_NOT_INITIALIZED             -21
#define DTKM_SEGLOAD_ERROR_OUTPUT_ERROR_DTK_LIST_IS_NOT_EMPTY              -22
#define DTKM_SEGLOAD_ERROR_OUTPUT_ERROR_DTK_LIST_NOT_INITIALIZED           -23
#define DTKM_SEGLOAD_ERROR_OUTPUT_REJECTED_DTK_LIST_IS_NOT_EMPTY           -24
#define DTKM_SEGLOAD_ERROR_OUTPUT_REJECTED_DTK_LIST_NOT_INITIALIZED        -25
#define DTKM_SEGLOAD_ERROR_SEGID_ZERO                                      -26
#define DTKM_SEGLOAD_ERROR_SEG_NOT_DELETED                                 -27
#define DTKM_SEGLOAD_ERROR_SEG_NOT_INSERTED                                -28
#define DTKM_SEGLOAD_ERROR_SEG_NOT_UPDATED                                 -29
#define DTKM_SEGLOAD_ERROR_SHOULD_BE_QUE_STATUS                            -30
#define DTKM_SEGLOAD_ERROR_SSCANF                                          -31
#define DTKM_SEGLOAD_ERROR_TOO_MANY_SEGS_UPDATED                           -32
#define DTKM_SEGLOAD_ERROR_ADDING_SEGMENT                                  -33
#define DTKM_SEGLOAD_ERROR_PROCESSING_LIST                                 -34
#define DTKM_SEGLOAD_ERROR_IN_SEG_TIMES                                    -35

#endif  /* DTKM_SEGLOAD_H  */
