Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#include",
    "#src/asf",
    "#src/asf_meta",
    "#src/libasf_proj",
    "#src/libasf_raster",
    "#src/libasf_sar",
])

localenv.ParseConfig("pkg-config --cflags --libs glib-2.0")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_sar",
])

bins = localenv.Program("point_target_analysis", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

