Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include/",
        "#src/asf/",
        "#src/libasf_raster/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_vector/",
        "/usr/include/libshp",
        "#src/libasf_import/",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs glib-2.0")
localenv.ParseConfig("pkg-config --cflags --libs libpng")
localenv.ParseConfig("pkg-config --cflags --libs libtiff-4")
localenv.ParseConfig("pkg-config --cflags --libs gsl")
localenv.ParseConfig("pkg-config --cflags --libs netcdf")

localenv.AppendUnique(LIBS = [
    "m",
    "hdf5",
    "hdf5_hl",
    "jpeg",
    "asf",
    "asf_meta",
    "asf_raster",
    "asf_proj",
    "asf_geocode",
])

libs = localenv.SharedLibrary("libasf_export", [
        "asf_export.c",
        "export_band.c",
        "export_netcdf.c",
        "export_hdf.c",
        "export_polsarpro.c",
        "export_as_envi.c",
        "export_as_esri.c",
        "util.c",
        "keys.c",
        "brs2jpg.c",
        "write_line.c",
        ])

localenv.Install(globalenv["inst_dirs"]["libs"], libs)

