.\" @(#)send_status_to_PPS.3	1.1  09 Dec 1996
.TH send_status_to_PPS 3 "December 1996" "       " "PPS DCE RPC"

.nf
NAME
.fi
send_status_to_PPS
\- Provides a DCE RPC to send a job status to the PPS server.

.nf
SYNOPSIS
#include "messages.h"
#include "check_status.h"
#include "PPSerr.h"

#define c_msg_size	(5000)

short int
	send_status_to_PPS(
	idl_char        buffer[c_msg_size],    /* IN */
	idl_long_int    size,                  /* IN */
	error_status_t  *status);              /* IN/OUT */


DESCRIPTION
The \fsend_status_to_PPS()\fR is a DCE RPC provided by the PPS
to report job status to the PPS server.

ARGUMENTS
.ta +1.0i
	buffer: a string describing the status of a job in ODL.
	See CP-PPS SIS for details.

	size: size of buffer.  Maximum is c_msg_size.

	status: status which is passed in and out of the RPC.
	It contains 0 if no DCE RPC errors occur.


RETURN VALUES
.ta +1.0i
Possible returns values are as follows:
	ER_NO_ERROR
	ER_SHUTDOWN
	ER_INPUT_NULL
	ER_PARSE_CP
	ER_NOT_CP_STATUS_MSG
	ER_NO_LOGIN_AVAIL
	ER_UPDATE_JOBSTATE
	ER_FIND_SCAN_ORDER
	ER_FIND_L1_ORDER
	ER_DEADLOCK


FILES
.ta +1.0i
Include files:
	/ASF/$ASFVER/include/pps/messages.h
	/ASF/$ASFVER/include/pps/check_status.h
	/ASF/$ASFVER/include/pps/PPSerr.h

Libraries:
	/ASF/$ASFVER/lib/$MACH/libpps_client.a
	/ASF/$ASFVER/lib/$MACH/libpps_client.so
