#! /bin/csh -f

#===============================================================================
# Copyright(c) 1996, California Institute of Technology.
#             ALL RIGHTS RESERVED.
# U.S. Government Sponsorship acknowledged.
#===============================================================================
# SCCS:
#       "@(#)README	1.1    11/21/96"
#---------------------------------------------

# for automatic binding
source pps_setup.csh
sparc/pps_server 
