# Makefile for: auto_sar_mosaic
# Author      : Tom Logan, Orion Lawlor

include ../../make_support/system_rules

out_auto_sar_mosaic:
	cp auto_sar_mosaic.sh $(BINDIR)/auto_sar_mosaic
	-chmod 775 $(BINDIR)/auto_sar_mosaic
	cp auto_sar_mosaic.1 ../../man/cat1/auto_sar_mosaic.1

