Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/asf_meta/",
    "#src/libasf_proj/",
    "#src/libasf_sar",
    "#src/libasf_raster",
])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "asf_sar",
    "asf_proj",
])

bins = localenv.Program("shift_geolocation", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
