/*
 * Replacement for StrToODL.  The error message generated by ODLparse(),
 * if any, is now returned to the user instead of being printed to syslog
 * automatically.
 */

#include <string.h>
#include "odl.h"

static char sccsid_stringtoodl_c[] =
    "@(#)StringToODL.c	1.1 96/06/03 12:47:24";

#ifdef  _NO_PROTO
ODL StringToODL (str, len, err)
char* str;
size_t len;
char *err;

#else
ODL StringToODL (char* str, size_t len, char *err)
#endif
{
    char *c;

    ODL odl;
    
    err[0] = 0;
    odl = (ODL) ODLparse(str, len, err);
    /*
     * If a parse error occurred, there's a newline at the end of the
     * message.  (See the source code for toolkit/flex.)  Replace it
     * with a null.
     */
    if ((c = strchr(err, '\n')) != (char *) NULL) *c = 0;
    return odl;
}
