# Makefile for java point target fetcher
include ../mk.common

SOURCE=ASF_Time.java Target.java Area.java MetaReader.java TargetReader.java AreaReader.java Metadata.java Constants.java Spawner.java TargetIngester.java ImageUtils.java

all:
	$(JAVAC) $(SOURCE)
	cp *.class $(JAVA)
	
clean:
	rm -f *.class $(JAVA)/*.class


