.TH convert2jpeg 1 "December 2003"

.SH NAME:
convert2jpeg \- Convert ASF tools byte images to JPEG format.

.SH SYNOPSIS:
.B "convert2jpeg"
[ options ]
.BI "infile outfile"

.SH DESCRIPTION
.B "convert2jpeg"
converts a 1- or 3- banded ASF tools byte image into a JPEG image using either
built-in palette files or a user specified palette file. JPEG images are usually
much smaller, and can be read in many other software packages.

.SH COMMAND LINE OPTIONS:
.TP 8
.B "-mask"
Input file is an unwrapping mask file. Escher generates this file after it
finishes unwrapping the phase file. convert2jpeg converts the unwrapping bits to
certain colors: white for non-integrated, black for grounding, purple for
branch cut, red and green for singularities, and yellow for integrated. 
.TP 8
.B "-pal palfile"
Generate a PPM file using a user-defined palette. This option is useful for
colorizing elevation files or even amplitude images. A palette file is an ASCII
file that has one entry per line. An entry consists of 4 number separated by
white space (tabs or spaces). The first value is the palette index (range:
0-255) with the indices always increasing. The next three values are the RGB
(red, green, and blue) colors with values ranging from 0 to 255. Pixel values
that are not specified will be generated so that one color will run into the
next. 
.TP 8
.B "infile"
Input file, an ASF tools 1- or 3- banded byte image. 
.TP 8
.B "outfile"
Output JPEG/JFIF image.

.SH EXAMPLES:
.ce 1
example% convert2jpeg e1amp.img amp.jpg 
.PP
Create a JPEG image from the given amplitude image.
.PP
.ce 1
example% convert2jpeg -pal revgrey.pal ml12amp.byte ml12amp.jpg
.PP
Colorize a byte version of a multilooked amplitude file using the palette in
revgrey.pal. In this case, revgrey.pal will apply an inverse greyscale to the
image. The palette file in this case would look like the following:
.PP
0    255    255     255
.br
255    0      0       0
.PP
convert2jpeg will automatically calculate the inbetween values.

.SH SEE ALSO:
.BR convert2ppm (1), 
.BR ml (1),
.BR escher (1)

.SH HARDWARE/SOFTWARE LIMITATIONS:
None known.

.SH BUGS:
None known.

.SH AUTHOR:
Orion Lawlor,  3/1999
.br
Patrick Denny, 2/2004
.br
Uses libjpeg routines from IJG (the Independent JPEG Group).

.SH CONTACT:
uso@asf.alaska.edu
.br
http://www.asf.alaska.edu
