Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/libasf_metadata/",
])

localenv.ParseConfig("pkg-config --cflags --libs libglade-2.0")
localenv.ParseConfig("pkg-config --cflags --libs gtk+-2.0")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_metadata",
])

bins = localenv.Program("mdv", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

shares = localenv.File([
    "mdv.glade",
    "mdv.ico",
])

localenv.Install(globalenv["inst_dirs"]["shares"], shares)
