import os.path

Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/libasf_metadata/",
])

localenv.ParseConfig("pkg-config --cflags --libs libglade-2.0")
localenv.ParseConfig("pkg-config --cflags --libs gsl")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_metadata",
    "asf_proj",
    "asf_meta",
])

head_build_dir, tail_build_dir = os.path.split(Dir(".").path)

localenv.AppendUnique(LIBPATH = [
    "#" + os.path.join(head_build_dir, "asf"),
    "#" + os.path.join(head_build_dir, "libasf_metadata"),
    "#" + os.path.join(head_build_dir, "libasf_proj"),
    "#" + os.path.join(head_build_dir, "asf_meta"),
])


bins = localenv.Program("mdv", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["bins"], bins)

shares = localenv.File([
    "mdv.glade",
    "mdv.ico",
])

globalenv.Install(globalenv["inst_dirs"]["shares"], shares)
