Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#src/asf/",
    "#include/",
    "#src/libasf_metadata/",
])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_metadata",
    "gtk-x11-2.0",
    "gobject-2.0",
    "glade-2.0",
    "glib-2.0",
])

bins = localenv.Program("mdv", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

shares = localenv.File([
    "mdv.glade",
    "mdv.ico",
])

localenv.Install(globalenv["inst_dirs"]["shares"], shares)
