#!/bin/csh
#
# @(#)cp-kill	1.3 96/07/29 00:58:54
#
# Kill all SPS applications on the local machine.
#
set pid = `/usr/bin/ps -ef|egrep 'asfn|log_browser|CP_qc|CP_scan_qc'|grep -v grep|grep $USER|awk '{print $2}'`
kill -9 $pid
