
#ifndef _HELP_H
#define _HELP_H

static char sccsid_help_h[] = "@(#)help.h	1.4 96/07/18 19:02:37";

#define HELP_SPS_QUEUE_WIN \
"SPS Processing Queue Window\n\
\n\
  Menus\n\
\n\
    File\n\
      Open:  Restore a previous state of the CP from disk.  In general,\n\
        use the value of CP.LAST_SAVED_STATEFILE from the CP configuration\n\
        file.\n\
      Save As ...:  Save the current state of the CP to an arbitrary file.\n\
      Print:  Print a screen dump of this window on the laser printer.\n\
        (Wait for two beeps before resuming work.)\n\
      Exit:  Exit the CP.\n\
\n\
    Tools\n\
      Generate Production Request (GPR):  Generate jobs for SPS\n\
        subsystems manually.  Should be disabled during operations.\n\
      CP Log Browser\n\
        Display CP messages logged at level \"XXX\" and higher, where \"XXX\"\n\
        can be specified as Info, Debug, or Error.  Choosing Debug is\n\
        equivalent to displaying all messages, while choosing Error selects\n\
        only the error messages.\n\
      SPS Log Browser\n\
        Display messages from all SPS subsystems other than the CP, where\n\
        the messages are logged at level \"XXX\" and higher.  \"XXX\" can be\n\
        specified as Info, Debug, and Error.  Choosing Debug is equivalent\n\
        to displaying all messages, while choosing Error selects only the\n\
        error messages.\n\
\n\
    Subsystems\n\
      Start All:  Start all the subsystems shown in the Subsystems Table.\n\
      Ready All:  Ready (allow jobs to be sent to) all the subsystems shown\n\
        in the Subsystems Table.\n\
      Start:  Start the selected subsystem.\n\
      Ready:  Ready the selected subsystem.\n\
      Reset:  Reset (halt current job on) the selected subsystem.\n\
      Shutdown:  Shut down the selected subsystem.\n\
      Raise Window:  Display jobs assigned to this subsystem.\n\
\n\
    Job Queue\n\
      Remove Hold:  Remove hold on selected job.\n\
      Perform QC:  Perform QC on product created by selected job.\n\
      Cancel Job:  Send a \"CANCEL/FAIL\" status message for this job to\n\
        the PPS and remove this job from the SPS queue.\n\
      Move Job:  Move this job to an alternate subsystem.\n\
      Show Detailed Info:  Display the actual processing request received\n\
        from the PPS for the selected job.\n\
\n\
    External\n\
      Start All:  Start all the external interfaces shown in the External\n\
        Interfaces Table.\n\
      Ready All:  Ready (allow jobs to be sent to) all the external\n\
        interfaces shown in the External Interfaces Table.\n\
      Start:  Start the selected external interface.\n\
      Ready:  Ready the selected external interface.\n\
      Reset:  Reset (halt current job on) the selected external interface.\n\
      Shutdown:  Shut down the selected external interface.\n\
\n\
    Options\n\
      Scan Destination\n\
        Select the subsystem (RDS or ASP) that will be used to scan all\n\
        RADARSAT standard-beam, ERS-1, and ERS-2 data.\n\
      QC Invocation\n\
        Select whether the image QC application is to be bypassed\n\
        (\"Automatic\") or is to be invoked for interactive checking\n\
        (\"Interactive\").\n\
\n\
    Help\n\
      SPS Processing Queue Window:  Display this window.\n\
      Subsystem Windows:  Display information about subsystem and external\n\
        interface windows.\n\
      Job States:  Definitions of CP job states.\n\
      Event Transitions:  List of events that take a CP job from one state\n\
        to another.\n\
      Menu Transitions:  List of menu operations that take a CP job from\n\
        one state to another.\n\
      Product Information:  Display the application version and copyright\n\
        message.\n\
        \n\
  Tables\n\
\n\
    Subsystems:  This table displays the state of each subsystem defined\n\
      in the CP's configuration file.\n\
    Jobs:  This table displays the status of all jobs being processed by\n\
      the SPS.\n\
    External Interfaces:  This table displays the state of each external\n\
      interface defined in the CP's configuration file.\n\
"

#define HELP_SUBSYS_WIN \
"Subsystem and External Interfaces windows\n\
\n\
  Menus\n\
\n\
    File\n\
      Print:  Print a screen dump of this window on the laser printer.\n\
        (Wait for two beeps before resuming work.)\n\
      Exit:  Shut down this subsystem.\n\
\n\
    Task\n\
      Ready:  Ready the selected subsystem.\n\
      Reset:  Reset (halt current job on) the selected subsystem.\n\
      Send Heartbeat:  Query subsystem's current status and display status\n\
        on status bar.\n\
      Log Browser:\n\
        Display messages generated by this subsystem only, where the\n\
        messages are logged at level \"XXX\" and higher.  \"XXX\" can be\n\
        specified as Info, Debug, and Error.  Choosing Debug is equivalent\n\
        to displaying all messages, while choosing Error selects only the\n\
        error messages.\n\
\n\
    Job Queue\n\
      Remove Hold:  Remove hold on selected job.\n\
      Cancel Job:  Send a \"CANCEL/FAIL\" status message for this job to\n\
        the PPS and remove this job from the SPS queue.\n\
      Move Job:  Move this job to an alternate subsystem.\n\
      Perform QC:  Perform QC on product created by selected job.\n\
      Show Detailed Info:  Display the actual processing request received\n\
        from the PPS for the selected job.\n\
\n\
    Help\n\
      SPS Processing Queue Window:  Display information about SPS Processing\n\
        Queue Window.\n\
      Subsystem Windows:  Display this window.\n\
      Job States:  Definitions of CP job states.\n\
      Event Transitions:  List of events that take a CP job from one state\n\
        to another.\n\
      Menu Transitions:  List of menu operations that take a CP job from\n\
        one state to another.\n\
      Product Information:  Display the application version and copyright\n\
        message.\n\
        \n\
  Status Bar:  Display current job and status of this subsystem in response\n\
    to heartbeat message.  (Refer to Task menu.)\n\
\n\
  Job Table:  This table displays the status of all jobs being processed by\n\
    this subsystem.\n\
"

#define HELP_JOB_STATES \
"                      CP states and their definitions\n\
\n\
 TO NEXT STATE\n\tCP is in the process of moving this job to its next state\n\
 WAITING FOR XXX\n\tWaiting to be submitted to subsystem\n\
 FIRST FOR XXX\n\tThis is the job that will next be submitted to the subsystem\n\
 XXX: DATA NOT READY\n\tInput data required for this job is not available. \
This message \n\
\tis displayed from the time that the Tape Mount dialog box \n\
\tis popped up until the operator closes the dialog by \n\
\tselecting \"OK\" or \"Cancel\"\n\
 XXX: DATA READY\n\tInput data required for this job is available\n\
 XXX READY TO SEND\n\tCP is ready to send this job to subsystem\n\
 XXX SENT\n\tJob has been sent to the subsystem\n\
 MASTER XXX ACK\n\tCP's master queue has received the subsystem's\n\
\tacknowledgement of this job\n\
 SUBSYS XXX ACK\n\tCP's subsystem queue has received the subsystem's\n\
\tacknowledgement of this job\n\
 XXX PROCESSING\n\tSubsystem is processing this job\n\
 XXX COMPLETED\n\tSubsystem has completed processing this job\n\
 CYCLE COMPLETED\n\tCP just completed one phase of processing this job and\n\
\tis in the process of moving this job to its next logical state\n\
 SCAN COMPLETED\n\tScan job just completed\n\
 IMAGE AVERAGING\n\tImage averaging is currently being performed\n\
 READY FOR Q/C\n\tJob is ready for QC\n\
 PERFORMING Q/C\n\tQC is currently being performed\n\
 Q/C ACCEPTED   \n\tJob was accepted via the QC program\n\
 Q/C REJECTED   \n\tJob was rejected via the QC program\n\
 XXX Q/C HOLD   \n\tJob was put on hold via the QC program\n\
 CHECKING TAPE \n\
\tTape label mismatch is being performed on this job.\n\
\tThis message is displayed from the time that the Tape\n\
\tLabel Mismatch dialog box is popped up until the operator\n\
\tcloses the dialog by selecting \"OK\" or \"Cancel\"\n\
 XXX ON HOLD/DATA \n\tJob is on hold because operator selected \"Cancel\" to\n\
\tthe tape mount prompt\n\
 XXX ON HOLD/ERROR \n\tJob is on hold because the subsystem returned an error\n\
 XXX ERROR/CLEANUP \n\
\tThis message is displayed from the time that the Cleanup \n\
\tprocessing is to be performed on this job.  The Cleanup \n\
\tConfirmation dialog box is popped up until the operator\n\
\tcloses the dialog by selecting \"OK\".  This job can be \n\
\tre-submitted to the subsystem at a later time. \n\
 XXX TO REPEAT   \n\
\tIf a subsystem is reset or stopped while a job is processing,\n\
\tthat job will be placed into this state.\n\
 XXX ENTRY DELETED \n\tJob is in the process of being deleted\n\
"

#define HELP_EVENT_TRANSITIONS \
"                                     Events\n\
\n\
Job State            Event                                     Next State\n\
-------------------  ---------------------------------------   --------- \n\
\n\
                                                               {WAITING FOR XXX |\n\
 TO NEXT STATE       CP determines next logical step for a job IMAGE AVERAGING |\n\
                                                               READY FOR Q/C |\n\
                                                               CYCLE COMPLETED }\n\
\n\
 WAITING FOR XXX     CP determines job should be sent to       FIRST FOR XXX\n\
                     subsystem\n\
\n\
 FIRST FOR XXX       CP prepares to send message               {XXX: DATA NOT READY |\n\
                                                               XXX READY TO SEND}\n\
\n\
 XXX: DATA NOT READY Tape Mount: OK                            XXX: DATA READY\n\
                     Tape Mount: Cancel                        XXX ON HOLD/DATA\n\
 XXX: DATA READY     CP master queue normal processing         XXX READY TO SEND\n\
 XXX READY TO SEND   Message successfully sent                 XXX SENT\n\
 XXX SENT            Receive SUBSYSTEM_ACK                     \"MASTER XXX ACK\"\n\
 MASTER XXX ACK      CP master queue normal processing         \"SUBSYS XXX ACK\"\n\
 SUBSYS XXX ACK      CP subsystem queue normal processing      \"XXX PROCESSING\"\n\
                                                               {XXX COMPLETED |\n\
 XXX PROCESSING      Receive { SUBSYSTEM_COMPLETED |           XXX ERROR/CLEANUP |\n\
                     SUBSYSTEM_STATUS}\n\
                                                               XXX HOLD/ERROR}\n\
 XXX COMPLETED       CP master queue normal processing         TO NEXT STATE\n\
 CYCLE COMPLETED     CP master queue normal processing         TO NEXT STATE\n\
 SCAN COMPLETED      CP master queue normal processing         CYCLE COMPLETED\n\
 IMAGE AVERAGING     Image averaging program completes         READY FOR Q/C\n\
 READY FOR Q/C       CP determines that QC can be invoked      PERFORMING Q/C\n\
                                                               { Q/C ACCEPTED |\n\
 PERFORMING Q/C      Q/C program completes                     Q/C REJECTED |\n\
                                                               XXX Q/C HOLD}\n\
 Q/C ACCEPTED                          -----                   CYCLE COMPLETED\n\
 Q/C REJECTED                          -----                   CYCLE COMPLETED\n\
 XXX Q/C HOLD                          -----                            -----\n\
\n\
 CHECKING TAPE       Tape Label: OK | Subsystem reset/stopped  WAITING FOR XXX\n\
                     Tape Label: Cancel                        XXX ON HOLD/ERROR\n\
 XXX ON HOLD/DATA                      -----                            -----\n\
 XXX ON HOLD/ERROR                     -----                            -----\n\
\n\
 XXX ERROR/CLEANUP   Cleanup Confirmation w/Resubmit           WAITING FOR XXX\n\
                     Cleanup Confirmation w/Cancel             XXX ENTRY DELETED\n\
                                                               {WAITING FOR XXX |\n\
 XXX TO REPEAT       CP master queue normal processing         SCAN COMPLETED |\n\
                                                               CYCLE COMPLETED}\n\
 XXX ENTRY DELETED                     -----                            -----\n\
"

#define HELP_MENU_TRANSITIONS \
"        Menu Operations that take a CP job from one state to another\n\
\n\
  Job State            Menu Selection              Next State\n\
  ------------------   --------------------------  ---------------------\n\
\n\
  TO NEXT STATE        Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
                                                   {XXX: DATA NOT READY |\n\
  WAITING FOR XXX      Subsystems: Ready           XXX: DATA READY |\n\
                                                   XXX READY TO SEND}\n\
\n\
  FIRST FOR XXX        Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX: DATA NOT READY  Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX: DATA READY      Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX READY TO SEND    Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX SENT             Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  MASTER XXX ACK       Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  SUBSYS XXX ACK       Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX PROCESSING       Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
\n\
                       Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
  XXX COMPLETED        Subsystems: Ready           TO NEXT STATE\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  CYCLE COMPLETED      Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  SCAN COMPLETED       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  IMAGE AVERAGING      Queue: Cancel Job           WAITING FOR XXX\n\
\n\
  READY FOR Q/C        Queue: Perform QC           PERFORMING Q/C\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  PERFORMING Q/C       Queue: Cancel Job           WAITING FOR XXX\n\
\n\
  Q/C ACCEPTED         Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  Q/C REJECTED         Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
                       Queue: Perform QC           PERFORMING Q/C\n\
  XXX Q/C HOLD         Queue: Remove Hold          WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  CHECKING TAPE        Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX ON HOLD/DATA     Queue: Remove Hold          WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX ON HOLD/ERROR    Queue: Remove Hold          WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX ERROR/CLEANUP    Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX TO REPEAT        Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
                       Queue: Cancel Job           XXX ENTRY DELETED\n\
\n\
  XXX ENTRY DELETED    Subsystems: {Stop | Reset}  WAITING FOR XXX\n\
\n\
"

#define HELP_INFO \
"                                   %s\n\
\n\
         Copyright (C) 1996, California Institute of Technology.\n\
U.S. Government Sponsorship under NASA Contract NAS7-1260 is acknowledged.\n\
"

#endif /* ! _HELP_H */
