#!/sbin/csh

# status is string in status
#set MSGTEMP=/user/nancy/src/cp/msgTemplate.odl.status
#set MSGTEMP=/user/src/cp/src/sps/msgTemplate.odl
set MSGTEMP=/LOCAL/PRECM/sps/templates/msgTemplate.odl

set CONFIG=/u/u3/pearl/work/CP/configfile.odl

#set LOG=SYSLOG
set LOG=SYSLOG_AND_TERM

set CP=CP
#set CP=CP_nancy
#set CP=/user/test/cp/CP
#set CP=$ASF/bin/CP.2.9
#set CP=$ASF/bin/CP.2.8.20
#set CP=$ASF/bin/CP
#set CP=/ASF/R1.4.8/bin/CP
#set CP=/ASF/R1BP/bin/CP
#set CP=/user/src/cp/src/CP/CP

set CPOPTS="-asfn CP -asflogloc $LOG -asfcpconfig $CONFIG -config $MSGTEMP"
#set CPOPTS="-asfn CP -asflogloc $LOG -asfcpconfig $CONFIG "
echo "running" $CP $CPOPTS

#echo r $CP $CPOPTS > ~/.dbxinit
#dbx -r $CP $CPOPTS 
#$CP -asfn CP -asflogloc $LOG -asfcpconfig $CONFIG 
$CP $CPOPTS 


exit
