import os.path

Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_import/",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs gsl")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_import",
    "asf_proj",
    "asf_raster",
    "asf_meta",
    "asf_sar",
    "asf_fft",
])

head_build_dir, tail_build_dir = os.path.split(Dir(".").path)

localenv.AppendUnique(LIBPATH = [
    "#" + os.path.join(head_build_dir, "asf"),
    "#" + os.path.join(head_build_dir, "libasf_proj"),
    "#" + os.path.join(head_build_dir, "asf_meta"),
    "#" + os.path.join(head_build_dir, "libasf_sar"),
    "#" + os.path.join(head_build_dir, "asf_fft"),
    "#" + os.path.join(head_build_dir, "libasf_import"),
    "#" + os.path.join(head_build_dir, "libasf_raster"),
])


bins = localenv.Program("write_ppf", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["bins"], bins)
