Import("globalenv")
localenv = globalenv.Clone()

libs = localenv.SharedLibrary("libasf_sgpsdp", [
        "math.c",
        "obs.c",
        "in.c",
        "time.c",
        "solar.c",
        "sgpsdp.c",
        ])

globalenv.Install(globalenv["inst_dirs"]["libs"], libs)

# run the unit test, and set its dependencies
test_result = localenv.UnitTest("test.semaphore", None)
localenv.Depends(test_result, [libs])
