###############################################################################
#
# File:         makefile
#
# Function:     Make file for the IMS migrate source tree.
#
# Author:       S. Hardman
#
# Date:         4/21/97
#
###############################################################################

include ../makedefs

all:	appl

appl:	
	cd clnt_app; $(MAKE) all

clean:
	cd clnt_app; $(MAKE) clean

install:
	cd clnt_app; $(MAKE) install
