.TH gps_vector 1 "13 April 1996"
.SH NAME
gps_vector \- draw ice motion vectors or grids
.SH SYNOPSIS
.B "gps_vector"
[-a] [-g] [-b \fInband\fP] [-w \fIlinewidth\fP] [-m \fImag\fP] [-v \fIvector\fP]
[-r \fIresample\fP] 
.BI " ice-motion-file outfile"
.PP
.B gps_vector
-s [-a] [-g] [-b \fInband\fP] [-w \fIlinewidth\fP] [-m \fImag\fP] 
[-v \fIvector\fP] [-r \fIresample\fP] 
.BI " ice-motion-file outfile lat lon"
.SH DESCRIPTION
.B gps_vector  
draws ice motion vectors from GPS ice motion data created at the Alaska SAR
Facility. It creates a LAS 6.0 byte image called 
.IR outfile "\|.img"
It also creates 
.IR outfile "\|.ddr"
which is the corresponding valid DDR. The image data will have the same 
geographic coordinates as the destination image used by the GPS processor. 
(This image is referred to as image B in the metadata.) 
.PP
If 
.B gps_vector
is run in grid mode, the grid is drawn from vector head to vector head. In
this mode, the 
.I mag
.RB ( \-m )
option is not used. Vectors cannot be lengthend.
.SH COMMAND LINE OPTIONS
.TP 8
.B "-a"
Subtract the average displacement from each vector.
.TP 8
.B "-g"
Draw ice motion as a grid instead of individual vectors. The -m is invalid when
drawing grids.
.TP 8
.B "-n \fInband\fP"
Write the output image with a number of bands equalling \fInband\fP. The
default value is 1.
.TP 8
.B "-w \fIlinewidth\fP"
Draw grid lines and vectors with a line width of \fIlinewidth\fP. The default
value is 3.
.TP 8
.B "-m \fImag\fP"
Artificially increase vector length by a factor of
.IR mag "\|."
This option should only be used for images that will later be mosaicked
together. Otherwise, screen overcrowding will become readily apparent.
.TP 8
.B "-v \fIvector\fP"
Decreases the amount of vectors drawn by 1 / \fIvector \fP^2. In the vector
grid created by the GPS processor, only every \fIvector\fP is drawn.
.TP 8
.B "-r \fIresample\fP"
Output image is resampled to a resolution specified by \fIresample\fP. Images 
are normally written at a 100 meters per pixel. \fIResample\fP should be 
specified in meters.
.TP 8
.B "-s"
Using the -s option causes 
.B gps_vector
to search for the vector located in the data file with the base closest to
the input \fIlat\fP, \fIlon\fP values. Upon finding this vector, 
.B gps_vector
will subtract it from each of the other vectors.
.SH EXAMPLES
.ce 1
example% gps_vector inSAR out1
.PP
In its basic format, gps_vector will read the ice motion data from the data
file
.IR inSAR "\|.dat"
and the metadata leader file
.IR inSAR "\|.ldr."
The resulting image, written with a resolution of 100 meters per pixel, will
have every vector drawn at the correct size. The output files will be called
.IR out1 "\|.img"
for the image data and 
.IR out1 "\|.ddr"
for the DDR data.
.PP
.ce 1
example% gps_vector -m 5 -v 2 -r 300 inSAR out1
.PP
Works the same as above except that vectors will be 5 times their actual
length, only every other vector will be drawn, and the output image will have
a resolution of 300 meters per pixel.
.PP
.ce 1
example% gps_vector -g -v 2 -r 500 inSAR out1
.PP
In this case, draw a grid instead of vectors using only every other vector
point. Output resolution will be at 500 meters per pixel.
.PP
.ce 1
example gps_vector -s -n 3 inSAR out1 70.54 -145.89
.PP
.B Gps_vector
will find the vector nearest to 70.54 degrees North and 145.89 degrees West
and subtract it from each of the other vectors. The information will be
output to the file \fIout1\fP which is a three banded image.
.ne 13
.SH SEE ALSO
.BR resample (1)
.SH AUTHOR
\tMike Shindle, Alaska SAR Facility, Fairbanks, AK
.SH CONTACT
\tMike Shindle (mshindle@iias.images.alaska.edu)
.br
\tRick Guritz (rguritz@iias.images.alaska.edu)

