.TH calibrate 1 "January 2004" 

.SH NAME:
calibrate \- performs radiometric calibration 

.SH SYNOPSIS: 
.B "calibrate"  
.BI " inSARfile outSARfile [-m][-g]"

.SH DESCRIPTION: 
Performs radiometric calibration of all types of ASF SAR imagery. Calibrate
processes inSARfile.D(dat) using data from the inSARfile.L(ldr) file (assumed
to be in the same directory as the inSARfile.D) to produce outSARfile.img. 
Note that the extensions are assumed, and, as such, should not be included
on the command line. 
.PP
Calibrate utilizes the equations and conditions described below:
.PP
.ce 1 
Excerpt on Radiometric Calibration from SAR User Guide. ==>
.PP 
.RS 4
The Radiometric Data Record contains the information necessary to convert
image data values to backscatter (sigma0). There are three coefficients
immediately following the word "INTENSITY" near the beginning of the
record. These coefficients (a1,a2, and a3) are the noise scaling, the
linear conversion, and the offset, respectively. (The offset, a3, is
always 0.) The conversion of data number, d, to backscatter in units of dB
is
.PP
.ce 1
sigma0 = 10log[a2(d^2 - a1n(r)) + a3]
.PP
where n(r) is the noise versus range function immediately following the
coefficients in the record. The noise in the image varies with range due
to internal radiometric compensation for antenna pattern, range to target,
and incidence angle. Accurate conversion to backscatter requires
subtraction of the noise as indicated by the equation. There are 256 noise
values as a function of range. The first value corresponds to pixel one
(in each range line), the second value to pixel 33,...,and the 256th to
pixel 8161. The function varies slowly enough that nearest neighbor
application is well within the accuracy of the function, but linear
interpolation between values is functionally more accurate. The square
root of the a1n(r) term is the d (amplitude) value of the noise. 
.PP
In general the edge pixels should be avoided for accurate quanitative
work, since the antenna pattern mismatch is always greatest at the edges. 
.PP
Once sigma0 is calculated, calibrate maps sigma0 (from -25.5 dB
to 0 dB attenuation) to a byte (from 0 to 255 brightness) via
the scaling:
.PP
.ce1
outByte = (25.5+sigma0)*10
.PP
so to go from a byte value in the image to sigma0, use:
.PP
.ce1
sigma0 = outByte/10-25.5
.PP                
NOTE: For Radarsat imagery acquired during the Commissioning Phase (the first
7000 orbits, where the satellite was being tested and the satellite gain was
being modified), the a1 and a2 coefficients are not applicable as they
currently exist. These first 7000 orbits may contain inconsistent satellite
gains as the engineers determined the best imaging parameters for the
satellite. It would be best if these orbits were avoided entirely. However, if
this data is needed please apply the following equations to obtain more
radiometrically accurate data. For a1, the noise scaling coefficient:
.PP
.in +3		   
new a1 = (existing a1 in the metadata) * \\
.in +10
10[(processor gain)/10]
.PP
The processor gain is always a multiple of 3 dB and typically is 0. To
determine a new a2, or linear coefficient:
.PP
.in +3		   
new a2 = (existing a2 in the metadata) * \\
.in +10		   
10^(-5)*10[-(processor gain)/10]
.PP
These replacements for the orbits during the Commissioning Phase of Radarsat
should produce results similar to the calibrated images that were acquired
after the Commissioning Phase completed. The requirements for calibration are
+/- 1dB of relative error and +/- 2 dB in absolute error, radiometrically.
.RE 
.PP
===============================================> End Excerpt

.SH OPTIONS:
.TP 8
.B "-m"
allows modification of radiometric calibration coefficients that have been
read from the .ldr file. 
.TP 8
.B "-g"
allows creation of gamma0 output images based on the incidence angle at each pixel in the image.  Gamma0 is defined as
.PP
.ce1
gamma0 = sigma0 - 10log(cos(incidence))

.SH EXAMPLES:
.ce 1
calibrate E106987290G1S033 e1_06987_290
.PP
This would process the file E106987290G1S033.D, using information found in the
file E106987290G1S033.L. The output file created would be named 
e1_06987_290.img.

.SH SEE ALSO:
metadata(1), sarin(1)

.SH HARDWARE/SOFTWARE LIMITATIONS:
None known.

.SH BUGS:
None known.

.SH AUTHORS:         
Tom Logan, Mike Shindle

.SH CONTACT:
E-Mail:  uso@asf.alaska.edu
.br
Website: http://www.asf.alaska.edu
