C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.

********************************************************************
*  Name:	SWINQ
*  Module Type: SUBROUTINE	Language: FORTRAN
*  $Logfile:   ACS003:[BLD.MPS.LIB.SRC]SWINQ.FOV  $
*  Purpose:	DETERMINE IF THE GREAT CIRCLE SEGMENT SL1, SR1 IS INSIDE
*		THE QUADRILATERAL.  IF IT IS ON A BORDER, THE INSIDE OF 
*		THE QUADRILATERAL MUST BE ON THE FAR SIDE OF SL1 SR1 
*		TO RETURN A POSITIVE RESULT.  
*  Subroutines called:
*  VECTOR LIBRARY: UCROSS, VUNIT, VUNITN
*  Input Parameters:
*  POINTS ON A UNIT SPHERE, (X,Y,Z)
*  Name         Type    Definition
*  SL1		REAL*8	LEFT POINT OF START OF SWATH
*  SR1		REAL*8	RIGHT POINT OF START OF SWATH
*  SL2		REAL*8	LEFT POINT OF END OF SWATH
*  SR3		REAL*8	RIGHT POINT OF END OF SWATH
*  Q1		REAL*8	1ST POINT OF QUADRILATERAL
*  Q2		REAL*8	2ND POINT OF QUADRILATERAL
*  Q3		REAL*8	3RD POINT OF QUADRILATERAL
*  Q4		REAL*8	4TH POINT OF QUADRILATERAL
*			NOTE:  THE POINTS ARE ENTERED IN A CLOCKWISE 
*			DIRECTION.  
*  Output Parameters:
*  Name         Type    Definition
*  IFLAG	INTEGER	RESULT FLAG:
*			= 1	THE SWATH LINE IS INSIDE THE QUADRILATERAL.
*				IF THE SWATH LINE IS ON AN EDGE, THEN THE 
*				QUADRILATERAL INSIDE LIES ON THE FAR SIDE
*				OF THE SWATH LINE.  
*			= -1	ALL OTHER CASES.
*  Variables:
*  Locals :
*  Externals :
*  Modification History:                                            
*  Date			Revision	Author
*  $Date$ $Revision$ $Author$
*                                                                   
*********************************************************************/
      SUBROUTINE SWINQ (SL1,SR1,SL2,SR2,Q1,Q2,Q3,Q4,IFLAG)
      character*100 SccsFileID
     -/'@(#)swinq.for	5.1 98/01/08 APS/ASF\0'/

      IMPLICIT NONE
      REAL*8 SL1(3),SR1(3),SL2(3),SR2(3),Q1(3),Q2(3),Q3(3),Q4(3)
      REAL*8 F
      INTEGER IFLAG
C---	START WITH IDENTIFYING ALL POSSIBLE SL1 AND SR1 EQUALITIES:  
      CALL GCLOSE(IFLAG,SL1,Q1)
      IF(IFLAG.NE.1) GO TO 1000
C---	SWANGL RECEIVES THE IDENTICAL POINTS AND THEIR ADJACENT POINTS
C---	IN LEFT TO RIGHT ORDER AS YOU ARE LOOKING FROM OUTSIDE THE BOXES.
      CALL SWANGL(SL2,SL1,SR1,Q2,Q4,IFLAG)
      GO TO 9999
 1000 CONTINUE
      CALL GCLOSE(IFLAG,SL1,Q2)
      IF(IFLAG.NE.1) GO TO 2000
      CALL SWANGL(SL2,SL1,SR1,Q3,Q1,IFLAG)
      GO TO 9999
 2000 CONTINUE
      CALL GCLOSE(IFLAG,SL1,Q3)
      IF(IFLAG.NE.1) GO TO 3000
      CALL SWANGL(SL2,SL1,SR1,Q4,Q2,IFLAG)
      GO TO 9999
 3000 CONTINUE
      CALL GCLOSE(IFLAG,SL1,Q4)
      IF(IFLAG.NE.1) GO TO 4000
      CALL SWANGL(SL2,SL1,SR1,Q1,Q3,IFLAG)
      GO TO 9999
 4000 CONTINUE
      CALL GCLOSE(IFLAG,SR1,Q1)
      IF(IFLAG.NE.1) GO TO 5000
      CALL SWANGL(SL1,SR1,SR2,Q2,Q4,IFLAG)
      GO TO 9999
 5000 CONTINUE
      CALL GCLOSE(IFLAG,SR1,Q2)
      IF(IFLAG.NE.1) GO TO 6000
      CALL SWANGL(SL1,SR1,SR2,Q3,Q1,IFLAG)
      GO TO 9999
 6000 CONTINUE
      CALL GCLOSE(IFLAG,SR1,Q3)
      IF(IFLAG.NE.1) GO TO 7000
      CALL SWANGL(SL1,SR1,SR2,Q4,Q2,IFLAG)
      GO TO 9999
 7000 CONTINUE
      CALL GCLOSE(IFLAG,SR1,Q4)
      IF(IFLAG.NE.1) GO TO 8000
      CALL SWANGL(SL1,SR1,SR2,Q1,Q3,IFLAG)
      GO TO 9999
 8000 CONTINUE
      IFLAG = 1
      CALL GCRINQ(F,SL1,SR1,Q1,Q2,Q3,Q4)
      IF(F .GE. 0.0D00) GO TO 9999
C---	NO ENTRY DETECTED YET.  GCRINQ SERVES OUR PURPOSE EXCEPT IF SL1 SR1
C---	LIES IN THE PLANE OF ONE OF THE SIDES OF THE QUADRILATERAL.
C---	GCRINQ TREATS CASE WHERE THE SWATH LIES IN THE PLANE OF A SIDE
C---	AS A NON-INTERSECTION.  WE NEED TO IDENTIFY
C---	THAT CASE AS A START COVERAGE, SINCE THE OTHER POINTS IN THE QUAD
C---	MAY BE SUCH THAT NONE OF THE OTHER START SWATH ROUNTINES ARE EVEN
C---	CALLED.  
C
C---	TRY TO SEE IF THE SWATH LIES ON A BOUNDARY PLANE AND GIVES A START
C---	COVERAGE.  
      CALL SWSIDE(SL1,SR1,Q2,Q1,IFLAG)
      IF(IFLAG.EQ.1) GO TO 9999
      CALL SWSIDE(SL1,SR1,Q3,Q2,IFLAG)
      IF(IFLAG.EQ.1) GO TO 9999
      CALL SWSIDE(SL1,SR1,Q4,Q3,IFLAG)
      IF(IFLAG.EQ.1) GO TO 9999
      CALL SWSIDE(SL1,SR1,Q1,Q4,IFLAG)
 9999 CONTINUE
      RETURN
      END
