.TH convert2geotiff 1 "February 2004"

.SH NAME:
convert2geotiff  \- Converts an ASF tools image to a geoTIFF file.

.SH SYNOPSIS:
.B "convert2geotiff "
<inASF> <outGeoTIFF>

.SH DESCRIPTION:
.B "convert2geotiff "
converts an ASF tools image to a geoTIFF file. This program works with images 
that are of data type byte, integer16, integer32, or real32 for single band 
images.
.B "Convert2geotiff"
will add all extensions.

.SH OPTIONS:
None.

.SH EXAMPLE:

.SH SEE ALSO:

.SH HARDWARE/SOFTWARE LIMITATIONS:
None known.

.SH BUGS:
None known.

.SH AUTHOR:
Sherman Watts, 08/2001
.br
Patrick Denny, 02/2004

.SH CONTACT:
uso@asf.alaska.edu
.br
http://www.asf.alaska.edu

