Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_tiff/",
        "#src/libasf_export/",
        "#src/libasf_raster/",
        "#src/libasf_import/",
        "#src/libasf_sar/",
        "#src/libasf_terrcorr/",
        "#src/libasf_geocode/",
        "#src/libasf_ardop/",
        "#src/libasf_vector/",
        "/usr/include/libshp",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs glib-2.0")
localenv.ParseConfig("pkg-config --cflags --libs netcdf")

libs = localenv.SharedLibrary("libasf_convert", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["libs"], libs)

