Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_tiff/",
        "#src/libasf_export/",
        "#src/libasf_raster/",
        "#src/libasf_import/",
        "#src/libasf_sar/",
        "#src/libasf_terrcorr/",
        "#src/libasf_geocode/",
        "#src/libasf_ardop/",
        "#src/libasf_vector/",
        "/usr/include/libshp",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "asf_raster",
    "asf_sar",
    "asf_vector",
    "asf_export",
    "asf_geocode",
    "asf_terrcorr",
    "asf_ardop",
    "asf_import",
    "z",
])

libs = localenv.SharedLibrary("libasf_convert", Glob("*.c"))

shares = localenv.File([
    "mapready_settings.cfg",
])

localenv.Install(globalenv["inst_dirs"]["libs"], libs)
localenv.Install(globalenv["inst_dirs"]["shares"], shares)

