Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#/include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        ])

localenv.ParseConfig("pkg-config --cflags --libs gsl")
localenv.ParseConfig("pkg-config --cflags --libs libpng")

localenv.AppendUnique(LIBS = [
    "m",
    "jpeg",
    "asf",
    "asf_meta",
    "asf_proj",
    "asf_fft",
    "tiff",
    "geotiff",
    "glib-2.0",
])

libs = localenv.SharedLibrary("libasf_raster", [
        "interpolate.c",
        "kernel.c",
        "float_image.c",
        "banded_float_image.c",
        "uint8_image.c",
        "scaling.c",
        "bands.c",
        "stats.c",
        "trim.c",
        "fftMatch.c",
        "shaded_relief.c",
        "resample.c",
        "smooth.c",
        "tile.c",
        "look_up_table.c",
        "raster_calc.c",
        "diffimage.c",
        "spline_eval.c",
        "fit_warp.c",
        ])

shares = [
     localenv.Dir([
        "#src/libasf_raster/look_up_tables",
     ]),
]

localenv.Install(globalenv["inst_dirs"]["libs"], libs)
localenv.Install(globalenv["inst_dirs"]["shares"], shares)

