#!/bin/ksh
rm -f mail_message
echo "Subject: ASF Doppler Trending Report" > mail_message
echo "Automated RAMP Status Report:" >> mail_message
echo `date` >> mail_message
echo >> mail_message
echo "Doppler Trending Report:  The following frames have bad dopplers" >> mail_message
echo "  and should be reprocessed:" >> mail_message
echo "Format: ramp/orderNumber/fileName   Beam   DopplerOffset" >> mail_message

for rev in `ls */*/*.L | awk -F/ '{print substr($3,3,5)}' | sort -u`
do
	echo "Calling DopPlot on Revolution #" $rev
	dopPlot $rev
done

cat mail_message | mail "mmason@gi.alaska.edu kfn@iceberg.mps.ohio-state.edu olawlor@images.alaska.edu"
rm mail_message
