Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf",
        "#include",
        "#src/asf_meta",
        "#src/libasf_proj",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "asf_proj",
])

bins = localenv.Program("measures2csv", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
