#include "asf.h"
#include "ceos.h"

void prn_mpdr(char *file, struct VMPDREC *vmpdr)
{
  FILE *fp;

  fp = FOPEN(file, "w");
  fprintf(fp, "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
  fprintf(fp, "\"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n<head>\n");
  fprintf(fp, "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\n");
  fprintf(fp, "<title>Map Projection Data record</title>\n</head>\n<body>\n");
  fprintf(fp, "<h2>Map Projection Data record</h2>\n");
  fprintf(fp, "Map Projection Descriptor: </strong>%s<br>\n",vmpdr->mpdesc);
  fprintf(fp, "<strong>Number of Pixels: </strong>%i<br>\n",vmpdr->npixels);
  fprintf(fp, "<strong>Number of Lines : </strong>%i<br>\n",vmpdr->nlines);
  fprintf(fp, "<strong>Nominal inter-pixel distance in output (m): </strong>%f<br>\n",vmpdr->nomipd);
  fprintf(fp, "<strong>Nominal inter-line distance in output (m): </strong>%f<br>\n",vmpdr->nomild);
  fprintf(fp, "<strong>Orientation at center: </strong>%f<br>\n",vmpdr->orient);
  fprintf(fp, "<strong>Actual platform orbital inclination (deg): </strong>%f<br>\n",vmpdr->orbitincl);
  fprintf(fp, "<strong>Actual ascending node (deg): </strong>%f<br>\n",vmpdr->ascnode);
  fprintf(fp, "<strong>Platform distance from center to geocenter: </strong>%f<br>\n",vmpdr->distplat);
  fprintf(fp, "<strong>Altitude of platform rel. to ellipsoid (m): </strong>%f<br>\n",vmpdr->altplat);
  fprintf(fp, "<strong>Actual groundspeed at nadir: </strong>%f<br>\n",vmpdr->velnadir);
  fprintf(fp, "<strong>Platform heading (deg): </strong>%f<br>\n",vmpdr->plathead);
  fprintf(fp, "<strong>Name of reference ellipsoid: </strong>%s<br>\n",vmpdr->refelip);
  fprintf(fp, "<strong>Semimajor axis of ellipsoid (m): </strong>%f<br>\n",vmpdr->remajor);
  fprintf(fp, "<strong>Semiminor axis of ellipsoid (m): </strong>%f<br>\n",vmpdr->reminor);
  fprintf(fp, "<strong>Datum shift reference dx (m): </strong>%f<br>\n",vmpdr->datshiftx);
  fprintf(fp, "<strong>Datum shift perpendicular dy (m): </strong>%f<br>\n",vmpdr->datshifty);
  fprintf(fp, "<strong>Datum shift direction of rotation dz (m): </strong>%f<br>\n",vmpdr->datshiftz);
  fprintf(fp, "<strong>Datum shift 1, rotation angle: </strong>%f<br>\n",vmpdr->datshift1); 
  fprintf(fp, "<strong>Datum shift 2, rotation angle: </strong>%f<br>\n",vmpdr->datshift2); 
  fprintf(fp, "<strong>Datum shift 3, rotation angle: </strong>%f<br>\n",vmpdr->datshift3); 
  fprintf(fp, "<strong>Scale factor of reference ellipsoid: </strong>%f<br>\n",vmpdr->rescale);
  fprintf(fp, "<strong>Alphanumeric description of map projection: </strong>%s<br>\n",vmpdr->mpdesig);
  fprintf(fp, "<strong>UTM descriptor: </strong>%s<br>\n",vmpdr->utmdesc);
  fprintf(fp, "<strong>Signature of UTM zone: </strong>%s<br>\n",vmpdr->utmzone);
  fprintf(fp, "<strong>Map origin - false east: </strong>%f<br>\n",vmpdr->utmeast);
  fprintf(fp, "<strong>Map origin - false north: </strong>%f<br>\n",vmpdr->utmnorth);
  fprintf(fp, "<strong>Center of projection longitude: </strong>%f<br>\n",vmpdr->utmlong);
  fprintf(fp, "<strong>Center of projection latitude: </strong>%f<br>\n",vmpdr->utmlat);
  fprintf(fp, "<strong>1st standard parallel (deg): </strong>%f<br>\n",vmpdr->utmpara1);
  fprintf(fp, "<strong>2nd standard parallel (deg): </strong>%f<br>\n",vmpdr->utmpara2);
  fprintf(fp, "<strong>UTM scale factor: </strong>%f<br>\n",vmpdr->utmscale);
  fprintf(fp, "<strong>UPS descriptor: </strong>%s<br>\n",vmpdr->upsdesc);
  fprintf(fp, "<strong>Center of projection longitude: </strong>%f<br>\n",vmpdr->upslong);
  fprintf(fp, "<strong>Center of projection latitude: </strong>%f<br>\n",vmpdr->upslat);
  fprintf(fp, "<strong>UPS scale factor: </strong>%f<br>\n",vmpdr->upsscale);
  fprintf(fp, "<strong>NPS projection description: </strong>%s<br>\n",vmpdr->nspdesc);
  fprintf(fp, "<strong>Map origin - fasle east: </strong>%f<br>\n",vmpdr->nspeast);
  fprintf(fp, "<strong>Map origin - false north: </strong>%f<br>\n",vmpdr->nspnorth);
  fprintf(fp, "<strong>Center of projection longitude: </strong>%f<br>\n",vmpdr->nsplong);
  fprintf(fp, "<strong>Center of projection latitude: </strong>%f<br>\n",vmpdr->nsplat);
  fprintf(fp, "<strong>Standard parallels: </strong>%f<br>\n",vmpdr->nsppara1);
  fprintf(fp, "<strong>Standard parallels: </strong>%f<br>\n",vmpdr->nsppara2);
  fprintf(fp, "<strong>Standard parallels: </strong>%f<br>\n",vmpdr->nsppara3);
  fprintf(fp, "<strong>Standard parallels: </strong>%f<br>\n",vmpdr->nsppara4);
  fprintf(fp, "<strong>Central meridian: </strong>%f<br>\n",vmpdr->nspcm1);
  fprintf(fp, "<strong>Central meridian: </strong>%f<br>\n",vmpdr->nspcm2);
  fprintf(fp, "<strong>Central meridian: </strong>%f<br>\n",vmpdr->nspcm3);
  fprintf(fp, "<strong>Top left corner north (m): </strong>%f<br>\n",vmpdr->tlcnorth);
  fprintf(fp, "<strong>Top left corner east (m): </strong>%f<br>\n",vmpdr->tlceast);
  fprintf(fp, "<strong>Top right corner north (m): </strong>%f<br>\n",vmpdr->trcnorth);
  fprintf(fp, "<strong>Top right corner east (m): </strong>%f<br>\n",vmpdr->trceast);
  fprintf(fp, "<strong>Bottom right corner north (m): </strong>%f<br>\n",vmpdr->brcnorth);
  fprintf(fp, "<strong>Bottom right corner east (m): </strong>%f<br>\n",vmpdr->brceast);
  fprintf(fp, "<strong>Bottom left corner north (m): </strong>%f<br>\n",vmpdr->blcnorth);
  fprintf(fp, "<strong>Bottom left corner east (m): </strong>%f<br>\n",vmpdr->blceast);
  fprintf(fp, "<strong>Top left corner latitude (deg): </strong>%f<br>\n",vmpdr->tlclat);
  fprintf(fp, "<strong>Top left corner longitude (deg): </strong>%f<br>\n",vmpdr->tlclong);
  fprintf(fp, "<strong>Top right corner latitude (deg): </strong>%f<br>\n",vmpdr->trclat);
  fprintf(fp, "<strong>Top right corner longitude (deg): </strong>%f<br>\n",vmpdr->trclong);
  fprintf(fp, "<strong>Bottom right corner latitude (deg): </strong>%f<br>\n",vmpdr->brclat);
  fprintf(fp, "<strong>Bottom right corner longitude (deg): </strong>%f<br>\n",vmpdr->brclong);
  fprintf(fp, "<strong>Bottom left corner latitude (deg): </strong>%f<br>\n",vmpdr->blclat);
  fprintf(fp, "<strong>Bottom left corner longitude (deg): </strong>%f<br>\n",vmpdr->blclong);
  fprintf(fp, "<strong>Top left corner terrain height (m): </strong>%f<br>\n",vmpdr->tlcheight);
  fprintf(fp, "<strong>Top right corner terrain height (m): </strong>%f<br>\n",vmpdr->trcheight);
  fprintf(fp, "<strong>Bottom right corner terrain height (m): </strong>%f<br>\n",vmpdr->brcheight);
  fprintf(fp, "<strong>Bottom left corner terrain height (m): </strong>%f<br>\n",vmpdr->blcheight);
  fprintf(fp, "<strong>Coefficients to convert a line & pixel to a projection reference<strong><br>\n");
  fprintf(fp, "<strong>a11: </strong>%f<br>\n",vmpdr->a11);
  fprintf(fp, "<strong>a12: </strong>%f<br>\n",vmpdr->a12);
  fprintf(fp, "<strong>a13: </strong>%f<br>\n",vmpdr->a13);
  fprintf(fp, "<strong>a14: </strong>%f<br>\n",vmpdr->a14);
  fprintf(fp, "<strong>a21: </strong>%f<br>\n",vmpdr->a21);
  fprintf(fp, "<strong>a22: </strong>%f<br>\n",vmpdr->a22);
  fprintf(fp, "<strong>a23: </strong>%f<br>\n",vmpdr->a23);
  fprintf(fp, "<strong>a24: </strong>%f<br>\n",vmpdr->a24);
  fprintf(fp, "<strong>Coefficients to convert a projection reference to a line & pixel</strong><br>\n");
  fprintf(fp, "<strong>b11: </strong>%f<br>\n",vmpdr->b11);
  fprintf(fp, "<strong>b12: </strong>%f<br>\n",vmpdr->b12);
  fprintf(fp, "<strong>b13: </strong>%f<br>\n",vmpdr->b13);
  fprintf(fp, "<strong>b14: </strong>%f<br>\n",vmpdr->b14);
  fprintf(fp, "<strong>b21: </strong>%f<br>\n",vmpdr->b21);
  fprintf(fp, "<strong>b22: </strong>%f<br>\n",vmpdr->b22);
  fprintf(fp, "<strong>b23: </strong>%f<br>\n",vmpdr->b23);
  fprintf(fp, "<strong>b24: </strong>%f<br>\n",vmpdr->b24);
  fprintf(fp, "</body>\n</html>\n");
  FCLOSE(fp);

  return;
}
