# Makefile for MeasureGeoLocationErrors.class

include ../Make_rules

all: MeasureGeoLocationErrors clean

MeasureGeoLocationErrors:
	$(JAVAC) MeasureGeoLocationErrors.java
	cp *.class $(JAVADIR) 

clean:
	rm -f *.class
