#include "ceos.h"

/*********************************************
*   SAR Leader File: File Descriptor Record  *
*********************************************/
struct FDR default_lfdr = {
/*   char   ascii_flag[2] */    "A",
/*          spare1[2] */        "",
/*          format_doc[12] */   "CEOS-SAR-CCT",
/*          format_rev[2] */    "B",
/*          design_rev[2] */    "B",
/*          software_id[12] */  "SAROUT",
/*   int    file_num */         1,
/*   char   product_id[16] */   "fill me",
/*          rec_seq_flag[4] */  "FSEQ",
/*   int    seq_loc */          1,
/*          seq_len */          4,
/*   char   rec_code[4] */      "FTYP",
/*   int    code_loc */         5,
/*          code_len */         4,
/*   char   rec_len[4] */       "FLGT",
/*   int    rlen_loc */         9,
/*          rlen_len */         4,
/*   char   spare2[4] */        "",
/*          spare3[64] */       "",
/*   int    n_dssr */           1,
/*        l_dssr */             4096,
/*        n_mpdr */             0,
/*        l_mpdr */             0,
/*        n_ppdr */             1,
/*        l_ppdr */             1024,
/*        n_atdr */             1,
/*        l_atdr */             1024,
/*        n_raddr */            1,
/*        l_raddr */            4232,
/*        n_rcr */              0,
/*        l_rcr */              0,
/*        n_qsr */              1,
/*        l_qsr */              1620,
/*        n_dhr */              2,
/*        l_dhr */              4628,
/*        n_rsr */              1,
/*        l_rsr */              5120,
/*        n_demdr */            0,
/*        l_demdr */            0,
/*        n_rpr */              0,
/*        l_rpr */              0,
/*        n_adr */              0,
/*        l_adr */              0,
/*        n_dpr */              0,
/*        l_dpr */              0,
/*        n_calr */             0,
/*        l_calr */             0,
/*        n_gcp */              0,
/*        l_gcp */              0,
/*        spare4[10] */         {0,0,0,0,0,0,0,0,0,0},
/*        n_facdr */            1,
/*        l_facdr */            1717,
/*    char  spare5[288] */      ""
};

