import os.path

Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")

head_build_dir, tail_build_dir = os.path.split(Dir(".").path)

libs = localenv.SharedLibrary("asf_metadata", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["libs"], libs)
