Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        ])


localenv.AppendUnique(LIBS = [
    "m",
    "proj",
    "asf",
    "tiff",
    "geotiff",
])

libs = localenv.SharedLibrary("libasf_proj", [
        "project.c",
        "spheroid_axes_lengths.c",
        "datum_spheroid.c",
        "geotiff_support.c",
        ])

localenv.Install(globalenv["inst_dirs"]["libs"], libs)

