# Makefile for: auto_swath_mosaic
# Author      : Tom Logan, Orion Lawlor

include ../../make_support/system_rules

create_auto_swath_mosaic:
	cp auto_swath_mosaic.sh $(BINDIR)/auto_swath_mosaic
	-chmod 775 $(BINDIR)/auto_swath_mosaic
	cp auto_swath_mosaic.man ../../man/cat1/auto_swath_mosaic.1
	
