Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_import/",
        "#src/libasf_raster/",
        "/usr/include/libshp",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libxml-2.0")

localenv.AppendUnique(LIBS = [
    "m",
    "hdf5",
    "asf",
    "asf_meta",
    "asf_proj",
    "asf_import",
    "shp",
    "geotiff",
])

libs = localenv.SharedLibrary("libasf_vector", [
        "convert2vector.c",
        "vector.c",
        "utils.c",
        "kml.c",
        "shape.c",
        "config.c",
        ])

shares = [
    localenv.File([
        "convert2vector.config",
    ]),
    localenv.Dir([
        "#src/libasf_vector/data_dictionaries",
    ]),
]

localenv.Install(globalenv["inst_dirs"]["libs"], libs)
localenv.Install(globalenv["inst_dirs"]["shares"], shares)

