Import("env")
env = env.Clone()

env.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "/usr/include/libshp/",
        "#src/libasf_import/",
        "#src/libasf_raster/",
        ])

env.ParseConfig("pkg-config --cflags --libs libgeotiff")
env.ParseConfig("pkg-config --cflags --libs glib-2.0")

libs = env.SharedLibrary("libasf_vector", [
        "convert2vector.c",
        "convert2vector.t.c",
        "utils.c",
        "header.c",
        "geotiff.c",
        "polygon.c",
        "point.c",
        "auig.c",
        "rgps.c",
        "multimatch.c",
        "meta.c",
        "terrasar.c",
        "kml.c",
        "shape.c",
        "generic_csv.c",
        "ursa.c",
        "datapool.c",
        "high_altitude_photography.c",
        "smap.c",
        "custom.c",
        "config.c",
        ])

products = {"libs": libs}

# run the unit test, and set its dependencies
test_program = None
test_result = env.UnitTest("test.semaphore", test_program)
for product in products.values():
    Depends(test_result, product)

Return("products")
