Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_import/",
        "#src/libasf_raster/",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs glib-2.0")
localenv.ParseConfig("pkg-config --cflags --libs shapelib")

localenv.AppendUnique(LIBS = [
    "m",
    "hdf5",
    "asf",
    "asf_meta",
    "asf_proj",
    "asf_import",
])

libs = localenv.SharedLibrary("libasf_vector", [
        "convert2vector.c",
        "convert2vector.t.c",
        "utils.c",
        "header.c",
        "geotiff.c",
        "polygon.c",
        "point.c",
        "auig.c",
        "rgps.c",
        "multimatch.c",
        "meta.c",
        "terrasar.c",
        "kml.c",
        "shape.c",
        "generic_csv.c",
        "ursa.c",
        "datapool.c",
        "high_altitude_photography.c",
        "smap.c",
        "custom.c",
        "config.c",
        ])

localenv.Install(globalenv["inst_dirs"]["libs"], libs)

