Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
    "#include",
    "#src/asf",
    "#src/asf_meta",
    "#src/libasf_proj",
    "#src/libasf_raster",
    "#src/libasf_sar",
])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_sar",
])

bins = localenv.Program("asf_calpol", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

