Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include/",
        "#src/asf/",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_export",
        "#src/libasf_raster",
        "#src/libasf_sar",
        ])


localenv.AppendUnique(LIBS = [
    "m",
    "asf",
    "asf_meta",
    "asf_sar",
    "asf_export",
    "asf_fft",
])

libs = localenv.SharedLibrary("libasf_ardop", [
        "ardop_libs.c",
        "cfft1d_risc.c",
        "estdop.c",
        "fft_dop.c",
        "read_signal.c",
        "ardop.c",
        "calc_deltas.c",
        "get_params.c",
        #"specan.c",
        #"specan_ml.c",
        #"specan_patch.c",
        #"specan_file.c",
        #"quicklook.c",
        "patch.c",
        "ardop_setup.c",
        "rciq.c",
        "rmpatch.c",
        "acpatch.c",
        "calibration.c",
        ])

localenv.Install(globalenv["inst_dirs"]["libs"], libs)

