Import("env")
env = env.Clone()

env.AppendUnique(CPPPATH = [
        "#include/",
        "#src/asf/",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_export",
        "#src/libasf_raster",
        "#src/libasf_sar",
        ])

env.ParseConfig("pkg-config --cflags --libs libgeotiff")
env.ParseConfig("pkg-config --cflags --libs glib-2.0")

libs = env.SharedLibrary("libasf_ardop", [
        "ardop_libs.c",
        "cfft1d_risc.c",
        "estdop.c",
        "fft_dop.c",
        "read_signal.c",
        "ardop.c",
        "calc_deltas.c",
        "get_params.c",
        #"specan.c",
        #"specan_ml.c",
        #"specan_patch.c",
        #"specan_file.c",
        #"quicklook.c",
        "patch.c",
        "ardop_setup.c",
        "rciq.c",
        "rmpatch.c",
        "acpatch.c",
        "calibration.c",
        ])

products = {"libs": libs}

# run the unit test, and set its dependencies
test_program = None
test_result = env.UnitTest("test.semaphore", test_program)
for product in products.values():
    Depends(test_result, product)

Return("products")
