Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include",
        "#src/asf",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_convert",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_convert",
])

bins = localenv.Program("asf_mapready", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["bins"], bins)

