Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_raster",
])

bins = [
    localenv.Program("fftMatch", ["fftMatch.c"]),
    localenv.Program("fftMatchGrid", ["fftMatchGrid.c"]),
    localenv.Program("fftMatchProj", ["fftMatchProj.c"]),
    localenv.Program("fftMatchOptical", ["fftMatchOptical.c"]),
]

docs = localenv.File("fftMatch.man")

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
localenv.Install(globalenv["inst_dirs"]["docs"], docs)
