.TH refine_base 1 "April 2004"

.SH NAME:
refine_base \- perform baseline refinement.

.SH SYNOPSIS:
.B "refine_base" 
.BI "[-keep <iter>] [-log <file>] [-quiet]"
.br
.BI "          <phase> <tie_points> <meta> <old_base> <new_base>"

.SH DESCRIPTION:
Refine_base corrects a given baseline for an interferogram using tie points.
Tie points are listed in an ASCII file with each tie point on a separate line.
The format for a line in a tie point file is x or sample, y or line, and height
in meters. These coordinates are before multilooking, and in the original
interferogram's image space (before any windowing or multilooking). X and Y are
pixel locations in the file and each  parameter is separated by white space.
.PP
Using the tie point file, refine_base retrieves the unwrapped phase value at
each pixel. If the phase value happens to equal the seed value used to unwrap
the interferogram, that point is discarded. Refine_base will assume a default
seed value of 0.0. You should change this to the value used in our progam
escher(1).
.PP
After retrieving the phase values, refine_base calculates the new baseline
values and places the resulting information in the new_base file.
.PP
The baseline file contains 4 values describing the baseline separation of the
satellite passes. The 4 values are, in order, perpendicular baseline (Bn), 
delta perpendicular baseline (dBn), parallel baseline (Bp), and delta parallel 
baseline (dBp). The delta values represent the change of the baseline over the
entire image. All these values are in meters.

.SH COMMAND LINE OPTIONS:
.TP 8
.B "-keep <iter>"
Keep intermediate files generated by refine_base. By default, refine_base will
delete all the intermediate files it creates. However, if you wish to save
these files, specify the \-keep option and a value for <iter>. The intermediate
files will be appended with this value.
.TP 8
.B "-log <file>"
Writes output to a log <file> (and the terminal).
.TP 8
.B "-quiet"
Surpress output to only the essential.
.TP 8
.B "phase"
Input unwrapped phase file. This file is usually generated by the escher(1)
program.
.TP 8
.B "tie_points"
An ASCII tie point file containg x,y image locations and height values in
meters. 
.TP 8
.B "meta"
Name of .meta file for the source image.
.TP 8
.B old_base
Baseline file. ASCII file of 4 baseline parameters entered on the same line.
This file contains the baseline parameters that need to be refined.
.TP 8
.B new_base
Baseline file generated by refine_base. This file contains the new baseline
parameters. The interferogram should be deramped again using these values.

.SH EXAMPLES:
.ce 1
example% refine_base uwp12 ifm12.tp image1 base.0 base.1
.PP
Refine_base will refine the baseline in the file base.0 and place the new
baseline in the file base.1. It will use the tie points in the file ifm12.tp
and obtain the phases from the file uwp12.phase. Image1 is the base name of the
metadata file image1.meta associated with the source image. 

.SH SEE ALSO:
coregister_coarse(1), deramp(1), escher(1)

.SH HARDWARE/SOFTWARE LIMITATIONS:
None known.

.SH BUGS:
None known.

.SH AUTHOR:
Mike Shindle,   6/97
.br
Patrick Denny,  4/04

.SH CONTACT:
uso@asf.alaska.edu
.br
http://www.asf.alaska.edu


