     -/'@(#)constants.inc	5.1 98/01/08 APS/ASF\0'/

*.
*   Constants.inc
*
*	08/02/89 15:45
*..
*   Constants added to remove hardcoded constant values from
*   subroutine calls..aap..11/4/93
*..
	integer i2two/2/
	integer i2five/5/
*
	integer ineg3/-3/
	integer ineg2/-2/
	integer ineg1/-1/
	integer	izero/0/
	integer ione/1/
	integer itwo/2/
	integer ithree/3/
	integer ifive/5/
	integer i15/15/
	integer i20/20/
	integer i91/91/
	integer i125/125/
	integer i255/255/
	integer i780/780/
	integer i1023/1023/
	integer i1279/1279/
	integer i1995/1995/
	integer i10000/10000/
*
	real*4	rtwo/2.0/
*
	double precision dneg90/-90.0d+0/
	double precision dnegone/-1.0d+0/
	double precision dzero/0.0d+0/
	double precision d_one/1.0d+0/
	double precision d90/90.0d+0/
	double precision d365/365.0d+0/
	double precision d888/888.8d+0/
	double precision d999/999.9d+0/
*..
	double precision pi,twopi,halfpi,rads
	data pi,twopi /3.14159265358979323d0,6.283185307179586d0/
	data halfpi,rads /1.570796326794897d0,0.017453292519943296d0/
