#!/bin/sh

asf_import $1 test
resample test test_60m 60
gr2sr test_60m test_sr2_60m

remap -scale 0.99667767023656 0.63338076567152 test_sr2_60m test_sr2_60m_scaled

create_dem_grid delta_fixed.img test_sr2_60m_scaled.img dem_grid

fit_poly dem_grid 5 dem_poly

remap -translate 0 0 -poly dem_poly -width 1500 -height 1200 -bilinear -float delta_fixed.img dem_big.img

reskew_dem test_sr2_60m_scaled.meta dem_big.img dem_slant.img dem_sim_amp.img
exit 1

trim -h 1081 -w 1022 dem_sim_amp.img dem_trimsim_amp.img 0 0

fftMatch -m dem.corr test_sr2_60m_scaled.img dem_trimsim_amp.img

trim -h 1081 -w 1022 dem_sim_amp.img dem_trimsim_amp.img 117 0

fftMatch -m dem.corr2 test_sr2_60m_scaled.img dem_trimsim_amp.img

trim -h 1081 -w 1022 dem_slant.img dem_trimmed_slant.img 117 0

deskew_dem -i test_sr2_60m_scaled.img 0 dem_trimmed_slant.img test_sr2_tc.img
