#include "asf.h"
#include "ceos.h"

void prn_facdr(char *file, struct VFDRECV *ofdr, int era)
{
  FILE *fp;

  fp = FOPEN(file, "w");
  fprintf(fp, "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
  fprintf(fp, "\"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n<head>\n");
  fprintf(fp, "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\n");
  fprintf(fp, "<title>Facility Related Data record</title>\n</head>\n<body>\n");
  fprintf(fp, "<h2>Facility Related Data record</h2>\n");
  fprintf(fp, "<strong>Data take id: </strong>%s<br>\n", ofdr->dataid);
  fprintf(fp, "<strong>SPS image identifier: </strong>%s<br>\n", ofdr->imageid);
  fprintf(fp, "<strong>UTC year of image correlation: </strong>%s<br>\n", ofdr->coryear);
  fprintf(fp, "<strong>UTC time of image correlation: </strong>%s<br>\n", ofdr->cortime);
  fprintf(fp, "<strong>Name of site covered: </strong>%s<br>\n", ofdr->sitename);
  fprintf(fp, "<strong>UTC year at the image center: </strong>%s<br>\n", ofdr->imgyear);
  fprintf(fp, "<strong>UTC time at the image center: </strong>%s<br>\n", ofdr->imgtime);
  fprintf(fp, "<strong>Latitude of the image center: </strong>%.7f<br>\n", ofdr->imgclat);
  fprintf(fp, "<strong>Longitude of the image center: </strong>%.7f<br>\n", ofdr->imgclon);
  fprintf(fp, "<strong>Lat at start of image frame in near swath: </strong>%.7f<br>\n", ofdr->nearslat);
  fprintf(fp, "<strong>Long at start of image frame in near swath: </strong>%.7f<br>\n", ofdr->nearslon);
  fprintf(fp, "<strong>Lat at end of image frame in near swath: </strong>%.7f<br>\n", ofdr->nearelat);
  fprintf(fp, "<strong>Long at end of image frame in near swath: </strong>%.7f<br>\n", ofdr->nearelon);
  fprintf(fp, "<strong>Lat at start of image frame in far swath: </strong>%.7f<br>\n", ofdr->farslat);
  fprintf(fp, "<strong>Long at start of image frame in far swath: </strong>%.7f<br>\n", ofdr->farslon);
  fprintf(fp, "<strong>Lat at end of image frame in far swath: </strong>%.7f<br>\n", ofdr->farelat);
  fprintf(fp, "<strong>Long at end of image frame in far swath: </strong>%.7f<br>\n", ofdr->farelon);
  fprintf(fp, "<strong>Actual swath width (km) in azimuth direction: </strong>%.7f<br>\n", ofdr->swazim);
  fprintf(fp, "<strong>Actual swath width (km) in range direction: </strong>%.7f<br>\n", ofdr->swrange);
  fprintf(fp, "<strong>Actual (no filler) number of pixels per line: </strong>%i<br>\n", ofdr->npixels);
  fprintf(fp, "<strong>Actual (no filler) number of image lines: </strong>%i<br>\n", ofdr->nlines);
  fprintf(fp, "<strong>Total (with filler) number of pixels per line: </strong>%i<br>\n", ofdr->apixels);
  fprintf(fp, "<strong>Total (with filler) number of image lines: </strong>%i<br>\n", ofdr->alines);
  fprintf(fp, "<strong>Identification label of the media written to: </strong>%s<br>\n", ofdr->mediaid);
  fprintf(fp, "<strong>Location on the DCRSI where data begins: </strong>%s<br>\n", ofdr->sblock);
  fprintf(fp, "<strong>Location on the DCRSI where data ends: </strong>%s<br>\n", ofdr->eblock);
  fprintf(fp, "<strong>Name of platform for the transmitting sensor: </strong>%s<br>\n", ofdr->platform);
  fprintf(fp, "<strong>Sensor and mode of operation: </strong>%s<br>\n", ofdr->sensmode);
  fprintf(fp, "<strong>Pulse repitition frequency (prf): </strong>%.7f<br>\n", ofdr->prfreq);
  fprintf(fp, "<strong>SAR antenna look angle: </strong>%.7f<br>\n", ofdr->antlook);
  fprintf(fp, "<strong>Data rate: </strong>%.7f<br>\n", ofdr->datarate);
  fprintf(fp, "<strong>Data window position: </strong>%.7f<br>\n", ofdr->datawin);
  fprintf(fp, "<strong>Range gate delay: </strong>%.7f<br>\n", ofdr->rangegd);
  fprintf(fp, "<strong>Track angle to True North: </strong>%.7f<br>\n", ofdr->trackang);
  fprintf(fp, "<strong>Flag indicating whether the pass is asc/desc: </strong>%s<br>\n", ofdr->ascdesc);
  fprintf(fp, "<strong>Altitude of the spacecraft at image center: </strong>%.7f<br>\n", ofdr->scalt);
  fprintf(fp, "<strong>Spacecraft X-position at the image center: </strong>%.15f<br>\n", ofdr->scxpos);
  fprintf(fp, "<strong>Spacecraft Y-position at the image center: </strong>%.15f<br>\n", ofdr->scypos);
  fprintf(fp, "<strong>Spacecraft Z-position at the image center: </strong>%.15f<br>\n", ofdr->sczpos);
  fprintf(fp, "<strong>Spacecraft X-velocity at the image center: </strong>%.15f<br>\n", ofdr->scxvel);
  fprintf(fp, "<strong>Spacecraft Y-velocity at the image center: </strong>%.15f<br>\n", ofdr->scyvel);
  fprintf(fp, "<strong>Spacecraft Z-velocity at the image center: </strong>%.15f<br>\n", ofdr->sczvel);
  fprintf(fp, "<strong>Spacecraft roll at the image center: </strong>%.14g<br>\n", ofdr->scroll);
  fprintf(fp, "<strong>Spacecraft yaw at the image center: </strong>%.14g<br>\n", ofdr->scyaw);
  fprintf(fp, "<strong>Spacecraft pitch at the image center: </strong>%.14g<br>\n", ofdr->scpitch);
  fprintf(fp, "<strong>Quality flag for the spacecraft roll: </strong>%i<br>\n", ofdr->qroll);
  fprintf(fp, "<strong>Quality flag for the spacecraft yaw: </strong>%i<br>\n", ofdr->qyaw);
  fprintf(fp, "<strong>Quality flag for the spacecraft pitch: </strong>%i<br>\n", ofdr->qpitch);
  fprintf(fp, "<strong>Spacecraft roll rate at the image center: </strong>%.14g<br>\n", ofdr->rroll);
  fprintf(fp, "<strong>Spacecraft yaw rate at the image center: </strong>%.14g<br>\n", ofdr->ryaw);
  fprintf(fp, "<strong>Spacecraft pitch rate at the image center: </strong>%.14g<br>\n", ofdr->rpitch);
  fprintf(fp, "<strong>Quality flag for the spacecraft roll rate: </strong>%i<br>\n", ofdr->rqroll);
  fprintf(fp, "<strong>Quality flag for the spacecraft yaw rate: </strong>%i<br>\n", ofdr->rqyaw);
  fprintf(fp, "<strong>Quality flag for the spacecraft pitch rate: </strong>%i<br>\n", ofdr->rqpitch);
  fprintf(fp, "<strong>Radius of the earth at nadir: </strong>%.7f<br>\n", ofdr->eradnadr);
  fprintf(fp, "<strong>Radius of the earth at image center: </strong>%.7f<br>\n", ofdr->eradcntr);
  fprintf(fp, "<strong>Incidence angle at the center of the image: </strong>%.7f<br>\n", ofdr->incedang);
  fprintf(fp, "<strong>Version of the ASP: </strong>%s<br>\n", ofdr->procvers);
  fprintf(fp, "<strong>Image processing type identifier: </strong>%s<br>\n", ofdr->imgproct);
  fprintf(fp, "<strong>Type of Ephemeris used identifier: </strong>%s<br>\n", ofdr->ephemert);
  fprintf(fp, "<strong>Effective number of looks in azimuth: </strong>%.7f<br>\n", ofdr->nlooksaz);
  fprintf(fp, "<strong>Effective number of looks in range: </strong>%.7f<br>\n", ofdr->nlooksra);
  fprintf(fp, "<strong>Weighting pedestal height in azimuth: </strong>%.7f<br>\n", ofdr->weightaz);
  fprintf(fp, "<strong>Weighting pedestal height in range: </strong>%.7f<br>\n", ofdr->weightra);
  fprintf(fp, "<strong>Look energy normalization flag: </strong>%s<br>\n", ofdr->normener);
  fprintf(fp, "<strong>Processing induced distortions in azimuth: </strong>%.7f<br>\n", ofdr->indistaz);
  fprintf(fp, "<strong>Processing induced distortions in range: </strong>%.7f<br>\n", ofdr->indistra);
  fprintf(fp, "<strong>Receiver gain: </strong>%.7f<br>\n", ofdr->recgain);
  fprintf(fp, "<strong>Swath velocity: </strong>%.7f<br>\n", ofdr->swathvel);
  fprintf(fp, "<strong>Squint angle: </strong>%.7f<br>\n", ofdr->squintan);
  fprintf(fp, "<strong>Ave. terrain height above Geoid at center: </strong>%.7f<br>\n", ofdr->avgterht);
  fprintf(fp, "<strong>Processor gain: </strong>%s<br>\n", ofdr->procgain);
  fprintf(fp, "<strong>Flag indicating if Doppler Skew was removed: </strong>%s<br>\n", ofdr->deskewf);
  fprintf(fp, "<strong>Ground range / slant range flag: </strong>%s<br>\n", ofdr->grndslnt);
  fprintf(fp, "<strong>Slant range to the first image pixel: </strong>%.7f<br>\n", ofdr->sltrngfp);
  fprintf(fp, "<strong>Slant range to the last image pixel: </strong>%.7f<br>\n", ofdr->sltrnglp);
  fprintf(fp, "<strong>Start sample of signal data range line: </strong>%i<br>\n", ofdr->strtsamp);
  fprintf(fp, "<strong>Flag indicating whether clutterlock was used: </strong>%s<br>\n", ofdr->clttrlkf);
  fprintf(fp, "<strong>Doppler frequency at the near range: </strong>%.7f<br>\n", ofdr->dpplrfrq);
  fprintf(fp, "<strong>Doppler frequency slope: </strong>%.7f<br>\n", ofdr->dpplrslp);
  fprintf(fp, "<strong>Doppler frequency quadratic term: </strong>%.7f<br>\n", ofdr->dpplrqdr);
  fprintf(fp, "<strong>Flag indicating whether autofocus was used: </strong>%s<br>\n", ofdr->autfocsf);
  fprintf(fp, "<strong>Doppler frequency rate at the near range: </strong>%.7f<br>\n", ofdr->dpplrrat);
  fprintf(fp, "<strong>Doppler frequency rate slope: </strong>%.7f<br>\n", ofdr->dpratslp);
  fprintf(fp, "<strong>Doppler frequency rate quadratic term: </strong>%.7f<br>\n", ofdr->dpratqdr);
  fprintf(fp, "<strong>Nominal image resolution in azimuth: </strong>%.7f<br>\n", ofdr->imresaz);
  fprintf(fp, "<strong>Nominal image resolution in range: </strong>%.7f<br>\n", ofdr->imresra);
  fprintf(fp, "<strong>Pixel spacing in azimuth: </strong>%.7f<br>\n", ofdr->azpixspc);
  fprintf(fp, "<strong>Pixel spacing in range: </strong>%.7f<br>\n", ofdr->rapixspc);
  fprintf(fp, "<strong>On-board range compression flag: </strong>%s<br>\n", ofdr->rngcompf);
  fprintf(fp, "<strong>Bits per sample of the SAR signal data: </strong>%i<br>\n", ofdr->bitssamp);
  fprintf(fp, "<strong>Calibrator estimate: </strong>%.7f<br>\n", ofdr->calestim);
  fprintf(fp, "<strong>Data transfer bit error rate: </strong>%.7f<br>\n", ofdr->biterrrt);
  fprintf(fp, "<strong>Signal to noise ratio: </strong>%.7f<br>\n", ofdr->sigtonoi);
  fprintf(fp, "<strong>Estimated noise floor: </strong>%.7f<br>\n", ofdr->estnoifl);
  fprintf(fp, "<strong>Radiometric resolution: </strong>%.7f<br>\n", ofdr->radiores);
  fprintf(fp, "<strong>Num. of saturated points determined from hist: </strong>%i<br>\n",ofdr->nsatpnts);
  fprintf(fp, "<strong>Flag to indicate whether image is within spec: </strong>%s<br>\n", ofdr->inspecf);
  if (era)
    {
      fprintf(fp, "<strong>Chirp replica AGC value: </strong>%.7f<br>\n",ofdr->repl_agc);
      fprintf(fp, "<strong>Temp of RCVR LNA: </strong>%.7f<br>\n",ofdr->temp_rx_lna);
      fprintf(fp, "<strong>Temp of RCVR subsystem: </strong>%.7f<br>\n",ofdr->temp_rx_sub);
      fprintf(fp, "<strong>Temp of RCVR protector: </strong>%.7f<br>\n",ofdr->temp_rx_prot);
      fprintf(fp, "<strong>Temp of calib system: </strong>%.7f<br>\n",ofdr->temp_cal_sys);
      fprintf(fp, "<strong>RCVR AGC value: </strong>\t%.7f<br>\n",ofdr->rx_agc);
      fprintf(fp, "<strong>Pre CAL1 avg power: </strong>%.7f<br>\n",ofdr->pre_cal1_pow);
      fprintf(fp, "<strong>Pre CAL2 avg power: </strong>%.7f<br>\n",ofdr->pre_cal2_pow);
      fprintf(fp, "<strong>Post CAL1 avg power: </strong>%.7f<br>\n",ofdr->post_cal1_pow);
      fprintf(fp, "<strong>Post CAL2 avg power: </strong>%.7f<br>\n",ofdr->post_cal2_pow);
      fprintf(fp, "<strong>Replica avg power: </strong>%.7f<br>\n",ofdr->repl_pow);
      fprintf(fp, "<strong>Est scansar roll angle: </strong>%.7f<br>\n",ofdr->ssar_roll_ang);
    }
  fprintf(fp, "<strong>Comment field for documenting image anomalies: </strong>%s<br>\n", ofdr->comment);
  fprintf(fp, "</body>\n</html>\n");
  FCLOSE(fp);

  return;
}
