Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_import/",
        "#src/libasf_geocode/",
        "#src/libasf_raster/",
        "#src/libasf_convert/",
        "#src/libasf_vector/",
        "/usr/include/libshp",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libpng")

localenv.AppendUnique(LIBS = [
    "m",
    "asf",
    "asf_import",
    "asf_convert",
    "asf_proj",
    "asf_raster",
    "asf_vector",
    "asf_meta",
    "tiff",
    "geotiff",
    "xml2",
    "gtk-x11-2.0",
    "gdk_pixbuf-2.0",
    "gdk-x11-2.0",
    "pango-1.0",
    "gobject-2.0",
    "glade-2.0",
    "glib-2.0",
])

bins = localenv.Program("mapready", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

shares = localenv.File([
        "mapready.glade",
        "mapready.ico",
        "#src/asf/pixmaps/asf_seal.png",
        "#src/asf/pixmaps/bulb_icon.png",
        "#src/asf/pixmaps/asf_view_button.png",
        "#src/asf/pixmaps/trash_can.png",
        "#src/asf/pixmaps/process_all_files.png",
        "#src/asf/pixmaps/stop_s.png",
        "#src/asf/pixmaps/blue_books_help.png",
        "#src/asf/pixmaps/mediumASFlogo.png",
        "plugins.cfg",
        "mapready.txt",
        ])

localenv.Install(globalenv["inst_dirs"]["shares"], shares)

docs = localenv.File([
        "mapready.txt",
        ])

localenv.Install(globalenv["inst_dirs"]["docs"], docs)
