#!/bin/csh -f

#===============================================================================
# Filename:	mkall
# Description:	Script for making all dirmons in one command
# Creator:	Norbert Piega
# Notes:	
#
# SCCS Info:
#  %M%
#  %R%
#  %G%
#  %W%
#===============================================================================

# Make clean first before making each library
gnumake DM=ADEOS_DM cleanobjs all
#gnumake DM=CSA_DM   cleanobjs all
gnumake DM=ESA_DM   cleanobjs all
gnumake DM=NASDA_DM cleanobjs all
gnumake DM=WALPS_DM cleanobjs all
