C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:	calc_window.for
C--
C--  Description:	
C--	
C--  Notes:
C--
C-- ==========================================================================

C-----------------------------------------------------------------------
C SUBROUTINE CALC_WINDOW
C
C PURPOSE
C	CREATES AND DISPLAYS THE WINDOW FOR THE CHOSEN PROJECTION.
C
C $Logfile:   ACS003:[BLD.MPS.MAPR.SRC]CALC_WINDOW.FOV  $
C
C VARIABLES
C INPUT
C	PROJN		PROJECTION TYPE TO DISPLAY MAP
C	OBSLAT		CENTERING LATITUDE OF THE MAP (DEG)
C	OBSLON		CENTERING LONGITUDE OF THE MAP (DEG)
C	WSID  		WORKSTATION ID NUMBER
C	WNSIZE		SIZE OF THE WINDOW
C	MINLAT		MINIMUM LATITUDE OF THE WINDOW (DEG)
C	MAXLAT		MAXIMUM LATITUDE OF THE WINDOW (DEG)
C	MINLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	MAXLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	OBSMIN		MINIMUM LONITUDE OF THE WINDOW (DEG)
C	OBSMAX		MAXIMUM LONITUDE OF THE WINDOW (DEG)
C
C OUTPUT
C	MINX  		MINIMUM X-COORD OF THE WINDOW
C	MAXX  		MAXIMUM X-COORD OF THE WINDOW
C	MINY  		MINIMUM Y-COORD OF THE WINDOW
C	MAXY  		MINIMUM Y-COORD OF THE WINDOW
C	MINXWN		MINIMUM X-COORD OF THE WINDOW
C	MAXXWN		MAXIMUM X-COORD OF THE WINDOW
C	MINYWN		MINIMUM Y-COORD OF THE WINDOW
C	MAXYWN		MINIMUM Y-COORD OF THE WINDOW
C
C
C SUBROUTINE CALLS
C	SATVW	CREATES/DISPLAYS WINDOW FOR SATELLITE VIEW PROJECTION.
C	CYLIN	"                "      "   CYLIN, MERC, AND MILLER PROJS.
C	STRGR   "                "      "   POLAR STEREO PROJECTION.
C
C            
C ORIGINALLY WRITTEN BY RICHARD P. LEE     5-25-88
C MODIFIED FOR ASF BY CRAIG K. FUJIMOTO  8-01-88
C     
C MODIFICATIONS
C $Date$ $Revision$ $Author$
C 7/11/94  Nadia Adhami -port to UNIX/C 
C
C-----------------------------------------------------------------------
       SUBROUTINE CALC_WINDOW (WSID,PROJN,WNSIZE,
     1                    MINLAT,MAXLAT,MINLON,MAXLON,
     2                    OBSLAT,OBSLON,OBSMIN,OBSMAX,
     3                    MINX,MAXX,MINY,MAXY,
     4                    MINXWN,MAXXWN,MINYWN,MAXYWN)

      character*100 SccsFileID
     -/'@(#)calc_window.for	5.1 98/01/08 APS/ASF\0'/

       IMPLICIT NONE

C INPUT:

       INTEGER PROJN,WSID

       REAL WNSIZE
       REAL OBSLAT,OBSLON
       REAL MINLAT,MAXLAT,MINLON,MAXLON
       REAL OBSMIN,OBSMAX
     
C OUTPUT:
       REAL MINX,MAXX,MINY,MAXY
       REAL MINXWN,MAXXWN,MINYWN,MAXYWN

C-----------------------------------------------------------------------

C DEFINE SATELLITE VIEW WINDOW
       IF (PROJN .EQ. 1) THEN

         MINXWN = 0.0
         MAXXWN = 1.0
         MINYWN = 0.0
         MAXYWN = 1.0

C DEFINE MERC/CYLIN EQUID/MILLER CYLIN WINDOW
       ELSE IF (PROJN .EQ. 2 .OR. PROJN .EQ. 3 .OR. PROJN .EQ. 4) THEN

         CALL CYLIN (PROJN,OBSLAT,OBSLON,
     1               MINLAT,MAXLAT,OBSMIN,OBSMAX,
     6               MINX,MAXX,MINY,MAXY,
     7               MINXWN,MAXXWN,MINYWN,MAXYWN)

C DEFINE POLAR STEREOGRAPHIC WINDOW
       ELSE IF (PROJN .EQ. 5 .OR. PROJN .EQ. 6) THEN

C   CREATE AND DISPLAY STEREOGRAPHIC WINDOW

         CALL POLXY(PROJN,OBSLAT,OBSLON,
     1              MINLAT,MAXLAT,MINLON,MAXLON,
     2              MINX,MAXX,MINY,MAXY,
     3              MINXWN,MAXXWN,MINYWN,MAXYWN)

       END IF

 9999  CONTINUE
       RETURN
       END


C-----------------------------------------------------------------------
C SUBROUTINE CYLIN
C            
C PURPOSE
C	SETS THE MIN/MAX X/Y AND XWN/YWN VALUES FOR THE 
C	MERC/CYLIN/MILLER PROJECTIONS
C
C INPUT
C	PROJN 		PROJECTION TYPE TO DISPLAY MAP
C	OBSLAT		CENTERING LATITUDE OF THE MAP (DEG)
C	OBSLON		CENTERING LONGITUDE OF THE MAP (DEG)
C	MINLAT		MINIMUM LATITUDE OF THE WINDOW (DEG)
C	MAXLAT		MAXIMUM LATITUDE OF THE WINDOW (DEG)
C	MINLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	MAXLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	MINX  		MINIMUM X-COORD OF THE WINDOW
C
C OUTPUT
C	MAXX  		MAXIMUM X-COORD OF THE WINDOW
C	MINY  		MINIMUM Y-COORD OF THE WINDOW
C	MAXY  		MINIMUM Y-COORD OF THE WINDOW
C	MINXWN		MINIMUM X-COORD OF THE WINDOW
C	MAXXWN		MAXIMUM X-COORD OF THE WINDOW
C	MINYWN		MINIMUM Y-COORD OF THE WINDOW
C	MAXYWN		MINIMUM Y-COORD OF THE WINDOW
C
C INTERNAL
C	ZFAC  		ZOOM WINDOW SCALING FACTOR
C	DIFX  		LENGTH OF THE WINDOW
C	DIFY  		HEIGHT OF THE WINDOW
C
C WRITTEN BY RICHARD P. LEE  5-25-88
C-----------------------------------------------------------------------
       SUBROUTINE CYLIN2 (PROJN,OBSLAT,OBSLON,
     1                   MINLAT,MAXLAT,MINLON,MAXLON,
     2                   MINX,MAXX,MINY,MAXY,
     3                   MINXWN,MAXXWN,MINYWN,MAXYWN)

       IMPLICIT NONE
C INPUT:

       INTEGER PROJN
       REAL OBSLAT,OBSLON
       REAL MINLAT,MAXLAT,MINLON,MAXLON
C OUTPUT:
       REAL MINX,MAXX,MINY,MAXY
       REAL MINXWN,MAXXWN,MINYWN,MAXYWN
C INTERNAL:
       REAL ZFAC  /5.75/
       REAL DIFX,DIFY
       LOGICAL HIDDEN,BRNCUT
C-----------------------------------------------------------------------

C CALCULATE THE MINIMUM AND MAXIMUM LAT-LON TO X-Y COORD TRANSFORMATION
C   POINTS

       CALL LTRANS (PROJN,OBSLAT,OBSLON,
     1              MINLON,MINLAT,MINX,MINY,HIDDEN,BRNCUT)
       CALL LTRANS (PROJN,OBSLAT,OBSLON,
     1              MAXLON,MAXLAT,MAXX,MAXY,HIDDEN,BRNCUT)

C LENGTH AND HEIGHT OF THE WINDOW

       DIFX = MAXX - MINX
       DIFY = MAXY - MINY
            
C SET THE WORKSTATION WINDOW BOUNDARIES

       MINXWN = MINX - (DIFX / ZFAC)
       MAXXWN = MAXX + (DIFX / ZFAC)
       MINYWN = MINY - (DIFY / ZFAC)
       MAXYWN = MAXY + (DIFY / ZFAC)

C   SET WINDOW LENGTH TO MAXIMUM

       IF (MINXWN .LT. 0.0) MINXWN = 0.0
       IF (MAXXWN .GT. 1.0) MAXXWN = 1.0

C   SET WINDOW HEIGHT TO MAXIMUM

       IF (MINYWN .LT. 0.12) MINYWN = 0.12
       IF (MAXYWN .GT. 0.88) MAXYWN = 0.88

 9999  CONTINUE
       RETURN
       END
