C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:	dismwf.for
C--
C--  Description:	
C--	
C--  Notes:
C--
C-- ==========================================================================


C-----------------------------------------------------------------------
C SUBROUTINE DISMWF
C
C PURPOSE
C	READS AND DISPLAYS A MAP WINDOW FILE
C
C $Logfile:   ACS003:[BLD.MPS.MAPR.SRC]DISMWF.FOV  $
C
C INPUT
C	NSEG  		OVERLAY COUNT
C	CRSEGN		OVERLAY STATUS ARRAY
C	CRSEGT		OVERLAY NAME ARRAY
C	CRDARID		OVERLAY DARID ARRAY
C	PROJN		PROJECTION TYPE
C	WSID  		WORKSTATION ID NUMBER 
C	GRIDLN		GRID LINES FLAG 0=OFF 1=ON
C	OBSLAT,OBSLON	CENTER LAT/LON OF THE WINDOW (DEG)
C	OBSMIN,OBSMAX	MIN/MAX LON OF THE WINDOW (DEG)
C	LONPT		ARRAY OF GRID LONGITUDE DIVISIONS (DEG)
C	MINLAT,MAXLAT,
C	MINLON,MAXLON	MIN/MAX LAT/LON OF WINDOW
C	STMNLT,STMXLT,
C	STMNLN,STMXLN	INITIAL MIN/MAX LAT/LON OF THE WINDOW
C       START_LL        START WINDOW MIN/MAX LON/LAT
C OUTPUT
C	MINX,MAXX,
C	MINY,MAXY	MIN/MAX X/Y COORD OF THE DISPLAY
C	MINXWN,MAXXWN,
C	MINYWN,MAXYWN	MIN/MAX X/Y COORD OF THE WINDOW
C	IOS		RETURN STATUS
C INTERNAL
C	MWFIL		GKSM METAFILE
C	MWHDR		GKSM HEADER FILE
C	ERR		ERROR FLAG
C	MEM
C	I,J,CNT		COUNTERS
C	NUGRID		0 = NO NEW GRID GSEG NEEDED
C
C
C SUBROUTINE CALLS
C	GQSGWK		GKS CALL
C
C	MFINPUT		OPEN AND READ METAFILE HEADER FILE
C	MFINIT		INITIALIZE WINDOW VARIABLES
C	MFBLKOUT	BLOCK OUT WINDOW
C	METAFILE	LOAD IN OVERLAYS FROM METAFILE
C	DISSEG		DISPLAY SEGMENTS
C
C ORIGINALLY CODED BY RICHARD P. LEE  9-30-88
C MODIFIED BY CRAIG K. FUJIMOTO
C
C MODIFICATIONS
C $Date$ $Revision$ $Author$
C 7/11/94  Nadia Adhami -port to UNIX/C 
C
C-----------------------------------------------------------------------
      SUBROUTINE DISMWF (WSID,MWID,PROJN,WNSIZE,GRIDLN,
     1                   MINLAT,MAXLAT,MINLON,MAXLON,
     2                   OBSLAT,OBSLON,OBSMIN,OBSMAX,LONPT,
     3                   NSEG,CRSEGN,CRSEGT,CRDARID,
     4                   MINX,MAXX,MINY,MAXY,
     5                   MINXWN,MAXXWN,MINYWN,MAXYWN,
     6                   STMNLT,STMXLT,STMNLN,STMXLN,
     7                   START_LL,
     8                   IOS)

      character*100 SccsFileID
     -/'@(#)dismwf.for	5.1 98/01/08 APS/ASF\0'/
                          
      IMPLICIT NONE
C INPUT:

      CHARACTER*(*) CRSEGT(*)
      INTEGER PROJN,WSID,MWID,GRIDLN
      INTEGER CRSEGN(*),CRDARID(*),NSEG
      REAL WNSIZE,
     1     OBSLAT,OBSLON,OBSMIN,OBSMAX,
     2     MINLAT,MAXLAT,MINLON,MAXLON,
     3     LONPT(*),
     4     STMNLT,STMXLT,STMNLN,STMXLN,
     5     START_LL(2,2)

C OUTPUT:
      REAL MINX,MAXX,MINY,MAXY
      REAL MINXWN,MAXXWN,MINYWN,MAXYWN
      INTEGER IOS

C INTERNAL:
      CHARACTER*46 MWFIL,MWHDR
      INTEGER NUGRID
C-----------------------------------------------------------------------
C INIT FLAGS
      NUGRID = 0

C READ THE METAFILE INFORMATION
      CALL MFINPUT(MWFIL,MWHDR,PROJN,GRIDLN,WNSIZE,
     1             OBSLAT,OBSLON,
     2             MINLAT,MAXLAT,MINLON,MAXLON,
     3             STMNLT,STMXLT,STMNLN,STMXLN,
     4             START_LL,
     5             NSEG,CRSEGN,CRSEGT,CRDARID,
     6             IOS)
                                
      IF (IOS .NE. 0) THEN
        GO TO 9999
      END IF

C MAKE THE WINDOW SMALL WHILE LOADING METAFILE
      CALL MFBLKOUT(WSID)

      CALL DISMSGW('Reading GKS metafile...')

C RETRIEVE THE GSEGS FROM THE METAFILE
      CALL METAFILE(MWID,MWFIL,PROJN,
     1              MINLAT,MAXLAT,MINLON,MAXLON,
     2              OBSLAT,OBSLON,OBSMIN,OBSMAX,
     4              LONPT)


C CALCULATE THE WINDOW DIMENSIONS
      CALL CALC_WINDOW (WSID,PROJN,WNSIZE,
     1                   MINLAT,MAXLAT,MINLON,MAXLON,
     2                   OBSLAT,OBSLON,OBSMIN,OBSMAX,
     3                   MINX,MAXX,MINY,MAXY,
     4                   MINXWN,MAXXWN,MINYWN,MAXYWN)

       CALL DISMSGW('Resetting the window...')

C SET THE WINDOW
      CALL SET_WINDOW (WSID,WNSIZE,MINXWN,MAXXWN,MINYWN,MAXYWN)

C DISPLAY THE GSEGS
      CALL DISP_SEG (WSID,PROJN,NUGRID,GRIDLN,WNSIZE,
     1              MINLAT,MAXLAT,MINLON,MAXLON,
     2              OBSLAT,OBSLON,OBSMIN,OBSMAX,LONPT,
     3              NSEG,CRSEGN,
     4              MINX,MAXX,MINY,MAXY)

 9999 CONTINUE
      RETURN
      END
