C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:	diswmf.for
C--
C--  Description:	
C--	
C--  Notes:
C--
C-- ==========================================================================

C-----------------------------------------------------------------------
C   
C SUBROUTINE DISWMF
C
C PURPOSE
C	DISPLAYS A WORLD MAP FROM THE WORLD MAP DATABASE.
C	THE WORLD MAP IS BROKEN INTO SEVERAL GSEGS:
C	500 = THE GLOBE - HOLLOW
C	501 = THE GLOBE - FILLED
C	502 = THE WORLD - HOLLOW
C	503 = THE WORLD - FILLED
C	504 = THE GRID LINES
C	505 = THE GRID TEXT FOR DISPLAYING
C	506 = THE GRID TEXT FOR PLOTTING
C
C	THE HOLLOW GSEGS ARE FOR PLOTTING AND THE FILLED GSEGS
C	FOR DISPLAYING. INITIALLY, ALL GSEGS EXCEPT 506 ARE DISPLAYED.
C	GSEGS 504,505,506 ARE CREATED IN THE SUBROUTINE GRID.
C
C $Logfile:   ACS003:[BLD.MPS.MAPR.SRC]DISWMF.FOV  $
C
C VARIABLES
C INPUT
C	WSID		WORKSTATION ID NUMBER
C
C INPUT/OUTPUT
C	PROJN 		PROJECTION TYPE TO DISPLAY MAP
C	GRIDLN		DISPLAY GRID LINES (0=OFF OR 1=ON)
C	WNSIZE		SIZE OF THE WINDOW TO DISPLAY 
C	OBSLAT,OBSLON	CENTERING LAT/LON OF THE MAP (DEG)
C	OBSMIN,OBSMAX	MIN/MAX LONITUDE OF THE WINDOW (DEG)
C	MINLAT,MAXLAT,
C	MINLON,MAXLON	MIN/MAX LAT/LON OF THE WINDOW (DEG)
C	STMNLT,STMXLT,
C	STMNLN,STMXLN	INITIAL MIN/MAX LAT/LON OF THE WINDOW
C	START_LL	START WINDOW MIN/MAX LON/LAT
C	LONPT		
C	NSEG  		NUMBER OF SEGMENTS CREATED
C	CRSEGN		OVERLAY STATUS ARRAY
C	CRSEGT		OVERLAY NAME ARRAY
C	MINX,MAXX,
C	MINY,MAXY	MIN/MAX X/Y COORDS OF THE DISPLAY
C	MINXWN,MAXXWN,
C	MINYWN,MAXYWN	MIN/MAX X/Y COORDS OF THE WINDOW
C
C INTERNAL
C	XEDGE,YEDGE	ARRAY OF X/Y COORD POINTS ON UNIT CIRCLE
C	SEGNAM		NAME OF THE SEGMENT BEING CREATED
C
C
C SUBROUTINE CALLS
C        MAPINP
C        WINDOW  CREATES THE WINDOW FOR THE CHOSEN PROJECTION.
C        CRTSEG  INITIALTES THE CREATION OF
C        WORLD   DISPLAYS THE WORLD IN THE CURRENT WINDOW.
C        CLSSEG  CLOSES THE SEGMENT JUST CREATED
C        GRID    DISPLAYS THE GRID.
C        BORDER  DISPLAYS THE BORDER.
C                
C
C ORIGINALLY CODED BY RICHARD P. LEE     5-25-88
C MODIFIED FOR ASF BY CRAIG K. FUJIMOTO  8-01-88
C
C MODIFICATIONS
C $Date$ $Revision$ $Author$
C-----------------------------------------------------------------------
       SUBROUTINE DISWMF (WSID,PROJN,WNSIZE,GRIDLN,
     1                    MINLAT,MAXLAT,MINLON,MAXLON,
     2                    OBSLAT,OBSLON,OBSMIN,OBSMAX,LONPT,
     3                    NSEG,CRSEGN,CRSEGT,
     4                    MINX,MAXX,MINY,MAXY,
     5                    MINXWN,MAXXWN,MINYWN,MAXYWN,
     6                    STMNLT,STMXLT,STMNLN,STMXLN,
     7                    START_LL)

      character*100 SccsFileID
     -/'@(#)diswmf.for	5.1 98/01/08 APS/ASF\0'/

       IMPLICIT NONE
C INPUT:
      INTEGER WSID
C INPUT/OUTPUT:
       CHARACTER*(*) CRSEGT(*)
       INTEGER RES,PROJN,GRIDLN,NSEG,CRSEGN(*)
       REAL WNSIZE
       REAL MINLAT,MAXLAT,MINLON,MAXLON
       REAL OBSLAT,OBSLON,OBSMIN,OBSMAX
       REAL LONPT(*)
       REAL STMNLT,STMXLT,STMNLN,STMXLN
       REAL START_LL(2,2)
C OUTPUT:          
       REAL MINX,MAXX,MINY,MAXY
       REAL MINXWN,MAXXWN,MINYWN,MAXYWN
C INTERNAL:
       REAL XEDGE(720),YEDGE(720)
C-----------------------------------------------------------------------

C OBTAIN USER INPUTS AND INITIALIZE 

       CALL WINPUT (RES,PROJN,GRIDLN,WNSIZE,
     1              OBSLAT,OBSLON,OBSMIN,OBSMAX,
     2              MINLAT,MAXLAT,MINLON,MAXLON,
     3              LONPT,  
     5              STMNLT,STMXLT,STMNLN,STMXLN,
     5              START_LL)

                           
C CALCULATE THE WINDOW DIMENSIONS
      CALL CALC_WINDOW (WSID,PROJN,WNSIZE,
     1                   MINLAT,MAXLAT,MINLON,MAXLON,
     2                   OBSLAT,OBSLON,OBSMIN,OBSMAX,
     3                   MINX,MAXX,MINY,MAXY,
     4                   MINXWN,MAXXWN,MINYWN,MAXYWN)

C DISPLAY THE WINDOW
      CALL SET_WINDOW (WSID,WNSIZE,MINXWN,MAXXWN,MINYWN,MAXYWN)

C CREATE HOLLOW GLOBE SEGMENT - FOR PLOTTING
       CALL GCRSG (500)
       CALL GLOBE(PROJN,1,OBSLAT,OBSLON,
     1            MINX,MAXX,MINY,MAXY,
     1            XEDGE,YEDGE)
       CALL GCLSG ()

C CREATE FILL GLOBE SEGMENT
       CALL GCRSG (501)
       CALL GLOBE(PROJN,0,OBSLAT,OBSLON,
     1            MINX,MAXX,MINY,MAXY,
     1            XEDGE,YEDGE)
       CALL GCLSG ()
                                    
C CREATE HOLLOW WORLD SEGMENT - FOR PLOTTING
       CALL GCRSG (502)
       CALL WORLD (WSID,PROJN,RES,1,
     1             OBSLAT,OBSLON,
     3             XEDGE,YEDGE,
     4             MINX,MAXX,MINY,MAXY)
       CALL GCLSG ()
                                   
C CREATE FILL WORLD SEGMENT
       CALL GCRSG (503)
       CALL WORLD (WSID,PROJN,RES,0,
     1             OBSLAT,OBSLON,
     3             XEDGE,YEDGE,
     4             MINX,MAXX,MINY,MAXY)
       CALL GCLSG ()

C CREATE GRID SEGMENTS
       CALL GRID (WSID,PROJN,GRIDLN,
     1            MINLAT,MAXLAT,MINLON,MAXLON,
     2            OBSLAT,OBSLON,OBSMIN,OBSMAX,
     3            LONPT,
     4            MINX,MAXX,MINY,MAXY)

 9999  CONTINUE
       RETURN                             
       END                   
