C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:  sensorlist.inc
C--
C--  Description:
C--
C--  Notes:
C--
C-- ==========================================================================
C 
C     character*100 SccsFileID
C    -/'@(#)sensorlist.inc	5.1 98/01/08 APS/ASF\0'/
C
      CHARACTER*10 E1_SENSORLIST(30)
      CHARACTER*10 E2_SENSORLIST(30)
      CHARACTER*10 J1_SENSORLIST(30)
      CHARACTER*10 R1_SENSORLIST(30)
      CHARACTER*10 SS_SENSORLIST(30)
      COMMON  /E1_SENSORLIST/E1_SENSORLIST
      COMMON  /E2_SENSORLIST/E2_SENSORLIST
      COMMON  /J1_SENSORLIST/J1_SENSORLIST
      COMMON  /R1_SENSORLIST/R1_SENSORLIST
      COMMON  /SS_SENSORLIST/SS_SENSORLIST
 
      INTEGER E1_SENSORCOUNT
      INTEGER E2_SENSORCOUNT
      INTEGER J1_SENSORCOUNT
      INTEGER R1_SENSORCOUNT
      INTEGER SS_SENSORCOUNT
      COMMON  /E1_SENSORCOUNT/E1_SENSORCOUNT
      COMMON  /E2_SENSORCOUNT/E2_SENSORCOUNT
      COMMON  /J1_SENSORCOUNT/J1_SENSORCOUNT
      COMMON  /R1_SENSORCOUNT/R1_SENSORCOUNT
      COMMON  /SS_SENSORCOUNT/SS_SENSORCOUNT
 

