C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:	table_names.inc
C--
C--  Description:	
C--	
C--  Notes:
C--
C-- ==========================================================================

      character*100 SccsFileID
     -/'@(#)table_names.inc	5.1 98/01/08 APS/ASF\0'/


      INTEGER*4  ALL_COLS
      DATA       ALL_COLS/
     *           -1/

      INTEGER*4  PHASE
      DATA       PHASE/
     *           0/

      INTEGER*4  EPHEMERIS
      DATA       EPHEMERIS/
     *           1/

      INTEGER*4  SATSENSOR
      DATA       SATSENSOR/
     *           2/

      INTEGER*4  STATION
      DATA       STATION/
     *           3/


      INTEGER*4  DAR
      DATA       DAR/
     *           4/

      INTEGER*4  SITE
      DATA       SITE/
     *           5/

      INTEGER*4  DTK
      DATA       DTK/
     *           6/

      INTEGER*4  CVRG
      DATA       CVRG/
     *           7/

      INTEGER*4  SEG
      DATA       SEG/
     *           8/

      INTEGER*4  SSCVRG
      DATA       SSCVRG/
     *           9/

