C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:	window.for
C--
C--  Description:	
C--	
C--  Notes:
C--
C-- ==========================================================================

C-----------------------------------------------------------------------
C SUBROUTINE WINDOW
C
C PURPOSE
C	CREATES AND DISPLAYS THE WINDOW FOR THE CHOSEN PROJECTION.
C
C $LOGFILE$
C
C VARIABLES
C INPUT
C	PROJN		PROJECTION TYPE TO DISPLAY MAP
C	OBSLAT		CENTERING LATITUDE OF THE MAP (DEG)
C	OBSLON		CENTERING LONGITUDE OF THE MAP (DEG)
C	WSID  		WORKSTATION ID NUMBER
C	WNSIZE		SIZE OF THE WINDOW
C	MINLAT		MINIMUM LATITUDE OF THE WINDOW (DEG)
C	MAXLAT		MAXIMUM LATITUDE OF THE WINDOW (DEG)
C	MINLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	MAXLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	OBSMIN		MINIMUM LONITUDE OF THE WINDOW (DEG)
C	OBSMAX		MAXIMUM LONITUDE OF THE WINDOW (DEG)
C
C OUTPUT
C	MINX  		MINIMUM X-COORD OF THE WINDOW
C	MAXX  		MAXIMUM X-COORD OF THE WINDOW
C	MINY  		MINIMUM Y-COORD OF THE WINDOW
C	MAXY  		MINIMUM Y-COORD OF THE WINDOW
C	MINXWN		MINIMUM X-COORD OF THE WINDOW
C	MAXXWN		MAXIMUM X-COORD OF THE WINDOW
C	MINYWN		MINIMUM Y-COORD OF THE WINDOW
C	MAXYWN		MINIMUM Y-COORD OF THE WINDOW
C
C
C SUBROUTINE CALLS
C	DIFDEG	CALCULATES THE HEIGHT AND LENGTH OF THE WINDOW IN DEGREES.
C	SATVW	CREATES/DISPLAYS WINDOW FOR SATELLITE VIEW PROJECTION.
C	CYLIN	"                "      "   CYLIN, MERC, AND MILLER PROJS.
C	STRGR   "                "      "   POLAR STEREO PROJECTION.
C
C            
C ORIGINALLY WRITTEN BY RICHARD P. LEE     5-25-88
C MODIFIED FOR ASF BY CRAIG K. FUJIMOTO  8-01-88
C     
C MODIFICATIONS
C $DATE$ $REVISION$ $AUTHOR$
C-----------------------------------------------------------------------
       SUBROUTINE WINDOW (WSID,PROJN,PLOT,WNSIZE,
     1                    MINLAT,MAXLAT,MINLON,MAXLON,
     2                    OBSLAT,OBSLON,OBSMIN,OBSMAX,
     3                    MINX,MAXX,MINY,MAXY,
     4                    MINXWN,MAXXWN,MINYWN,MAXYWN,
     5                    DIFLAT,DIFLON)

      character*100 SccsFileID
     -/'@(#)window.for	5.1 98/01/08 APS/ASF\0'/

       IMPLICIT NONE

C INPUT:
c--port       INCLUDE 'SYS$LIBRARY:GKSDEFS.BND'

       INCLUDE 'GKS_ROOT:include/fgksenum.inc'


       INTEGER PROJN,WSID,PLOT

       REAL WNSIZE
       REAL OBSLAT,OBSLON
       REAL MINLAT,MAXLAT,MINLON,MAXLON
       REAL OBSMIN,OBSMAX
     
C OUTPUT:
       REAL MINX,MAXX,MINY,MAXY
       REAL MINXWN,MAXXWN,MINYWN,MAXYWN
       REAL DIFLAT,DIFLON

C-----------------------------------------------------------------------

C CLEAR DISPLAY DEVICE

       CALL GCLRWK (WSID,GALWAY)

C CALCULATE WINDOW HEIGHT AND LENGTH
       CALL DIFDEG(OBSLON,MINLAT,MAXLAT,MINLON,MAXLON,
     1             DIFLAT,DIFLON)

C SET VIEWPORT
       CALL VIEWPORT(WSID,PLOT,WNSIZE)


C DEFINE SATELLITE VIEW WINDOW
       IF (PROJN .EQ. 1) THEN

         CALL SATVW (MINX,MAXX,MINY,MAXY,
     3               MINXWN,MAXXWN,MINYWN,MAXYWN)

C DEFINE MERC/CYLIN EQUID/MILLER CYLIN WINDOW
       ELSE IF (PROJN .EQ. 2 .OR. PROJN .EQ. 3 .OR. PROJN .EQ. 4) THEN

         CALL CYLIN (PROJN,OBSLAT,OBSLON,
     1               MINLAT,MAXLAT,OBSMIN,OBSMAX,
     6               MINX,MAXX,MINY,MAXY,
     7               MINXWN,MAXXWN,MINYWN,MAXYWN)

C DEFINE POLAR STEREOGRAPHIC WINDOW
       ELSE IF (PROJN .EQ. 5 .OR. PROJN .EQ. 6) THEN

C   CREATE AND DISPLAY STEREOGRAPHIC WINDOW

         CALL POLXY(PROJN,OBSLAT,OBSLON,
     1              MINLAT,MAXLAT,MINLON,MAXLON,
     2              MINX,MAXX,MINY,MAXY,
     3              MINXWN,MAXXWN,MINYWN,MAXYWN)

       END IF

C SET WORKSTATION WINDOW
       CALL GSWKWN (WSID,MINXWN,MAXXWN,MINYWN,MAXYWN)

C UPDATE THE WORKSTATION
       CALL GUWK (WSID,GPERFO)

 9999  CONTINUE
       RETURN
       END

C---------------------------------------------------------------------
C SUBROUTINE SATVW
C
C PURPOSE
C	SETS WINDOW TO BE VIEWED
C
C OUTPUT 
C	MINX,MAXX
C	MINY,MAXY	MIN/MAX X/Y OF ZOOM WINDOW
C	MINXWN,MAXXWN
C	MINYWN,MAXYWN	MIN/MAX X/Y OF ZOOM WINDOW AND BORDER
C INTERNAL
C	DR		DUMMY INTEGER VARIABLE 
C	I		DO LOOP INDEX
C
C WRITTEN BY RICHARD P. LEE  5-25-88
C-----------------------------------------------------------------------
       SUBROUTINE SATVW (MINX,MAXX,MINY,MAXY,
     1                   MINXWN,MAXXWN,MINYWN,MAXYWN)

       IMPLICIT NONE
C INPUT:
c--port       INCLUDE 'SYS$LIBRARY:GKSDEFS.BND'

       INCLUDE 'GKS_ROOT:include/fgksenum.inc'

C OUTPUT
       REAL MINX,MAXX,MINY,MAXY
       REAL MINXWN,MAXXWN,MINYWN,MAXYWN
C INTERNAL:
C-----------------------------------------------------------------------

C       MINX = 0.0
C       MAXX = 1.0
C       MINY = 0.0
C       MAXY = 1.0

C       MINXWN = 0.1
C       MAXXWN = 0.9
C       MINYWN = 0.1
C       MAXYWN = 0.9

       MINXWN = 0.0
       MAXXWN = 1.0
       MINYWN = 0.0
       MAXYWN = 1.0

 9999  CONTINUE
       RETURN
       END



C-----------------------------------------------------------------------
C SUBROUTINE CYLIN
C            
C PURPOSE
C	SETS THE MIN/MAX X/Y AND XWN/YWN VALUES FOR THE 
C	MERC/CYLIN/MILLER PROJECTIONS
C
C INPUT
C	PROJN 		PROJECTION TYPE TO DISPLAY MAP
C	OBSLAT		CENTERING LATITUDE OF THE MAP (DEG)
C	OBSLON		CENTERING LONGITUDE OF THE MAP (DEG)
C	MINLAT		MINIMUM LATITUDE OF THE WINDOW (DEG)
C	MAXLAT		MAXIMUM LATITUDE OF THE WINDOW (DEG)
C	MINLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	MAXLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	MINX  		MINIMUM X-COORD OF THE WINDOW
C
C OUTPUT
C	MAXX  		MAXIMUM X-COORD OF THE WINDOW
C	MINY  		MINIMUM Y-COORD OF THE WINDOW
C	MAXY  		MINIMUM Y-COORD OF THE WINDOW
C	MINXWN		MINIMUM X-COORD OF THE WINDOW
C	MAXXWN		MAXIMUM X-COORD OF THE WINDOW
C	MINYWN		MINIMUM Y-COORD OF THE WINDOW
C	MAXYWN		MINIMUM Y-COORD OF THE WINDOW
C
C INTERNAL
C	ZFAC  		ZOOM WINDOW SCALING FACTOR
C	DIFX  		LENGTH OF THE WINDOW
C	DIFY  		HEIGHT OF THE WINDOW
C
C WRITTEN BY RICHARD P. LEE  5-25-88
C-----------------------------------------------------------------------
       SUBROUTINE CYLIN (PROJN,OBSLAT,OBSLON,
     1                   MINLAT,MAXLAT,MINLON,MAXLON,
     2                   MINX,MAXX,MINY,MAXY,
     3                   MINXWN,MAXXWN,MINYWN,MAXYWN)

       IMPLICIT NONE
C INPUT:
c--port       INCLUDE 'SYS$LIBRARY:GKSDEFS.BND'

       INTEGER PROJN
       REAL OBSLAT,OBSLON
       REAL MINLAT,MAXLAT,MINLON,MAXLON
C OUTPUT:
       REAL MINX,MAXX,MINY,MAXY
       REAL MINXWN,MAXXWN,MINYWN,MAXYWN
C INTERNAL:
       REAL ZFAC  /5.75/
       REAL DIFX,DIFY
       LOGICAL HIDDEN,BRNCUT
C-----------------------------------------------------------------------

C CALCULATE THE MINIMUM AND MAXIMUM LAT-LON TO X-Y COORD TRANSFORMATION
C   POINTS

       CALL LTRANS (PROJN,OBSLAT,OBSLON,
     1              MINLON,MINLAT,MINX,MINY,HIDDEN,BRNCUT)
       CALL LTRANS (PROJN,OBSLAT,OBSLON,
     1              MAXLON,MAXLAT,MAXX,MAXY,HIDDEN,BRNCUT)

C LENGTH AND HEIGHT OF THE WINDOW

       DIFX = MAXX - MINX
       DIFY = MAXY - MINY
            
C SET THE WORKSTATION WINDOW BOUNDARIES

       MINXWN = MINX - (DIFX / ZFAC)
       MAXXWN = MAXX + (DIFX / ZFAC)
       MINYWN = MINY - (DIFY / ZFAC)
       MAXYWN = MAXY + (DIFY / ZFAC)

C   SET WINDOW LENGTH TO MAXIMUM

       IF (MINXWN .LT. 0.0) MINXWN = 0.0
       IF (MAXXWN .GT. 1.0) MAXXWN = 1.0

C   SET WINDOW HEIGHT TO MAXIMUM

       IF (MINYWN .LT. 0.12) MINYWN = 0.12
       IF (MAXYWN .GT. 0.88) MAXYWN = 0.88

 9999  CONTINUE
       RETURN
       END
