C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:	winput.for
C--
C--  Description:	
C--	
C--  Notes:
C--
C-- ==========================================================================

C-----------------------------------------------------------------------
C SUBROUTINE WINPUT
C
C PURPOSE
C	PRESENTS THE WORLD MAP CONFIGURATION MENUS AND INITIALIZES
C	VARIABLES BASED ON THE USER'S SELECTIONS.
C
C      THE MAP WINDOW IS INITIALIZED TO THE ENTIRE WORLD. THE USER 
C      MAY SELECT THE CENTER LATITUDE AND LONGITUDE FOR SATELLITE VIEW.
C      THE USER MAY SELECT ONLY THE CENTER LONGITUDE FOR ALL OTHER
C      PROJECTIONS (CENTER LATITUDE IS SET TO ZERO DEGREES).  THE
C      ONLY WAY TO RECENTER IS TO READ IN WORLD MAP FILE AGAIN.
C 
C $Logfile:   ACS003:[BLD.MPS.MAPR.SRC]WINPUT.FOV  $
C
C INPUT/OUTPUT
C	MAPFIL		WORLD MAP FILE NAME
C	PROJN 		PROJECTION TYPE TO DISPLAY MAP
C	GRIDLN		DISPLAY GRID LINES 0 (OFF) OR 1 (ON)
C	WNSIZE		SIZE OF THE WINDOW TO DISPLAY ON
C
C OUTPUT
C	OBSLAT		CENTERING LATITUDE OF THE MAP (DEG)
C	OBSLON		CENTERING LONGITUDE OF THE MAP (DEG)
C	OBSMIN		MINIMUM LONITUDE OF THE WINDOW (DEG)
C	OBSMAX		MAXIMUM LONITUDE OF THE WINDOW (DEG)
C	MINLAT		MINIMUM LATITUDE OF THE WINDOW (DEG)
C	MAXLAT		MAXIMUM LATITUDE OF THE WINDOW (DEG)
C	MINLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	MAXLON		MINIMUM LONGITUDE OF THE WINDOW (DEG)
C	LONPT(		ARRAY OF LONGITUDE GRID DIVISIONS (DEG)
C	STMNLT		INITIAL MINIMUM LATITUDE OF THE WINDOW
C	STMXLT		INITIAL MAXIMUM LATITUDE OF THE WINDOW
C	STMNLN		INITIAL MINIMUM LONGITUDE OF THE WINDOW
C	STMXLN		INITIAL MINIMUM LONGITUDE OF THE WINDOW
C	START_LL	START MIN/MAX WINDOW LON/LAT 
C
C INTERNAL
C	IOS		READ STATEMENT I/O STATUS NUMBER      
C	LON   		LONGITUDE DIVISION INITIAL VALUES
C	I     		DUMMY INTEGER VARIABLE
C
C WRITTEN BY RICHARD P. LEE
C MODIFIED BY CRAIG K. FUJIMOTO
C
C MODIFICATION
C $Date$ $Revision$ $Author$
C-----------------------------------------------------------------------
      SUBROUTINE WINPUT (RES,PROJN,GRIDLN,WNSIZE,
     1                   OBSLAT,OBSLON,OBSMIN,OBSMAX,
     2                   MINLAT,MAXLAT,MINLON,MAXLON,
     3                   LONPT,
     4                   STMNLT,STMXLT,STMNLN,STMXLN,
     5                   START_LL)

      character*100 SccsFileID
     -/'@(#)winput.for	5.1 98/01/08 APS/ASF\0'/
 
      IMPLICIT NONE

C INPUT/OUTPUT:

      INTEGER RES,PROJN,GRIDLN

      REAL WNSIZE

C OUTPUT:

      REAL OBSLAT,OBSLON,OBSMIN,OBSMAX
      REAL MINLAT,MAXLAT,MINLON,MAXLON
      REAL STMNLT,STMXLT,STMNLN,STMXLN
      REAL START_LL(2,2)
      REAL LONPT(*)

C INTERNAL:

C-----------------------------------------------------------------------

C RESOLUTION?
      CALL ASK_WRES(RES)

C PROJECTION?
      CALL ASK_WPROJ(PROJN)

C GRID LINES?
      IF (PROJN .NE. 1) THEN
        CALL ASK_WGRID(GRIDLN)
      END IF

C INPUT MAP SIZE

C         CALL ASK_WNSIZE(WNSIZE)
C  CONVERT WNSIZE TO %   
C         WNSIZE = WNSIZE / 100.0

C DEFAULT SIZE OF MAP WINDOW
      WNSIZE = 1.0

C SET CENTERING TO 0,0
      OBSLAT = 0.0
      OBSLON = 0.0

C SET MIN/MAX LATS
C MERCATOR PROJECTION
      IF (PROJN .EQ. 3) THEN
        MINLAT = -85.0
        MAXLAT = 85.0
C POLAR STEREO NORTH
      ELSE IF (PROJN .EQ. 5) THEN
        MINLAT = 90.0
        MAXLAT = 0.0
C POLAR STEREO SOUTH
      ELSE IF (PROJN .EQ. 6) THEN
        MINLAT = -90.0
        MAXLAT = 0.0
C SAT VIEW,MILLER CYLIN,CYLIN EQUI
      ELSE
        MINLAT = -89.99
        MAXLAT = 89.99
      END IF

C SET MIN/MAX LONS
      IF (PROJN.NE.5 .AND. PROJN.NE.6) THEN
        MINLON = -179.99
        MAXLON = 179.99
      ELSE
        MINLON = 0.0
        MAXLON = 0.0
      END IF

C SET INITIAL WINDOW HOLD VARIABLES
      STMNLT = MINLAT
      STMXLT = MAXLAT
      STMNLN = MINLON
      STMXLN = MAXLON

C SET START WINDOW HOLD VARIABLES
      START_LL(1,1) = MINLON
      START_LL(1,2) = MAXLON
      START_LL(2,1) = MINLAT
      START_LL(2,2) = MAXLAT

C GET CENTER LAT/LON FROM USER
      CALL GET_CENTER (PROJN,OBSLAT,OBSLON)

C SET MIN/MAX LON AND LONPT ARRAY
      CALL CALC_CENTER (OBSLAT,OBSLON,OBSMIN,OBSMAX,LONPT)

 9999 CONTINUE
      RETURN
      END
