# Makefile for: register_lzceos
# Module Author: Tom Logan 
# Module Description: C schell scripts for sub-pixel registration
# Makefile date: 3/00 

include ../../make_support/system_rules

all: register_lzceos
	cp register_lzceos $(BINDIR)/register_lzceos
	cp *.1 ../../man/cat1
