#!/bin/sh
#
# NAME: register_lzceos
#
# SYNOPSIS: register_lzceos <file 1> <file 2> <igram>
#                     [ <grid resolution> [ <line 1> <line 2> ] ]
#  <file 1> an ASF LZP ceos file (.D & .L or .raw & .ldr);
#                you must include the .D or .raw extension
#  <file 2> an ASF LZP ceos file (.D & .L or .raw & .ldr);
#                you must include the .D or .raw extension
#  <igram> the output interferogram (.amp, .phase, .ddr)
#  [ <grid resolution> ] is the grid resolution for fico(1).
#                           (the default is 20, for a 20x20 grid)
#  <line 1>  first line to process for file #1
#  <line 2>  first line to process for file #2
#
# DESCRIPTION:
#
#  Register_lzceos will run the Alaska SAR processor
#  on the two images, then coregister the two images
#  using resolve, fico, fit_line, and calc_deltas,
#  then re-process the second image so that it matches
#  up with (is coregistered with) the first.
#  The result will be an inteferogram.
#  After this, you can generate a DEM with tandem_ifm.
#
#  The register_lzceos script automates the process of sub-pixel
#  registration for ASF Level-Zero Ceos data.  This script will take
#  the data, SAR process it, sub-pixel register it, and make it into
#  an interferogram.
#
#  After running this script, you can generate a DEM with
#  tandem_ifm(1), or use the interferogram for your own science.
#
# EXTERNAL ASSOCIATES:
#    NAME:               USAGE:
#    ---------------------------------------------------------------
#    lz2raw
#    avg_in_dop 
#    aisp 
#    resolve
#    fico 
#    register_slc
#    fit_line 
#    metadata
#    igram 
#    coh
#
# FILE REFERENCES:
#    NAME:               USAGE:
#    ---------------------------------------------------------------
#
# PROGRAM HISTORY:
#    VERS:   DATE:  AUTHOR:      PURPOSE:
#    ---------------------------------------------------------------
#    1.0			Initial development
#    1.1			Corrected "rm avedop" to "rm avdop".
#    1.2 			Updated for new FICO, changed temp. 
#				filenames to start with reg/.
#    2.0 			Modified from register_ccsd script
#    2.5     2000   Tom Logan	New average dop calc
#				Calc start of last patch rather than hardcode
#
# HARDWARE/SOFTWARE LIMITATIONS:
#
# ALGORITHM DESCRIPTION:
#
# ALGORITHM REFERENCES:
#
# BUGS
#	
#****************************************************************************
#								            *
#   Register_lzceos will run the Alaska SAR processor on the two images,    *
#		    then coregister the two images 			    *
#   Copyright (C) 2001  ASF Advanced Product Development    	    	    *
#									    *
#   This program is free software; you can redistribute it and/or modify    *
#   it under the terms of the GNU General Public License as published by    *
#   the Free Software Foundation; either version 2 of the License, or       *
#   (at your option) any later version.					    *
#									    *
#   This program is distributed in the hope that it will be useful,	    *
#   but WITHOUT ANY WARRANTY; without even the implied warranty of    	    *
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the   	    *
#   GNU General Public License for more details.  (See the file LICENSE     *
#   included in the asf_tools/ directory).				    *
#									    *
#   You should have received a copy of the GNU General Public License       *
#   along with this program; if not, write to the Free Software		    *
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.               *
#									    *
#       ASF Advanced Product Development LAB Contacts:			    *
#	APD E-mail:	apd@asf.alaska.edu 				    *
# 									    *
#	Alaska SAR Facility			APD Web Site:	            *	
#	Geophysical Institute			www.asf.alaska.edu/apd	    *
#      	University of Alaska Fairbanks					    *
#	P.O. Box 757320							    *
#	Fairbanks, AK 99775-7320					    *
#								  	    *
#**************************************************************************/
#
if [ ! $# -eq 3 -a ! $# -eq 4 -a ! $# -eq 6 ]
then
	echo "Register_lzceos:"
	echo "Usage: register_lzceos <file 1> <file 2> <igram> "
	echo "                     [ <grid resolution> [ <line 1> <line 2>] ]"
	echo ""
	echo "  <file 1> an ASF LZP ceos file (.D & .L or .raw & .ldr);"
	echo "		you must include the .D or .raw extension"
	echo "  <file 2> an ASF LZP ceos file (.D & .L or .raw & .ldr);"
	echo "		you must include the .D or .raw extension"	
	echo "  <igram> the output interferogram (.amp, .phase, .ddr)"
	echo "  [ <grid resolution> ] is the grid resolution for fico(1)."
	echo "                           (the default is 20, for a 20x20 grid)"
	echo "  <line 1>  start line for image 1 (default=0)"
	echo "  <line 2>  start line for image 2 (default=0)"
	echo ""
	echo "Register_lzceos will run the Alaska SAR processor"
	echo "on the two images, then coregister the two images"
	echo "using resolve, fico, fit_line, and calc_deltas,"
	echo "then re-process the second image so that it matches "
	echo "up with (is coregistered with) the first."
	echo "The result will be an inteferogram."
	echo "After this, you can generate a DEM with tandem_ifm."
	echo "\nVersion 2.5, ASF SAR TOOLS"
	exit 1
fi

#rm="echo Remove "
rm="/bin/rm -r"
gridRes=$4
dop="-d 1 -c reg/avedop"
if [ $# -eq 6 ]
then
	aisp1_shift=$5
	aisp2_shift=$6
else
	aisp1_shift=0
	aisp2_shift=0
fi

mkdir reg

ceos2raw $1 a
ceos2raw $2 b

# if using old CEOS extension make links with the new extensions
image1=`echo $1 | awk -F. '{print $1}'`	#1st image base name
ext1=`echo $1 | awk -F. '{print $2}'`	#1st image extension
flag1D=1				
flag1L=1
if [ $ext1 = "raw" ]			#if the 1st image is .raw
then					#create .L & .D links to pose for .raw & .ldr
	if [ ! -r $image1.D ]		#if image1.D doesn't exist
	then				#make the link
		ln -s $1 $image1.D
		flag1D=0		#set flag for image1.D link to true
	fi
	if [ ! -r $image1.L ]		#if image1.L doesn't exist
	then				#make the link
		ln -s $image1.ldr $image1.L
		flag1L=0		#set flag for image1.L link to true
	fi
fi
image2=`echo $2 | awk -F. '{print $1}'`	#2nd image base name
ext2=`echo $2 | awk -F. '{print $2}'`	#2nd image extension
flag2D=2
flag2L=2
if [ $ext2 = "raw" ]			#if 2nd image is .raw
then					#create .L & .D links to pose for .raw & .ldr
	if [ ! -r $image2.D ]		#if image2.D doesn't exist
	then				#make the link
		ln -s $2 $image2.D
		flag2D=0		#set flag for image2.D link to true
	fi
	if [ ! -r $image2.L ]		#if image2.L doesn't exist
	then				#make the link
		ln -s $image2.ldr $image2.L
		flag2L=0		#set flag for image2.L link to true
	fi
fi

echo ""
echo "Calculating the average doppler term"
avg_in_dop a b reg/avedop
echo ""

###-------------------------------------------------------###
### Co-Register the top of image 1 to the top of image 2  ###
###-------------------------------------------------------###
echo "Co-registering first patch"

aisp1=`expr $aisp1_shift + 0`
aisp2=`expr $aisp2_shift + 0`
cp $image1.L a.L
cp $image2.L b.L

### Create the first patch from image 1 ###
	echo aisp -p 1 $dop -l $aisp1 a reg/a_p1
	     aisp -p 1 $dop -l $aisp1 a reg/a_p1
	cp a.L reg/a_p1.L

### Create the first patch from image 2###
	echo aisp -p 1 $dop -l $aisp2 b reg/b_p1
	     aisp -p 1 $dop -l $aisp2 b reg/b_p1
	cp b.L reg/b_p1.L

### Estimate the initial offsets from reg/a to reg/b ###
	echo resolve reg/a_p1 reg/b_p1 base.00 reg/ctrl1
	     resolve reg/a_p1 reg/b_p1 base.00 reg/ctrl1

### Perform sub-pixel correlation
	fico reg/a_p1 reg/b_p1 reg/ctrl1 reg/fico1 $gridRes

# Check to see if fico completed sucessfully.
if [ $? -eq 101 ]
then
	echo "Error: Fico could not find many offsets with"
	echo "interferometric phase in the top patch."
	echo "This means the interferogram"
	echo "is either mis-registered or just bad."
	echo "This can indicate any number of problems-- some can be fixed by"
	echo "processing the images separately, then co-registering them."
	echo "Register_lzceos will now attempt this."
	aisp $dop -l $aisp1 a a
	aisp $dop -l $aisp2 b b
	register_cpx a b $3 $gridRes
	exit 2
fi

	fit_line reg/fico1 reg/line1

###------------------------------------------###
### CORRELATE THE LAST PATCH FROM EACH IMAGE ###
###------------------------------------------###
echo "Co-registering last patch"

# find last patch for two the images
# get the last line number for the first image
	metadata i $image1.D -f
	lastLineNo1=`awk '$1=="Lines" {print $6}' $image1.ifiledr`

# get the last line number for the second image
	metadata i $image2.D -f
	lastLineNo2=`awk '$1=="Lines" {print $6}' $image2.ifiledr`

# Remove temporary metadata info files
	$rm $image1.ifiledr $image2.ifiledr

# Use the lesser last line of the two images
#	and backtrack one patch
if [ $lastLineNo1 -lt $lastLineNo2 ]
then
	lastLineNo=`expr $lastLineNo1 - 4096`
else
	lastLineNo=`expr $lastLineNo2 - 4096`
fi

aisp1=`expr $aisp1_shift + $lastLineNo`
aisp2=`expr $aisp2_shift + $lastLineNo`

# Create the last patch from image 1 
	echo aisp -p 1 $dop -l $aisp1 a reg/a_pL
	     aisp -p 1 $dop -l $aisp1 a reg/a_pL
	cp a.L reg/a_pL.L

# Create the last patch from image 2
	echo aisp -p 1 $dop -l $aisp2 b reg/b_pL
	     aisp -p 1 $dop -l $aisp2 b reg/b_pL
	cp b.L reg/b_pL.L

# Estimate the initial offsets from reg/a to reg/b
	echo resolve reg/a_pL reg/b_pL base.00 reg/ctrlL
	     resolve reg/a_pL reg/b_pL base.00 reg/ctrlL

# Perform sub-pixel correlation
	fico reg/a_pL reg/b_pL reg/ctrlL reg/ficoL $gridRes
# Check to see if fico completed sucessfully.
if [ $? -eq 101 ]
then
	echo "Error: Fico could not find many offsets with"
	echo "interferometric phase in the bottom patch.  "
	echo "This means the interferogram"
	echo "is either mis-registered or just bad."
	echo "This can indicate any number of problems-- some can be fixed by"
	echo "processing the images separately, then co-registering them."
	echo "Register_lzceos will now attempt this."
	aisp $dop -l $aisp1 a a
	aisp $dop -l $aisp2 b b
	register_cpx a b $3 $gridRes
	exit 2
fi
	fit_line reg/ficoL reg/lineL

	calc_deltas reg/line1 reg/lineL $lastLineNo reg/deltas

###------------------------------------------###
### PROCESS Images, now lined up.            ###
###------------------------------------------###
echo "Processing input image 1"
aisp1=`expr $aisp1_shift + 0`
aisp2=`expr $aisp2_shift + 0`
echo aisp $dop -l $aisp1 a a
     aisp $dop -l $aisp1 a a

echo "Processing input image 2"
echo aisp -o reg/deltas $dop -l $aisp2 b b_corr
     aisp -o reg/deltas $dop -l $aisp2 b b_corr

# Remove temporary links	
if [ $flag1D ]
then
	$rm $image1.D
fi
if [ $flag1L ]
then
	$rm $image1.L
fi
if [ $flag2D ]
then
	$rm $image2.D
fi
if [ $flag2L ]
then
	$rm $image2.L
fi

igram a b_corr $3
coh a b_corr $3_coh
#$rm b_corr*

	echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	echo register_lzceos complete
	echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

