C--  Copyright (c)1996, California Institute of Technology.
C--  U.S. Government Sponsorship acknowledged.
C-- ==========================================================================
C--
C--  Fortran Filename:	f77apspath.inc
C--
C--  Description:	
C--	
C--  Notes:
C--
C-- ==========================================================================
C
C
C  This file must be consistent with the C file apspath.h
C

C--   character*100 SccsFileID
C--  -/'@(#)f77apspath.inc	5.1 98/01/08 APS/ASF\0'/

DATA/ APS_TEMP / 0/
DATA/ APS_EPHMIN / 1/
DATA/ APS_EPHMOUT/ 2/
DATA/ APS_ORBGIN / 3/
DATA/ APS_ORBGOUT/ 4/
DATA/ APS_MAPPER / 5/

