Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_import/",
        "#src/libasf_vector/",
        "/usr/include/libshp",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "libasf_import",
    "libasf_vector",
    "shp"
])

bins = localenv.Program("convert2vector", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
