Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include/",
        "#src/asf_meta/",
        "#src/asf/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        "/usr/include/libshp",
        ])

localenv.ParseConfig("pkg-config --cflags --libs gsl")

localenv.AppendUnique(LIBS = [
    "m",
    "asf",
    "asf_meta",
    "asf_raster",
    "shp",
])

libs = localenv.SharedLibrary("libasf_sar", [
        "gr2sr.c",
        "sr2gr.c",
        "reskew_dem.c",
        "deskew_dem.c",
        "deskew.c",
        "create_dem_grid.c",
        "poly.c",
        "fit_poly.c",
        "fetcher.c",
        "remap_poly.c",
        "mfd.c",
        "to_sr.c",
        "refine_offset.c",
        "interp_dem_holes.c",
        "find_band.c",
        "classify.c",
        "polarimetry.c",
        "farcorr.c",
        "calibrate.c",
        "calc_number_looks.c",
        "point_target_analysis.c",
        "c2p.c",
        ])

shares = [
    localenv.File([
        "polarimetry.cfg",
        "point_target_analysis.cfg",
    ]),
    localenv.Dir([
        "#src/libasf_sar/classifications",
    ]),
]



localenv.Install(globalenv["inst_dirs"]["libs"], libs)
localenv.Install(globalenv["inst_dirs"]["shares"], shares)

