# Makefile for: register_ccsd
# Module Author: Orion Lawlor
# Module Description: C schell scripts for sub-pixel registration
# Makefile date: 6/97

include ../../make_support/system_rules

all: register_ccsd
	cp register_ccsd $(BINDIR)
	-chmod 775 $(BINDIR)/register_ccsd
	cp *.1 ../../man/cat1
