Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#include",
        "#src/asf",
        "#src/asf_meta",
        "#src/libasf_proj",
        "#src/libasf_raster",
        "#src/libasf_geocode",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
    "asf_geocode",
])

bins = localenv.Program("asf_geocode", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

