Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        ])


localenv.AppendUnique(LIBS = [
    "m",
    "asf",
    "asf_meta",
])

bins = localenv.Program("update_state", Glob("*.c"))

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
