Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_meta",
])

bins = localenv.Program("sample_plugin", ["sample_plugin.c"])

localenv.Install(globalenv["inst_dirs"]["bins"], bins)

# run the unit test, and set its dependencies
test_result = localenv.UnitTest(
    [
        "sample_plugin.t.c",
        "test_main.t.c",
    ],
    [bins],
    LIBS = ["cunit"],
    RPATH = []
)
