#!/bin/ksh -p
#
# DopPlot: this program extracts the doppler frequency 
# from ordinary ASF CEOS metadata, plots it against
# the frame number, and dumps the result to a file.
#
# The output file has the format:
#
#     <frame number> <Doppler value (Hz)> <ASP Version> <PRF> <filename>
#
# ASF Software Tools, Version 1.1,  Orion Lawlor,T. Logan 4/98
#

# Check for CLA
if [ -z $1 ]
then
	echo "Usage: dopPlot <rev. number>"
	exit 1
fi

# Make a list of leader files that match the pattern
echo 'Printing dopplers for rev. '$1'...'
metaList=`ls -1 */*/*.L | grep $1 `
if [ -z $metaList ]
then
	echo "Error! No files matching pattern "$1" found!"
	exit 1
fi

# Remove old version of file; create new version of file
rm -f dopPlot/dop_$1 > /dev/null 2>&1

#
# Read information for each file matching the given pattern
#

for fileName in $metaList
do
	echo 'Processing file ' $fileName
	
# Print frame number
	metadata f $fileName | grep "SPS image identifier" | \
		awk -F= '{ORS=" ";print substr($2,3,3)}' >> dopPlot/dop_$1
# Print doppler frequency
	metadata f $fileName | grep "Doppler frequency at the near range" | \
		awk -F= '{ORS=" ";print $2}' - >> dopPlot/dop_$1
# Print processor version number
	metadata f $fileName | grep "Version of the ASP" | \
		awk -F= '{ORS=" ";print $2}' - >> dopPlot/dop_$1
# Print image center latitude
	metadata f $fileName | grep "Pulse repitition frequency (prf)" | \
		awk -F= '{ORS=" ";print $2}' - >> dopPlot/dop_$1
# Print image name and path
	echo $fileName >> dopPlot/dop_$1
	
done

# Plot the result graphically.
cat dopPlot/dop_$1 | plotcol 1 2
echo "The frame number vs. doppler data plotted above is in dopPlot/dop_"$1

#
# Perform Doppler Trending Analysis
#
dopTrend dopPlot/dop_$1

