include ../mk.common



SOURCE=data_cuts.java image_data.java point_target_analysis_results.java\
              lobe.java location.java resolution.java pt_anal.java \
              islr.java pslr.java clutter.java \
              side_lobe.java DEBUG.java

all:
	$(JAVAC) $(SOURCE)
	cp *.class $(JAVA)

clean:
	rm -f *.class

