#ifndef _DIFFMETA_TOLERANCES_H_
#define _DIFFMETA_TOLERANCES_H_

// General Block
#define DM_MAX_ORBIT 99999
#define DM_MIN_FRAME -1
#define DM_MAX_FRAME 7200
#define DM_MAX_BANDCOUNT MAX_BANDS // Rudi says 1000
#define DM_MIN_LINECOUNT 10
#define DM_MAX_LINECOUNT 1000000
#define DM_MIN_SAMPLECOUNT 10
#define DM_MAX_SAMPLECOUNT 10000
#define DM_MIN_STARTLINE 0
#define DM_MIN_STARTSAMPLE 0
#define DM_MIN_PIXELSIZE 1.0
#define DM_MAX_PIXELSIZE 1500.0
#define DM_MIN_MAJOR_AXIS 6377500.0
#define DM_MAX_MAJOR_AXIS 6378500.0
#define DM_MIN_MINOR_AXIS 6356000.0
#define DM_MAX_MINOR_AXIS 6357000.0
#define DM_MIN_BIT_ERROR_RATE 0.0
#define DM_MAX_BIT_ERROR_RATE 1.0
#define DM_MIN_MISSING_LINES 0
#define DM_MAX_MISSING_LINES 10000

// SAR Block
#define DM_MIN_LOOK_COUNT 1
#define DM_MAX_LOOK_COUNT 5
#define DM_MIN_DESKEWED 0
#define DM_MAX_DESKEWED 1
#define DM_MIN_ORIGINAL_LINE_COUNT DM_MIN_LINECOUNT
#define DM_MAX_ORIGINAL_LINE_COUNT DM_MAX_LINECOUNT
#define DM_MIN_ORIGINAL_SAMPLE_COUNT DM_MIN_SAMPLECOUNT
#define DM_MAX_ORIGINAL_SAMPLE_COUNT DM_MAX_SAMPLECOUNT
#define DM_MIN_LINE_INCREMENT 1
#define DM_MAX_LINE_INCREMENT 100
#define DM_MIN_SAMPLE_INCREMENT 1
#define DM_MAX_SAMPLE_INCREMENT 100
#define DM_MIN_RANGE_TIME_PER_PIXEL 1E-08
#define DM_MAX_RANGE_TIME_PER_PIXEL 1E-07


#endif // _DIFFMETA_TOLERANCES_H_

