Import("env")
env = env.Clone()

env.AppendUnique(CPPPATH = [
        "#include/",
        "#src/asf/",
        ])
    
libs = env.SharedLibrary("asf_fft", [
        "dxpose.c",
        "fft2d.c",
        "fftlib.c",
        "matlib.c",
        "fftext.c",
        ])

mans = env.File([
        "asf_fft.man",
        ])

products = {"libs": libs, "mans": mans}

# run the unit test, and set its dependencies
test_program = None
test_result = env.UnitTest("test.semaphore", test_program)
for product in products.values():
    Depends(test_result, product)

Return("products")
