Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        "#src/libasf_sar",
        ])


localenv.AppendUnique(LIBS = [
    "asf",
    "asf_sar",
])

bins = localenv.Program("sr2gr", Glob("*.c"))
docs = localenv.File(["sr2gr.1"])

localenv.Install(globalenv["inst_dirs"]["bins"], bins)
localenv.Install(globalenv["inst_dirs"]["docs"], docs)
