.TH resolve 1 "June 1997"
.SH NAME:
resolve \- calculate the pixel offset and baseline between two images 
.SH SYNOPSIS:
.B "resolve"
.BI " <img1> <img2> <baseline> <ctrl-file> [-log <file>] [-quiet]"
.SH DESCRIPTION:
Using orbital metadata and a FFT on the data files,
.B "resolve"
calculates the pixel offset of the second image to the first. 
.B "Resolve"
also creates a baseline file called \fIbaseline\fP. This file contains the 
calculated baseline coordinates (both parallel and perpendicular) of the 
two images plus the rate of change of these two values across the scene. The
file format is perpendicular baseline, rate of change, parallel baseline, and
rate of change. The rate of change is determined in meters per scene.
.PP
.B "Resolve"
also creates a parameter file to be used with fico, the sub-pixel image 
registration program.  It does this by lining up the amplitude images
of the given complex scenes with 
.BR "fftMatch"

.SH COMMAND LINE OPTIONS:
.TP 8
.B img1
First input image. This image is usually the earlier image of the pair. 
The data format is either a short integer complex scene from ASF with
the appropriate metadata file(s), or float complex (.cpx) with a ddr
and valid ASF metadata (.L or .meta).  No extension should be specified.
.TP 8
.B img2
Second input image. This image is usually the later image of the pair. 
The data format is either a short integer complex scene from ASF with
the appropriate metadata file(s), or float complex (.cpx) with a ddr
and valid ASF metadata (.L or .meta).  No extension should be specified.
.TP 8
.B baseline
Baseline file. This file will be created and the computed baseline values 
written here.  By convention, the baseline estimate is called base.00.
.TP 8
.B ctrl-file
Fico parameter file. This file will be created and the necessary parameters
for fico will be entered.
.SH ERROR MESSAGES:
.B MESSAGE_GIVEN:  REASON:
-----------------------------------------------------------------
.SH EXAMPLES:
.ce 1
example% resolve 100 200 foo.base foo.ctrl
.PP
After calculating the image shift between these two images,
.B "Resolve"
will create the fico control file, foo.ctrl, using these and other parameters.
The calculated baseline will be placed in the file foo.base.  The input scenes
are assumed to be .cpx float complex data.
.PP
.PP
.SH SEE ALSO:
.BR tandem_ifm (1)
.BR fico (1)
.BR fftMatch (1)
.BR igram (1)
.SH HARDWARE/SOFTWARE LIMITATIONS:
.SH BUGS:
.SH AUTHOR:
.TP 8
Orion Lawlor, Alaska SAR Facility, Fairbanks, AK
.SH CONTACT:
\tapd@asf.alaska.edu
\tor visit http://www.asf.alaska.edu/apd

