###############################################################################
#
# File:         makefile
#
# Function:     Make file for the IMS Example source tree.
#
# Author:       S. Hardman
#
# Date:         6/3/95
#
###############################################################################

include ../makedefs

all:	appl

appl:	
	cd clnt_app; $(MAKE) all

clean:
	cd clnt_app; $(MAKE) clean

install:
	cd clnt_app; $(MAKE) install
