Import("globalenv")
localenv = globalenv.Clone()

localenv.AppendUnique(CPPPATH = [
        "#src/asf/",
        "#include/",
        "#src/asf_meta/",
        "#src/libasf_proj/",
        "#src/libasf_raster/",
        "#src/libasf_sar",
        ])

localenv.ParseConfig("pkg-config --cflags --libs libgeotiff")
localenv.ParseConfig("pkg-config --cflags --libs glib-2.0")

localenv.AppendUnique(LIBS = [
    "asf",
    "asf_sar",
])

bins = localenv.Program("to_sr", Glob("*.c"))

globalenv.Install(globalenv["inst_dirs"]["bins"], bins)
